Feat(Command service): Input batching for VictoriaMetrics
epiphany-platform/CommonDataLayer pull request #105
Opened 2020-12-16 15:44 UTC by Tesel

- [ ] alter command-service payload deserialization
- [ ] insert collected array into existing endpoint
- [x] write python tests to test your solution
- [ ] write unit tests to cover deserialization and serialization

2020-12-16 16:35 UTC, luke-biel requested changes

2020-12-16 16:35 UTC, luke-biel commented on tests/common/cdl_env.py
> +        cdl_env.stop()
`CdlEnv` is a wrapper over TestContainers already. I say, remove it and place it's logic here

2020-12-16 16:35 UTC, luke-biel commented on tests/common/kafka.py
> +        kafka_producer.close()
This is redundant. When leaving scope, connection is close. It cannot leak.

2020-12-16 16:35 UTC, luke-biel commented on tests/docker-compose.yml
> +    #  - ./docker-volume/victoria_metrics/db:/victoria-metrics-data
No need to keep comments in testing docker-compose

2020-12-16 16:35 UTC, luke-biel commented on tests/command_service/test_victoria_insertion.py
> +    "VICTORIA_METRICS_URL", "http://127.0.0.1:12345")
With testcontainers this shouldn't be configurable from env.

2020-12-16 16:35 UTC, luke-biel commented on tests/README.md
> +
* this doesn't belong here
* we don't allow configuring test environment, for this stage everything has to be within testcontainers (it may change later - but now it's redundant)

2020-12-16 16:35 UTC, luke-biel commented on tests/command_service/test_victoria_insertion.py
> +
Did you run autoformatter on this? This newline seems out of place

2020-12-16 16:35 UTC, luke-biel commented on tests/README.md
> +VictoriaMetrics instance must be started manually in order to execute tests.
Why is that? We don't want that.

2020-12-16 16:42 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
>          } = msg;
```let BorrowedInsertMessage {
            object_id,
            schema_id,
            data,
            ..
        } = msg;
``` instead

2020-12-16 16:43 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +    dbg!(&line_protocol);
delete

2020-12-16 16:45 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +    ts: Value,
Make it `u64` and whole function `get_object_timestamp` goes away

2020-12-17 08:43 UTC, Tesel commented on tests/common/kafka.py
> +        kafka_producer.close()
What ensures that?

2020-12-17 08:52 UTC, Tesel commented on command-service/src/output/victoria_metrics/mod.rs
> +    ts: Value,
So only u64 timestam format is accepted?

2020-12-17 13:00 UTC, Tesel commented on tests/command_service/test_victoria_insertion.py
> +
PEP8 allows for such behaviour, but removed that empty line

2020-12-17 13:30 UTC, luke-biel commented on tests/common/kafka.py
> +        kafka_producer.close()
GarbageCollector and destructor of KafkaProducer

2020-12-17 13:30 UTC, luke-biel commented on tests/command_service/test_victoria_insertion.py
> +
Sure, I don't mind it, but it seemed out of place at first glance

2020-12-17 13:36 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +    ts: Value,
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/ - to we go with LP spec, it should be i64, but within cdl we don't support negative timestamps

2020-12-17 14:15 UTC, Tesel commented on tests/common/kafka.py
> +        kafka_producer.close()
GarbageCollector call is not ensured without ContextManaging

2020-12-17 14:24 UTC, luke-biel commented on tests/common/kafka.py
> +        kafka_producer.close()
This resource resides solely in memory, it's not eg. compose deployed on system's docker instance. It will be freed eventually, and we don't need to add extra complexity to test programs, to manage that manually.

2020-12-17 15:19 UTC, Tesel commented on tests/common/kafka.py
> +        kafka_producer.close()
It reduces tests complexity, as resource gets freed manually prior to my changes.

2020-12-17 17:33 UTC, luke-biel commented on tests/common/kafka.py
> +        kafka_producer.close()
KafkaProducer wouldn't need to be freed manually. But ok, it's not that it matters much. We can introduce that. However we need to be consistent. Postgres and VM clients should follow same scheme then.

BTW You can reduce nesting by combining multiple with statements like so:
```python
with A() as a, B() as b, C() as c:
    doSomething(a,b,c)
```

2020-12-17 17:34 UTC, luke-biel commented
I think you've missed some files in this PR
```
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/lukbiel/acceptance-testing/CommonDataLayer/tests
collected 0 items / 3 errors

================================================================================================== ERRORS ==================================================================================================
_______________________________________________________________________ ERROR collecting command_service/test_postgres_insertion.py ________________________________________________________________________
ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/command_service/test_postgres_insertion.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
command_service/test_postgres_insertion.py:5: in <module>
    from tests.common import load_case, retry_retrieve
common/__init__.py:10: in <module>
    from tests.common.victoria_metrics import VictoriaMetrics
E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
_______________________________________________________________________ ERROR collecting command_service/test_victoria_insertion.py ________________________________________________________________________
ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/command_service/test_victoria_insertion.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
command_service/test_victoria_insertion.py:9: in <module>
    from tests.common import load_case, retry_retrieve
common/__init__.py:10: in <module>
    from tests.common.victoria_metrics import VictoriaMetrics
E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
_________________________________________________________________________ ERROR collecting db_shrinker_postgres/test_shrinking.py __________________________________________________________________________
ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/db_shrinker_postgres/test_shrinking.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
db_shrinker_postgres/test_shrinking.py:3: in <module>
    from tests.common import load_case
common/__init__.py:10: in <module>
    from tests.common.victoria_metrics import VictoriaMetrics
E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
========================================================================================= short test summary info ==========================================================================================
ERROR command_service/test_postgres_insertion.py
ERROR command_service/test_victoria_insertion.py
ERROR db_shrinker_postgres/test_shrinking.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================ 3 errors in 0.18s =============================================================================================
```

2020-12-18 09:18 UTC, Tesel commented on tests/common/kafka.py
> +        kafka_producer.close()
removed `kafka_producer_manager` and started using `contextlib.closing` and reduced nesting by proposed `with` statement.
also used closing for `postgres` db

2020-12-18 11:27 UTC, Kononnable commented on command-service/Cargo.toml
> +anyhow = "1.0"
```suggestion
anyhow      = "1.0"
```

2020-12-18 11:27 UTC, Kononnable commented on command-service/Cargo.toml
> +fnv         = "1.0.7"
```suggestion
fnv         = "1.0"
```

2020-12-18 11:27 UTC, Kononnable commented on command-service/src/output/victoria_metrics/mod.rs
> -use itertools::Itertools;
Looks like `itertools` is no longer used.

2020-12-18 11:27 UTC, Kononnable commented on requirements.txt
> +requests==2.22.0
```suggestion
requests~=2.22.0
```

2020-12-18 11:44 UTC, luke-biel requested changes

2020-12-18 11:44 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +                obj.ts.to_string()
`to_string` is done by format out of the box

2020-12-18 11:44 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +            Ok(format!("{}={}", key, value.to_string()))
Same, format already uses `trait Display`, potentially saving an allocation here

2020-12-18 11:44 UTC, luke-biel commented on tests/command_service/test_postgres_insertion.py
> +        print(entry)
Please, cleanup code when pushing it

2020-12-18 11:44 UTC, luke-biel commented on command-service/Cargo.toml
> +anyhow = "1.0"
Why was this whitespace change commited?

2020-12-18 11:48 UTC, luke-biel commented
As mentioned in issue, this requires also adjusting druid. If you have that in separate PR, let's merge it into this.

2020-12-18 12:04 UTC, Tesel commented on command-service/Cargo.toml
> +anyhow = "1.0"
overlooked, fixed

2020-12-18 12:35 UTC, Tesel commented on command-service/src/output/victoria_metrics/mod.rs
> +            Ok(format!("{}={}", key, value.to_string()))
fixed

2020-12-18 12:35 UTC, Tesel commented on command-service/src/output/victoria_metrics/mod.rs
> +                obj.ts.to_string()
fixed

2020-12-18 12:38 UTC, Tesel commented
> 
> 
> As mentioned in issue, this requires also adjusting druid. Do you plan on creating separate PR for that?

So fianlly Druid is being deployyed and supported? I've only heard to not care about it.

2020-12-18 12:39 UTC, Tesel commented on command-service/src/output/victoria_metrics/mod.rs
> -use itertools::Itertools;
Removed from cargo

2020-12-18 12:44 UTC, luke-biel commented
> > As mentioned in issue, this requires also adjusting druid. Do you plan on creating separate PR for that?
> 
> So finally Druid is being deployed and supported? I've only heard to not care about it.

Druid query wasn't working in the first place, druid command was. Features for TS must be the same.

2020-12-18 13:00 UTC, Tesel commented
> 
> 
> > > As mentioned in issue, this requires also adjusting druid. Do you plan on creating separate PR for that?
> > 
> > 
> > So finally Druid is being deployed and supported? I've only heard to not care about it.
> 
> Druid query wasn't working in the first place, druid command was. Features for TS must be the same.

Okay then, druid will be pushed with the next PR

2020-12-18 13:20 UTC, Tesel commented
> 
> 
> I think you've missed some files in this PR
> 
> ```
> =========================================================================================== test session starts ============================================================================================
> platform linux -- Python 3.9.1, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
> rootdir: /home/lukbiel/acceptance-testing/CommonDataLayer/tests
> collected 0 items / 3 errors
> 
> ================================================================================================== ERRORS ==================================================================================================
> _______________________________________________________________________ ERROR collecting command_service/test_postgres_insertion.py ________________________________________________________________________
> ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/command_service/test_postgres_insertion.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> command_service/test_postgres_insertion.py:5: in <module>
>     from tests.common import load_case, retry_retrieve
> common/__init__.py:10: in <module>
>     from tests.common.victoria_metrics import VictoriaMetrics
> E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
> _______________________________________________________________________ ERROR collecting command_service/test_victoria_insertion.py ________________________________________________________________________
> ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/command_service/test_victoria_insertion.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> command_service/test_victoria_insertion.py:9: in <module>
>     from tests.common import load_case, retry_retrieve
> common/__init__.py:10: in <module>
>     from tests.common.victoria_metrics import VictoriaMetrics
> E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
> _________________________________________________________________________ ERROR collecting db_shrinker_postgres/test_shrinking.py __________________________________________________________________________
> ImportError while importing test module '/home/lukbiel/acceptance-testing/CommonDataLayer/tests/db_shrinker_postgres/test_shrinking.py'.
> Hint: make sure your test modules/packages have valid Python names.
> Traceback:
> /usr/lib/python3.9/importlib/__init__.py:127: in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> db_shrinker_postgres/test_shrinking.py:3: in <module>
>     from tests.common import load_case
> common/__init__.py:10: in <module>
>     from tests.common.victoria_metrics import VictoriaMetrics
> E   ModuleNotFoundError: No module named 'tests.common.victoria_metrics'
> ========================================================================================= short test summary info ==========================================================================================
> ERROR command_service/test_postgres_insertion.py
> ERROR command_service/test_victoria_insertion.py
> ERROR db_shrinker_postgres/test_shrinking.py
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ============================================================================================ 3 errors in 0.18s =============================================================================================
> ```

added missing files

2020-12-21 14:49 UTC, Tesel commented
> 
> 
> > > > As mentioned in issue, this requires also adjusting druid. Do you plan on creating separate PR for that?
> > > 
> > > 
> > > So finally Druid is being deployed and supported? I've only heard to not care about it.
> > 
> > 
> > Druid query wasn't working in the first place, druid command was. Features for TS must be the same.
> 
> Okay then, druid will be pushed with the next PR

While waiting for accepts, I have also adjusted Druid

2020-12-21 15:24 UTC, esavier approved these changes
looks ok for me i guess

2020-12-21 15:43 UTC, frondeus approved these changes
LGTM

2020-12-22 07:01 UTC, luke-biel approved these changes

2020-12-22 07:01 UTC, merged