feat(chore): GraphQL server
epiphany-platform/CommonDataLayer pull request #109
Opened 2020-12-18 08:15 UTC by frondeus

2020-12-22 07:12 UTC, luke-biel commented on api/src/schema.rs
> +impl Into<i32> for SchemaType {
From<SchemaType> for i32
will implement into and from at the same time

2020-12-22 07:17 UTC, luke-biel commented on examples/deploy/docker-compose.yml
> +      #EXPORT_DIR: "/var/data/exported"
I don't see it necessary to include it within compose

2020-12-22 07:17 UTC, luke-biel commented on api/src/schema.rs
> +}
Isn't there any way to use SchemaType from `rpc` crate? I don't like this duplication at all.

2020-12-22 08:19 UTC, frondeus commented on api/src/schema.rs
> +impl Into<i32> for SchemaType {
Ah, this way around.... sure!

2020-12-22 08:25 UTC, frondeus commented on api/src/schema.rs
> +}
It would be a violation of orphan rule, because I cannot implement graphql trait for `SchemaType` from `rpc`. I know it's not the best solution but hey, at least this enum has only 4 lines of code.

2020-12-22 08:31 UTC, luke-biel commented on api/src/schema.rs
> +}
I was thinking maybe pack it in newtype, but dunno

2020-12-22 11:38 UTC, Kononnable commented on api/src/queries.rs
> +        drop(conn);
Why separate drop?

2020-12-22 11:38 UTC, Kononnable commented on api/src/queries.rs
> +        for version in versions {
This probably should be executed in parallel. However it's probably not going to be a bottleneck soon.

2020-12-22 11:38 UTC, Kononnable commented on api/src/queries.rs
> +    //TODO: Remove Option<> - return error on missing id.
Left it for future changes or forgot about that and was planned to be done before PR gets merged?

2020-12-22 11:38 UTC, Kononnable commented on api/src/queries.rs
> +// TODO: Add GRPC route to schema_registry which takes schema for uuid.
Same as above

2020-12-22 11:38 UTC, Kononnable commented on api/src/schema.rs
> +}
Both enum and traits impl can be done from same place - those traits(unless I'm missing something) are general, not related directly to api crate business logic. It might be a good idea to put schema type into utils crate(in future we can thing of `common` or similar name).

2020-12-22 11:38 UTC, Kononnable commented on api/src/schema.rs
> +}
Specify value with enum. Current form is error prone.

Something similar to https://stackoverflow.com/questions/31358826/how-do-i-convert-an-enum-reference-to-a-number

2020-12-22 11:38 UTC, Kononnable commented on api/src/context.rs
> +    query_router_conn: Mutex<Option<QueryServiceClient<Channel>>>,
I think we both those fields are not necessary at this point. We're not reusing connection in other places.

We probably will need to do it at some point, but it won't be that simple to implement. Connection pooling implementation needs to allow service scaling(simple connection reuse without connection invalidation doesn't do that), probably some circuit breaker feature(depends on the way we go). As an additional disadvantage - using mutex this way limits ability to process multiple requests at the same time.

2020-12-22 11:43 UTC, frondeus commented on api/src/schema.rs
> +}
But the point is, this enum needs to have implemented GraphQLEnum trait via `derive`. Do you wanna add graphql dependency to the common utils crate?

2020-12-22 11:46 UTC, frondeus commented on api/Cargo.toml
> +#async-trait             = "0.1"
One of the problems with GraphQL is N+1 problems. We are making N+1 requests to schema repository instead of 2.
Data loader might solve this issue. Please keep in mind that this PR is MVP and the work is still in progress. I commented this dependency for now because it's not used **yet** but I am going to use it in next PR.

2020-12-22 11:46 UTC, frondeus commented on api/README.md
> +This crate is under heavy work-in-progress. It may change a lot with breaking changes. Use wisely.
We can remove this roadmap as soon as I finish v0.2

2020-12-22 11:48 UTC, frondeus commented on api/README.md
> +You can deploy web api on local computer via `docker-compose`
Yes, for developer builds. That's why I wrote "on local computer". I wrote this README in case you guys want to play with this feature to decide if this is the correct way and if you like it.

2020-12-22 11:48 UTC, frondeus commented on api/README.md
> +You can deploy web api on local computer via `docker-compose`
I'd love to do helm chart in the future, but right now I see more important things to do.

2020-12-22 11:53 UTC, frondeus commented on api/src/context.rs
> +    query_router_conn: Mutex<Option<QueryServiceClient<Channel>>>,
I guess @USSAMOH2  can answer these questions better than especially that he wrote it, but:
> We are not reusing connections in other places.
This is not an excuse for not introducing it here.

Anyway, I agree about mutex and probably we don't need this pooling right now, here.
We need to remember this tool is rather a for management than for daily-use. I do not expect 10k requests per second, not even 100rps. So we don't have to worry that much about performance. As soon as it's not sluggish-like-jira.

I'd be happy if we could do performance gains later and do incremental development here. It doesn't have to be perfect from the beginning.

2020-12-22 11:54 UTC, frondeus commented on api/src/queries.rs
> +    //TODO: Remove Option<> - return error on missing id.
This is for future changes. In order to do it I have to implement new RPC route in schema registry.

2020-12-22 11:56 UTC, frondeus commented on api/src/queries.rs
> +// TODO: Add GRPC route to schema_registry which takes schema for uuid.
That's the change I was referring above ;-) We should ask about one schema instead of pooling all of them and filtering. It is on my TODO list, I'm doing it right now, but it's not blocking us, that's why I prepared PR.
The API is usable without this RPC call, just slower. I am going to fix it but meanwhile, you can get familiarized with graphql and the gains it brings.

2020-12-22 12:00 UTC, frondeus commented on api/src/schema.rs
> +}
Sure I  can  use it... but how exactly it is error prone?

2020-12-22 12:02 UTC, frondeus commented on api/src/context.rs
> +        self.conn.as_mut().unwrap()
I guess the intention is here that `Option` is always `Some`.
In theory we could replace `Option` with `MaybeUninit`, because that's exactly what we are doing here.

2020-12-22 12:31 UTC, Kononnable commented on api/src/schema.rs
> +}
Ok, didn't see that one - I guess if there is a comment after derive I just ignore that :smile: 

So the only options I see here is to leave it as is or create enum with single value(imported enum). Alias types won't work(can't derive on them).

2020-12-22 12:38 UTC, Kononnable commented on api/src/schema.rs
> +}
Those codes are used twice - you can e.g. mistype value in one place and make `SchemaType::Timeseries => 0,` from `SchemaType::Timeseries => 1,`. It's easy to do especially when adding new value means copy pasting last line. Such bugs are hard to find(unless clippy suggest something to make code simpler).

2020-12-22 12:53 UTC, frondeus commented on api/src/schema.rs
> +}
But your suggestion from link does not solve `TryFrom` case which means this "magic numbers" (0, 1) would be still in two places. Am I wrong?

2020-12-22 12:54 UTC, frondeus commented on api/src/queries.rs
> +        drop(conn);
I agree that can be avoided. Right now there is a drop, because conn has a mutex lock, and in following line I'm retrieving new mutex lock causing a deadlock. I'm going to change the following line and then remove the drop by reusing conn.

2020-12-23 08:44 UTC, frondeus commented on api/src/schema.rs
> +}
IMHO I should leave it. Enum with a single value wouldn't solve a thing cause when you derive, all fields/variants have to implement trait anyway.

2020-12-23 11:04 UTC, Kononnable submitted a review, later dismissed

2020-12-23 11:15 UTC, luke-biel commented on api/src/schema.rs
> +}
In theory you can cast from `u8` to `enum` somehow I guess.

There's `num::Frem/ToPrimitive` which derives enum automatically. We can try that.

2020-12-23 12:16 UTC, frondeus commented on api/src/schema.rs
> +}
Not bad especially that we are implicitly using `num-derive` in `prost`

2020-12-23 12:52 UTC, Kononnable approved these changes

2020-12-23 15:12 UTC, Kononnable submitted a review, later dismissed

2020-12-23 18:11 UTC, luke-biel requested changes

2020-12-23 18:11 UTC, luke-biel commented on deployment/compose/docker-compose.cdl.yml
> +
You already have VM entry in `docker-compose.yml`

2020-12-30 11:27 UTC, luke-biel commented on api/README.md
> +For more see [documentation](deployment/compose/README.md).
Path has changed

2020-12-30 15:25 UTC, luke-biel commented on deployment/compose/initial-schema.json
> +{
I now noticed that this file is in compose root. Can you move it to `docker-volume/schema-registry/init'?

2020-12-31 20:21 UTC, luke-biel commented on api/src/main.rs
> +    let graphql_filter = juniper_warp::make_graphql_filter(crate::queries::schema(), state.boxed());
We will need cors to query this from some frontend. I guess '*' will suffice now.

```
let cors = warp::cors()
    .allow_any_origin();

let state = warp::any().map({
    let config = config.clone();
    move || Context::new(config.clone())
});
let graphql_filter = juniper_warp::make_graphql_filter(crate::queries::schema(), state.boxed()).with(cors);
```

2020-12-31 23:53 UTC, luke-biel commented
I've added 2 different schema definitions via
```
mutation AddSchemaDefMutation($id: Uuid!) {
  addSchemaDefinition(schemaId:$id, newVersion:{
    version: "1.1.0",
    definition: "{\"test\": false, \"values\": true}"
  }) {
    definition
  }
}
```
(definition for 1st was `{}`)
and then queried registry via
```
query SchemaDefinitionQuery($id: Uuid!) {
  schema(id:$id) {
    id,
    definitions {
      version,
      definition,
    }
  }
}
```

result
```
{
  "data": {
    "schema": {
      "id": "2cfad3c7-411a-11eb-8000-000000000000",
      "definitions": [
        {
          "version": "1.1.0",
          "definition": "{\"test\":false,\"values\":true}"
        },
        {
          "version": "1.1.0",
          "definition": "{\"test\":false,\"values\":true}"
        },
        {
          "version": "1.1.0",
          "definition": "{\"test\":false,\"values\":true}"
        }
      ]
    }
  }
}
```

I expected there to be versions 1.0.0 and 1.0.1. Something's not okay

2021-01-04 09:03 UTC, frondeus commented on deployment/compose/initial-schema.json
> +{
The point is that we don't have to use docker-volume for schema, so why using `docker-volume/..` path?

2021-01-04 09:45 UTC, frondeus commented
It is okay.
You queried for `version` and schema registry uses semver. When retrieving data it returns you latest compatible definition for given version.
You can check it by adding:
```
query SchemaDefinitionQuery($id: Uuid!) {
  schema(id:$id) {
    id,
    definitions {
      version,
      definition,
      queriedVersion // <- this one will tell you `1.0.1` and `1.0.0`
    }
  }
}
```
If this isn't the desired behavior then we need to change the schema registry, but IMO this is job for different PR.

2021-01-04 10:37 UTC, luke-biel commented on deployment/compose/initial-schema.json
> +{
This path can be named whatever, the point is to keep all `init` in one place, to not make mess in root of `compose/`. We can create new dir named `setup` or something.

2021-01-04 10:58 UTC, luke-biel commented
> It is okay.
> You queried for `version` and schema registry uses semver. When retrieving data it returns you latest compatible definition for given version.
> You can check it by adding:
> 
> ```
> query SchemaDefinitionQuery($id: Uuid!) {
>   schema(id:$id) {
>     id,
>     definitions {
>       version,
>       definition,
>       queriedVersion // <- this one will tell you `1.0.1` and `1.0.0`
>     }
>   }
> }
> ```
> 
> If this isn't the desired behavior then we need to change the schema registry, but IMO this is job for different PR.

I believe this is strange behaviour. I expect it to return all versions, not one version 3 times.

2021-01-04 15:33 UTC, frondeus commented
Ah good old `=` constraint can do miracle :)

2021-01-05 12:51 UTC, luke-biel submitted a review, later dismissed

2021-01-05 12:51 UTC, luke-biel commented on api/Cargo.toml
> +juniper_warp            = "0.6"
It feels wrong that less indented deps are behind this one

2021-01-05 13:42 UTC, Kononnable reviewed
No helmfile changes, otherwise LGTM

2021-01-05 13:43 UTC, luke-biel commented on api/Cargo.toml
>  uuid        = { version = "0.8", features = ["v4", "serde"] }
```suggestion
# Crates.io
env_logger  = "0.8"
juniper     = { version = "0.15", features = ["uuid"] }
num-derive  = "0.3.3"
num-traits  = "0.2.14"
log         = "0.4"
structopt   = "0.3"
thiserror   = "1.0"
tokio       = { version = "0.2", default-features = false, features = ["sync", "rt-threaded", "macros"] }
uuid        = { version = "0.8", features = ["v4", "serde"] }
warp        = "0.2"
juniper_warp            = "0.6"
```

2021-01-05 15:38 UTC, luke-biel approved these changes

2021-01-05 15:50 UTC, USSAMOH2 approved these changes

2021-01-05 16:04 UTC, merged