feat: add initial frontend version
epiphany-platform/CommonDataLayer pull request #138
Opened 2021-01-04 12:46 UTC by luke-biel

2021-01-04 14:38 UTC, USSAMOH2 commented
I am not a fan of the current deployment strategy. A standard frontend website is served out of a folder and requires no long-running process to provide frontend content unless you are using templates, and we aren't _actually_ using templates here. We should move this to deploy without needing the server, and only have one crate in this PR.

2021-01-04 14:45 UTC, USSAMOH2 commented
When designing a website, it's important to have a consistent look: we need a CSS framework. I tend to prefer lighter-weight ones to make design decisions simpler and load times shorter. I like [Spectre](https://picturepan2.github.io/spectre/index.html) from this list of [CSS Frameworks](https://www.mockplus.com/blog/post/css-framework).

2021-01-04 16:35 UTC, frondeus commented
> When designing a website, it's important to have a consistent look: we need a CSS framework. I tend to prefer lighter-weight ones to make design decisions simpler and load times shorter. I like [Mustard](https://kylelogue.github.io/mustard-ui/index.html) from this list of [CSS Frameworks](https://www.mockplus.com/blog/post/css-framework).

While yes, it is nice to have consistent look - lets focus on UX and usability first. A shell but nice website is still just a shell.

2021-01-05 10:26 UTC, luke-biel commented
> I am not a fan of the current deployment strategy. A standard frontend website is served out of a folder and requires no long-running process to provide frontend content unless you are using templates, and we aren't _actually_ using templates here. We should move this to deploy without needing the server, and only have one crate in this PR.

I'm thinking about this. It's leftover from previous approach, where I had no graphql service. I'm gonna look into this closer to finishing this version. If after all is implemented I'm still not using server in any shape or for I'm gonna delete it.



> When designing a website, it's important to have a consistent look: we need a CSS framework. I tend to prefer lighter-weight ones to make design decisions simpler and load times shorter. I like [Mustard](https://kylelogue.github.io/mustard-ui/index.html) from this list of [CSS Frameworks](https://www.mockplus.com/blog/post/css-framework).

Right now we have CSS framework. It's LESS, and it's compiled in runtime (there's a script in layout.hbs for that). When I'm done with functionality, I will look into LESS compilation, or review other options.

2021-01-05 11:14 UTC, frondeus commented
> If after all is implemented I'm still not using server in any shape or for I'm gonna delete it.
I'd suggest having at least some kind of docker image with Nginx so it would be easily deployed on a local machine.

2021-01-14 10:43 UTC, luke-biel commented
@dependabot rebase

2021-01-15 14:22 UTC, frondeus requested changes

2021-01-15 14:22 UTC, frondeus commented on frontend/src/components/schema_registry/mod.rs
> +    page: Page, // TODO: Make it a stack
What about this TODO? Is this for the future or just missing?

2021-01-15 14:22 UTC, frondeus commented on frontend/src/lib.rs
> +    pub static ref GRAPHQL_URL: Url = Url::parse("http://localhost:50106/graphql").unwrap();
Thats worrysome, it shouldn't be hardcoded

2021-01-15 14:25 UTC, frondeus commented
While I appreciate your work, it's an amazing piece of tech I wonder if WASM/Yew is really that nice, while you get nice static typing, it's all just... so verbose and hard to look at.

Believe me, I'm not a fan of js, but `React` with `hooks` is surprisingly pleasant to type and extend.

Of course, I don't require a change from Yew to another framework, plus Sam is working on his implementation, these are just my thoughts on that matter.

2021-01-15 16:46 UTC, luke-biel commented on frontend/src/lib.rs
> +    pub static ref GRAPHQL_URL: Url = Url::parse("http://localhost:50106/graphql").unwrap();
Well, only way to make it configurable right now is to create a separate page, with config, that saves this to a cookie. It's a lot of work, I skipped it for now since it's not crucial for our (as in CDL team) experience with frontend right now. But yeah, we have to add it as the very next thing. I would just prefer to do it separately, so others may use and add features to frontend in parallel.

2021-01-15 16:49 UTC, luke-biel commented
> While I appreciate your work, it's an amazing piece of tech I wonder if WASM/Yew is really that nice, while you get nice static typing, it's all just... so verbose and hard to look at.
> 
> Believe me, I'm not a fan of js, but `React` with `hooks` is surprisingly pleasant to type and extend.
> 
> Of course, I don't require a change from Yew to another framework, plus Sam is working on his implementation, these are just my thoughts on that matter.

There's `yew_form` and `yew_router`, which remove much of this verbosity. Yew router requires an http_server that can handle SPA and I couldn't find any that would point `index/foo/bar/` back to `index` (i guess nginx can do this, but I can't use it locally) As for forms, i just didn't include it.

2021-01-15 16:50 UTC, luke-biel commented on frontend/src/components/schema_registry/mod.rs
> +    page: Page, // TODO: Make it a stack
For the future. I may either add a Vec here or use yew_router

2021-01-15 16:51 UTC, frondeus commented on frontend/src/lib.rs
> +    pub static ref GRAPHQL_URL: Url = Url::parse("http://localhost:50106/graphql").unwrap();
What about using relative url like `/graphql` and working with reverse proxy like nginx?

2021-01-18 11:22 UTC, Kononnable requested changes
Blocking till we decide which approach should we use(so it won't be merged by mistake, without proper code review).

For me it's very verbose and I don't like keeping html hidden inside other files just feels bad. Like keeping html content deep inside js files.

2021-01-27 09:27 UTC, luke-biel commented
Closing in favor of TS

2021-01-27 09:27 UTC, closed without merging