Move crates to separate folders
epiphany-platform/CommonDataLayer pull request #141
Opened 2021-01-07 16:14 UTC by frondeus

2021-01-07 16:29 UTC, USSAMOH2 requested changes

2021-01-07 16:29 UTC, USSAMOH2 commented on Cargo.toml
> +    "crates/*"
```suggestion
    "crates/api",
    "crates/blob-store",
    "crates/benchmarking",
    "crates/cdl-cli",
    "crates/command-service",
    "crates/data-router",
    "crates/document-storage",
    "crates/db-shrinker-postgres",
    "crates/leader-elector",
    "crates/query-router",
    "crates/query-service",
    "crates/query-service-ts",
    "crates/rpc",
    "crates/schema-registry",
```

2021-01-07 16:30 UTC, frondeus commented on Cargo.toml
> +    "crates/*"
Okay, but why? Do we want to enable/disable crates by explicitly exclude them?

2021-01-07 16:33 UTC, frondeus commented on Cargo.toml
> +    "crates/*"
Because if you want to easily check what crates are included in workspace I'd first go to `crates/` and do `ls` than check `Cargo.toml`

2021-01-08 10:15 UTC, luke-biel commented on Cargo.toml
> +    "crates/*"
Shouldn't we just move all cargo related stuff to `crates/` folder?

2021-01-08 10:56 UTC, frondeus commented on Cargo.toml
> +    "crates/*"
I think workspace Cargo.toml/lock should be in the root folder.
Otherwise you won't be able to do `cargo build` from `docs/` folder etc.

2021-01-08 10:59 UTC, luke-biel commented on Cargo.toml
> +    "crates/*"
Should you be able? And there's always `--manifest-path`

2021-01-08 11:47 UTC, Kononnable approved these changes
Remember to change PR title/squash commit message on merge

2021-01-08 14:49 UTC, USSAMOH2 approved these changes

2021-01-08 14:51 UTC, merged