feat: casuality defined by user
epiphany-platform/CommonDataLayer pull request #152
Opened 2021-01-11 10:31 UTC by Kononnable

2021-01-15 12:26 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let message_stream = select_all(streams.into_iter().map(Box::pin));
```
message_streams = [`fut1`]

next() => async handle_message(fut1.msg1)
next() => async handle_message(fut1.msg2)
// random delay on tokio task with fut1.msg1
fut1.msg2.ack()
fut1.msg1.ack()
```
What keeps the order here? I see we read messages from partitions in order, but even when tokio runs on single thread, we have no guarantees when tasks will finish, and in which order they finish.
Unless, of course, same future cannot be read from before acking previous message.

2021-01-15 12:26 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
According to yesterday, this has to be kafka

2021-01-15 12:51 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +            self.task_limiter
Task limiter should be part of task_queue functionality. Here we are limiting how many tasks can be queued, not processed.
We may consider changing this `select_all` to `for loop` with one tokio task per stream - then only we are sure task-limiter from one queue won't block other queues.

2021-01-15 12:51 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +            .map(async move |x| task_queue.run_task(x.to_string()).await);
`x` is ugly name

2021-01-15 12:51 UTC, luke-biel commented on crates/command-service/src/args.rs
> +                    .filter(|x| !x.is_empty())
```suggestion
                    .filter(|queue_name| !queue_name.is_empty())
```

2021-01-15 12:51 UTC, luke-biel commented on crates/command-service/src/args.rs
> +                    .filter(|x| !x.is_empty())
```suggestion
                    .filter(|queue_name| !queue_name.is_empty())
```

2021-01-15 12:51 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +            .map(async move |x| task_queue.run_task(x.to_string()).await);
Also, this does'n run any task, this locks a mutex. `acquire_permit()`, `guard()`, `task_permit()`, `acquire_task_guard()`, `acquire_guard_for_key()`?

2021-01-15 12:51 UTC, luke-biel commented on crates/data-router/src/main.rs
> +            .map(|x| x.to_string().replace("-", "."))
```suggestion
            .map(|tag| tag.to_string().replace("-", "."))
```

2021-01-15 12:51 UTC, luke-biel commented on crates/data-router/src/main.rs
> +            .map(|x| x.to_string().replace("-", "."))
```suggestion
            .map(|tag| tag.to_string().replace("-", "."))
```

2021-01-15 12:51 UTC, luke-biel commented on crates/data-router/src/main.rs
> +            .unwrap_or_else(|| "unordered".to_string());
In CS you are using this to limit parallel processing. Shouldn't this be left out empty for unordered messages?

2021-01-15 14:08 UTC, frondeus commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
This has to be dynamic, user should choose via ENV variable/cmd attribute

2021-01-15 14:13 UTC, frondeus requested changes

2021-01-15 14:13 UTC, frondeus commented on crates/command-service/src/args.rs
> +        MessageQueue,
Instead of replacing Kafka, we need to add RabbitMQ as a another option

2021-01-15 14:13 UTC, frondeus commented on crates/data-router/src/main.rs
> +        CommonPublisher::new_rabbit(&config.rabbit_connection_string)
Again producer should be dynamic based on ENV variable

2021-01-15 14:13 UTC, frondeus commented on crates/data-router/src/main.rs
> +        CommonPublisher::new_rabbit(&config.rabbit_connection_string)
It could be a nice base for `GRPC` support in `Data Router - Command Service` edge

2021-01-18 08:47 UTC, Kononnable commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
Agree, but I think it's better to have those unrelated changes in separate PR.

2021-01-18 08:48 UTC, Kononnable commented on crates/command-service/src/args.rs
> +        MessageQueue,
Agree, but I think it's better to have those unrelated changes in separate PR.

2021-01-18 08:48 UTC, Kononnable commented on crates/data-router/src/main.rs
> +        CommonPublisher::new_rabbit(&config.rabbit_connection_string)
Agree, but I think it's better to have those unrelated changes in separate PR.

2021-01-18 09:14 UTC, Kononnable commented on crates/command-service/src/input/service/mesage_queue.rs
> +            self.task_limiter
I don't think task limiter should be merged with task queue. They cover different functionalities and can by combined easily(reusability).

>Here we are limiting how many tasks can be queued, not processed.

Define being processed - as I remember task limiter was introduced to avoid CS fetching to much data from queue and consuming resources(also slowing down in the process). If we check if messages have same order group id before task limiter we would go back to those problems.

>We may consider changing this select_all to for loop with one tokio task per stream - then only we are sure task-limiter from one queue won't block other queues.

I'm not sure if that's really a problem - If someone sees such problems often they should really look into how they're splitting their workflow - define different exchange-queue binding on rabbitmq or change the way order group id is generated in their system. Task limiter will slow down other queues only if almost all of its tasks have single order group id, so increasing `task_limit` is also a good way to migrate that. Proposed changes would probably increase this too, don't see a point in defining task limit per queue if it's just to limit resource ussage.

2021-01-18 09:20 UTC, Kononnable commented on crates/command-service/src/input/service/mesage_queue.rs
> +            .map(async move |x| task_queue.run_task(x.to_string()).await);
this took me a while to figure out. This is just about renaming task_queue method name, right?

2021-01-18 09:35 UTC, Kononnable commented on crates/data-router/src/main.rs
> +            .unwrap_or_else(|| "unordered".to_string());
I think empty key may be disallowed in some message queues(or tools used for them). 
Should be extracted to some const anyway.

2021-01-18 10:00 UTC, frondeus approved these changes

2021-01-18 11:50 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +            .map(async move |x| task_queue.run_task(x.to_string()).await);
Yeah, sorry if that was ambiguous

2021-01-18 11:52 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
Consumers have to be Kafka to function on DE environment. That's what Jakub said. Am I missing something?

2021-01-18 12:40 UTC, Kononnable commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
Deployment for specific client isn't related to ordering. Ordering should work for both rabbitmq and kafka. Currently we're supporting only one message queue at the time(changing MQ requires code changes). What I meant is I would prefer to this being merged as is and create separate PR introducing ability to change MQ based on passed params.

We can go back to kafka in this PR but I don't see a point of it - it have to be changed by other PR either way to support multiple MQ.

2021-01-18 12:50 UTC, luke-biel commented on crates/command-service/src/input/service/mesage_queue.rs
> +        let ordered_options = Some(BasicConsumeOptions {
We need to deploy ordering supporting Kafka by the end of the month. As I see this PR doesn't provide this feature. I'm okay in doing this in separate PR but we are running out of time.

2021-01-19 10:27 UTC, luke-biel approved these changes

2021-01-19 10:39 UTC, luke-biel submitted a review, later dismissed

2021-01-19 10:43 UTC, Kononnable commented
Temporary disabled component tests - this PR should be merged just before merging PR(WIP) with support for both message queues which will enable them again.

2021-01-19 11:29 UTC, luke-biel approved these changes

2021-01-27 10:20 UTC, luke-biel approved these changes

2021-01-27 10:22 UTC, merged