feat(api): GraphQL subscriptions
epiphany-platform/CommonDataLayer pull request #166
Opened 2021-01-14 14:08 UTC by frondeus

2021-01-14 19:06 UTC, esavier submitted a review, later dismissed

2021-01-15 16:43 UTC, USSAMOH2 commented on crates/api/src/queries.rs
> +            .map_err(anyhow::Error::from)
Is there a way to do this more concisely?

2021-01-15 16:55 UTC, frondeus commented on crates/api/src/queries.rs
> +            .map_err(anyhow::Error::from)
I guess there is no point on having custom `Error` in Context if we are simply doing:
`anyhow::Error -> ContextError -> anyhow::Error`.
I could just return anyhow::Error in all context methods.

2021-01-15 16:57 UTC, frondeus commented on crates/api/src/queries.rs
> +            .map_err(anyhow::Error::from)
Or remove `anyhow::Error` and do proper library-like error management.

2021-01-18 10:09 UTC, Kononnable requested changes
I think using kafka directly is a blocker - what is the point of abstraction if we're not going to use it and won't be able to have same code for handling multiple message queues.

2021-01-18 10:09 UTC, Kononnable commented on crates/api/src/events.rs
> +            log::warn!("Kafka stream has ended");
What does it mean in terms of business logic(when does it happen)? Or if it should not have happen maybe we should restart the service or do something else(e.g. to avoid leaking memory)?

2021-01-18 10:09 UTC, Kononnable commented on crates/api/src/main.rs
> +        move || context.clone()
Looks weird - two clones on the same value, can this be simplified in some way?

2021-01-18 10:09 UTC, Kononnable commented on crates/api/src/main.rs
> +        .map(|reply| warp::reply::with_header(reply, "Sec-WebSocket-Protocol", "graphql-ws"));
This header should probably be somewhere in consts(of a dependency).

2021-01-18 10:09 UTC, Kononnable commented on crates/api/src/queries.rs
> +            .map_err(anyhow::Error::from)
If this is going directly to user I think it's fine. If it's going to our reporting service(kafka topic at this point) it would have to be put in some structure anyway(same as errors in data router - we mentioned it on Thursday I think).

2021-01-18 10:09 UTC, Kononnable commented on crates/api/src/events.rs
> +    pub payload: Option<String>,
Is it really optional?

2021-01-18 11:25 UTC, frondeus commented on crates/api/src/context.rs
> +    //                               Topic, Event stream
Fixed in metrics PR, can it wait?

2021-01-18 11:29 UTC, frondeus commented on crates/api/src/events.rs
> +            log::warn!("Kafka stream has ended");
(After I fixed few things in metrics PR) - it means that for example connection to kafka broker has been closed.
I'm not sure what to do then to be honest. Restart could be nice or reconnection.
But this is in separated task/thread therefore probably we need some way to change `HashMap` from `Context`. It is possible, after all I used `Arc<Mutex>`, but it means `Subscriber` would be depending on `Context`.

2021-01-18 11:30 UTC, frondeus commented on crates/api/src/events.rs
> +    pub payload: Option<String>,
It is in kafka. You can send messages without payload.

2021-01-18 11:31 UTC, frondeus commented on crates/api/src/main.rs
> +        move || context.clone()
I tried, but unfortunately `||` is `FnMut` I think.

2021-01-18 11:32 UTC, frondeus commented on crates/api/src/events.rs
> +        let consumer: StreamConsumer<DefaultConsumerContext> = ClientConfig::new()
Do you mean from `utils` crate?

2021-01-18 11:33 UTC, frondeus commented on crates/api/Cargo.toml
> +serde_json  = "1.0.61"
I don't see alphabetic order in other crates, so why here? Unless it supposed to be alphabetic but no-one cares?

2021-01-18 12:14 UTC, frondeus commented on crates/api/src/events.rs
> +            log::warn!("Kafka stream has ended");
Fixed with `FnOnce` callback called `on_close`

2021-01-18 12:41 UTC, Kononnable commented on crates/api/src/events.rs
> +        let consumer: StreamConsumer<DefaultConsumerContext> = ClientConfig::new()
Yes

2021-01-18 13:00 UTC, frondeus commented on crates/api/src/events.rs
> +        let consumer: StreamConsumer<DefaultConsumerContext> = ClientConfig::new()
Right now it's not possible. I will create an issue so we can touch this problem with RabbitMQ implementation.

2021-01-18 16:12 UTC, Kononnable approved these changes
We probably should add an issue about leak which is actually dangerous here.
And another one about helm charts which is getting out of date(I think api isn't event there)

2021-01-18 16:12 UTC, Kononnable commented on crates/api/src/events.rs
> +        let consumer = Box::leak(Box::new(consumer));
```suggestion
        let consumer = consumer.leak();
```
Easier to trace(remove leaks once it's possible).

2021-01-19 10:35 UTC, luke-biel requested changes

2021-01-19 10:35 UTC, luke-biel commented on crates/api/src/events.rs
> +        let consumer = Box::leak(Box::new(consumer));
I say more, we can't leak here, every new subscription will allocate new Consumer that will live forever

2021-01-19 10:35 UTC, luke-biel commented on crates/api/src/context.rs
> +type Topic = String;
This is misleading, either force use of newtype via tuple struct or use String everywhere.

2021-01-19 10:41 UTC, frondeus commented on crates/api/src/events.rs
> +        let consumer = Box::leak(Box::new(consumer));
![image](https://user-images.githubusercontent.com/1165825/105023199-f2a65980-5a4a-11eb-9616-875190f61502.png)
You dont have to worry about `leak` if there is no `leak` ;-)
`Subscriber` architecture uses `broadcast` which allowed me to remove the leak and have a normal local variable.

2021-01-19 10:43 UTC, frondeus commented
>I say more, we can't leak here, every new subscription will allocate new Consumer that will live forever

It was true only for two scenarios:
* You ask for new topic
* You lost connection and have to reconnect.
In our *notification* example it means there is usually only one leaked `Consumer` because we are **reusing** consumer between websocket clients.

And now this topic is obsolete - I just removed leak.

2021-01-19 10:45 UTC, frondeus commented on crates/api/src/context.rs
> +type Topic = String;
I don't think `String` is an option. Then I need to tell via comment what `String` represents.
The whole
```
type Topic =  String;
```
acts as a documentation for whoever is reading code, what is the key of our hashmap.

2021-01-19 10:46 UTC, frondeus commented on crates/api/src/context.rs
> +type Topic = String;
Especially that this type is not public and no method depends on it.

2021-01-19 11:03 UTC, luke-biel commented on crates/api/src/context.rs
> +type Topic = String;
The issue here is that we don't name our other strings, nor document them. It's usually just parameter name, and if it's named well (eg. `topic`) it does same job, appears in same place, it enforced by compiler in same way.
We'd need to do same for other types for this to not be odd and out of place. But then I'd go with using newtype wherever possible.

2021-01-19 11:05 UTC, luke-biel commented on crates/api/src/context.rs
> +type Topic = String;
In line 38 you have `topic: &str`.

2021-01-19 11:08 UTC, frondeus commented on crates/api/src/context.rs
> +type Topic = String;
The fact that we aren't doing it for other strings is not a strong argument. We could improve our codebase one module at a time and it still is an improvement.

But whatever, I'm not going to dispute over silly `type Topic`, you win.

2021-01-19 11:26 UTC, luke-biel approved these changes

2021-01-19 11:27 UTC, merged