feat(api): Simple metrics retrieval
epiphany-platform/CommonDataLayer pull request #171
Opened 2021-01-15 16:40 UTC by frondeus

2021-01-15 16:45 UTC, frondeus commented on crates/api/src/kafka_events.rs
> +                tokio::pin!(stream);
pin + while let could be in theory moved to common structure `Subscriber`

2021-01-15 17:06 UTC, USSAMOH2 requested changes

2021-01-15 17:06 UTC, USSAMOH2 commented on crates/api/src/config.rs
> +    #[structopt(long = "metrics-interval-sec", env = "METRICS_INTERVAL_SEC")]
you don't have to specify the actual long/env names, you can just put `#[structopt(long, env)]` and it will use the appropriate casing.

2021-01-15 17:06 UTC, USSAMOH2 commented on crates/api/src/metrics.rs
> +                    let _ = sink.send(item);
You can also do
```suggestion
                    sink.send(item).ok();
```

2021-01-15 17:06 UTC, USSAMOH2 commented on crates/api/src/context.rs
> +impl Context {
Why have 2 impl blocks?

2021-01-18 08:11 UTC, frondeus commented on crates/api/src/context.rs
> +impl Context {
I often do 2 impls to visually separate `pub fn` from private `fn`

2021-01-18 10:26 UTC, Kononnable requested changes
Please add a note in PR description if your PR is based on another PR - so it doesn't get merged to soon. And doi some cleanup before marking PR as ready to review...

2021-01-18 10:26 UTC, Kononnable commented on crates/api/src/context.rs
> +                    MetricsSource::PostgresCommand => &self.config.postgres_command_metrics,
Repositories can be added add-hoc and even create by the user, so I'm not sure if we can use enum here.

2021-01-18 10:26 UTC, Kononnable commented on crates/api/src/subscriber.rs
> +{
Clean it up

2021-01-18 10:26 UTC, Kononnable commented on crates/api/src/subscriber.rs
> +    T: Send + Sync + Clone + Unpin + Send + Sync + 'static,
as above

2021-01-18 10:26 UTC, Kononnable commented on crates/api/src/subscriber.rs
> +        let (tx, rx) = broadcast::channel(32);
magic number

2021-01-18 10:26 UTC, Kononnable commented on crates/api/src/metrics.rs
> +            let source = futures::stream::unfold(source, |s| async move { Some((s.clone(), s)) });
Definitely looks to complicated.

2021-01-18 10:42 UTC, frondeus commented on crates/api/src/metrics.rs
> +            let source = futures::stream::unfold(source, |s| async move { Some((s.clone(), s)) });
If you find anything less scary - be my guest, but unfortunately, that's the only way I know to pass owned string to stream.

2021-01-18 10:44 UTC, frondeus commented
> Please add a note in PR description if your PR is based on another PR - so it doesn't get merged to soon. And do some cleanup before marking PR as ready to review...

You imply that I didn't do a cleanup and that's not true.
I missed only the `Send + Sync` repetition.

2021-01-18 10:48 UTC, frondeus commented on crates/api/src/context.rs
> +                    MetricsSource::PostgresCommand => &self.config.postgres_command_metrics,
Okay, but then we need a clever way to pass metrics URL via env variable. I could parse and split by ",". The other issue is, right now we have separated dedicated query per each metrics source. We discussed before that probably graphQL API should parse metrics instead of passing raw string. And I agree but if we loose information from which component kind we are retrieving data, then how could we parse it and expect that `postgress-command` returns `countA` but `schema-registry` returns `countB` and `data-router` does not return counter at all?

2021-02-11 12:59 UTC, closed without merging