CDL Site (Svelte.js TypeScript Version)
epiphany-platform/CommonDataLayer pull request #176
Opened 2021-01-18 08:17 UTC by USSAMOH2

This will compile on deployment to a small build folder that can be dropped in anywhere. It's set up to run on GitHub pages already, so we could buy a domain and point it to the management interface. Let's discuss what to use between the two versions.

2021-01-18 09:40 UTC, frondeus commented on cdl-site/README.md
> +*Looking for a shareable component template? Go here --> [sveltejs/component-template](https://github.com/sveltejs/component-template)*
I think we need to replace this README with sth custom

2021-01-18 09:40 UTC, frondeus commented on cdl-site/rollup.config.js
> +		if (server) server.kill(0);
oh god, this indentation :o I think we need editorconfig file

2021-01-18 09:40 UTC, frondeus commented on cdl-site/src/App.svelte
> +    {:else}
Shouldn't `:else` direct to `NotFound` as well?

2021-01-18 09:40 UTC, frondeus commented on cdl-site/src/pages/insert/Insert.svelte
> +  function sendTransaction() {}
TODO?

2021-01-18 09:41 UTC, frondeus commented on cdl-site/src/pages/query/Query.svelte
> +      <h2>Insert Data</h2>
```suggestion
      <h2>Query Data</h2>
```

2021-01-18 09:43 UTC, frondeus commented on cdl-site/public/global.css
> +  font-family: 'Fredoka One', cursive;
Huh, I'm not a big fan of this font. It's too... rounded and feels fat and casual

2021-01-18 11:29 UTC, Kononnable requested changes
Blocking till we decide which approach should we use(so it won't be merged by mistake, without proper code review).

2021-01-19 10:38 UTC, luke-biel commented on cdl-site/.vscode/extensions.json
> +{
I think we need to discuss what tools we use and we can then add some configs for them, but not within this PR, and in main project directory. Can you remove this for time being?

2021-01-19 10:51 UTC, frondeus commented on cdl-site/.vscode/extensions.json
> +{
To be fair whole `.vscode` dir should be in users gitignore.

2021-01-20 15:28 UTC, USSAMOH2 commented on cdl-site/src/App.svelte
> +    {:else}
Since JS doesn't have an exhaustive match system, there's not a way for me to match the page explicitly. Here, the last unchecked-for page is the Schemas page; `NotFound` is when the `$route` is null.

2021-01-20 15:29 UTC, USSAMOH2 commented on cdl-site/src/pages/insert/Insert.svelte
> +  function sendTransaction() {}
This can't be done until the GraphQL API has the Data Router hooked up to it.

2021-01-20 15:29 UTC, USSAMOH2 commented on cdl-site/src/pages/insert/Insert.svelte
> +  function sendTransaction() {}
I'll add a TODO describing the situation.

2021-01-20 16:38 UTC, USSAMOH2 commented on cdl-site/.vscode/extensions.json
> +{
Yeah, I haven't touch VSCode in months, this comes from the template. I'll get rid of it.

2021-01-25 20:40 UTC, smores56 commented on cdl-site/README.md
> +*Looking for a shareable component template? Go here --> [sveltejs/component-template](https://github.com/sveltejs/component-template)*
Added a README.

2021-01-25 20:41 UTC, smores56 commented on cdl-site/rollup.config.js
> +		if (server) server.kill(0);
Formatted! There's config in the `package.json`, but I hadn't saved the file to auto-format it.

2021-01-25 20:41 UTC, smores56 commented on cdl-site/public/global.css
> +  font-family: 'Fredoka One', cursive;
Changed to a more "formal" font.

2021-02-09 18:29 UTC, Kononnable approved these changes

2021-02-09 20:44 UTC, merged