Use Distributed Database for Schema Registry
epiphany-platform/CommonDataLayer pull request #286
Opened 2021-03-03 23:16 UTC by smores56

To avoid "rolling our own" distribution mechanism by way of replication events in addition to the `leader-elector` service, this PR moves towards using [Citus](https://github.com/citusdata/citus) as a distributed extension of PostgreSQL for storage of schemas. The `leader-elector` and all manual replication has been removed.
In addition, views have been removed from the `schema-registry` until they have been properly defined, and JSON data is now sent to and from the schema registry encoded with MessagePack using gRPC.

2021-03-04 14:29 UTC, frondeus commented on crates/schema-registry/src/db.rs
> +        tokio::spawn(async move {
I'm not sure but i think it could be done by using `Stream` trait and `futures::stream::unfold` method.

2021-03-04 14:29 UTC, frondeus commented on crates/schema-registry/src/db.rs
> +// #[cfg(test)]
Either fix it or remove it. I'd prefer first ;-)

2021-03-08 09:09 UTC, Kononnable requested changes
- Use a Distributed Database for the Schema Registry
- views have been removed from the schema-registry until they have been properly defined
- JSON data is now sent to and from the schema registry encoded with MessagePack using gRPC

Without looking into code I see 3 completely unrelated PRs here. Also tests are failing, but that's a minor concern.

2021-03-08 14:22 UTC, smores56 commented on crates/api/src/schema/mutation.rs
> +        let r#type: rpc::schema_registry::types::SchemaType = new.r#type.into();
Is it because of the cleanliness of the variable? It's redundant.

2021-03-08 14:54 UTC, smores56 commented on crates/api/src/schema/query.rs
> +        &self.definitions
Yes, this is better than loading them individually (e.g., this is faster). When we add the dataloader, we can load only what we need, theorectically.

2021-03-08 14:55 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +            'receive: loop {
It seemed clearer, but it is inconsistent, sure. I'll remove it.

2021-03-08 15:06 UTC, smores56 commented on crates/schema-registry/src/db.rs
> +// #[cfg(test)]
The tests can no longer be done in memory (because the DB needs to be created and migrations run), so I have to make integration tests, they can no longer be done as unit tests. I'll remove them in this PR.

2021-03-08 22:07 UTC, smores56 commented
>     * Use a Distributed Database for the Schema Registry
> 
>     * views have been removed from the schema-registry until they have been properly defined
> 
>     * JSON data is now sent to and from the schema registry encoded with MessagePack using gRPC
> 
> 
> Without looking into code I see 3 completely unrelated PRs here. Also tests are failing, but that's a minor concern.

I have removed the MessagePack conversion from this PR, but I honestly believe this PR is simpler without the inclusion of views. How important is this separation of concerns to you? It will take a lot of work to re-introduce views only to remove them again.

2021-03-09 13:26 UTC, smores56 commented
> Then there should be two PRs - first one removing views and second based on the first which changes a database used.
> ... and probably a third one for larger refactor(api, cli)
> 
> Problem witch PRs as this one is not amount of files it touches. It's the scope - there are multiple unrelated changes which causes that it's hard to tell what is the reason for change of specific lines, so you can't propose a better solution even if such exists.
> 
> 
> If you're going to make any bigger changes to this PR please split it to smaller scoped ones. If not I'll live with merging it as is(after fixes are done). However since it's not the first time I warn you - next time I see PR like this with multiple scopes I'll literally block it. I won't waste several hours on review of such PR if same task can be done in one hour for multiple PRs with smaller scopes. And by looking on some of the comments I won't recommend merging such PR without a proper code review.
> 

Honestly, I'm glad you're taking a stance on this. I will break this up into multiple PR's, and will need to learn how to do so in the future; I'm not experienced breaking stuff up as I write at this scale. I'd love to have a discussion as to how I can do that in the future.

2021-04-20 10:16 UTC, closed without merging

2021-04-20 10:17 UTC, smores56 commented
Since the context of this PR has changed so much, this PR is being closed in favor of one with a better description and fresh discussion.