WIP
epiphany-platform/CommonDataLayer pull request #29
Opened 2020-11-18 09:52 UTC by luke-biel

2020-11-18 14:46 UTC, esavier reviewed
proper naming of PR or drafts, please

2020-11-18 16:58 UTC, luke-biel commented
We don't have standard naming

2020-11-19 05:30 UTC, USSAMOH2 requested changes

2020-11-19 05:30 UTC, USSAMOH2 commented on examples/deploy/docker-compose.yml
> +  victoria_metrics1:
Also, do we need the index after each service?

2020-11-19 05:30 UTC, USSAMOH2 commented on helm/cdl/values-local.yaml
> +  replicaCommandCount: 0
Why are the replica counts 0?

2020-11-19 05:30 UTC, USSAMOH2 commented on build.sh
>  # CDL_PUSH=true
Consider renaming this to something more readable (e.g. PUSH_TO_DOCKER_HUB or something similar).

2020-11-30 19:47 UTC, luke-biel commented
Changes in this were partially merged. Helm still needs to be updated, I'll do that in separate one.

2020-11-30 19:47 UTC, closed without merging