feat: edge-registry
epiphany-platform/CommonDataLayer pull request #294
Opened 2021-03-10 10:10 UTC by luke-biel

Once this PR passes I'm gonna convert all 3 TODO's into issues and write documentation.

2021-03-11 07:57 UTC, smores56 requested changes

2021-03-11 07:57 UTC, smores56 commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env, default = "5432")]
No need to give a default here, it's inconsistent.

2021-03-11 07:57 UTC, smores56 commented on crates/edge-registry/src/lib.rs
> +        let conn = self.pool.get().await.unwrap();
Unwrap?

2021-03-11 08:10 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +        let conn = self.pool.get().await.unwrap();
It's a draft, not ready for review yet

2021-03-15 10:15 UTC, luke-biel commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env, default = "5432")]
While other variables are 90% of time deployment dependent, port rarely changes. It's no cost convinience.

2021-03-16 11:19 UTC, frondeus commented on crates/edge-registry/src/lib.rs
> +                "SELECT id, child_schema_id FROM relations WHERE parent_schema_id = ($1::uuid)",
shouldn't we do `OR child_schema_id = ($1::uuid)`?

2021-03-16 11:20 UTC, frondeus commented on crates/edge-registry/src/main.rs
> +async fn main() {
add `env_logger::init()`

2021-03-16 11:20 UTC, frondeus commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env)]
Please add documentation comments for `--help`

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +            .map_err(|err| Status::internal(err.to_string()))?;
Should not return unknowns to users. They might contain some sensitive information(like host address/db name)

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +            .map_err(|err| Status::internal(err.to_string()))?;
Applies to similar lines bellow.

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +    // TODO: pagination
For now I don't think pagination is required. We can add it when there is a need for that(currently not having it is not an issue).

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/main.rs
> +async fn main() {
and serve metrics

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +                .map_err(|err| Status::internal(err.to_string()))?;
I think we should return some custom error if someone tries to add a relation between two objects if relation is not defined.

2021-03-16 12:11 UTC, Kononnable commented on crates/edge-registry/src/main.rs
> +    Server::builder()
We need to be able to ingest data from MQ.

2021-03-16 12:40 UTC, frondeus commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env)]
I saw "and write documentation." in first comment so I guess it's in backlog ;)

2021-03-16 12:59 UTC, luke-biel commented on crates/edge-registry/src/lib.rs
> +                "SELECT id, child_schema_id FROM relations WHERE parent_schema_id = ($1::uuid)",
I believe these edges are directional

2021-03-16 13:00 UTC, luke-biel commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env)]
I will once this app is accepted. Within this PR. Just after we resolve all issues.

2021-03-16 13:00 UTC, luke-biel commented on crates/edge-registry/Cargo.toml
> +name = "edge-registry"
Registry - it's not repository. Within this PR only this name is used.

2021-03-18 09:47 UTC, luke-biel commented on crates/edge-registry/src/main.rs
> +    Server::builder()
Added MQ listening for new edges

2021-03-18 09:54 UTC, luke-biel commented on crates/edge-registry/src/lib.rs
> +                .map_err(|err| Status::internal(err.to_string()))?;
There are 3 options:
* require users to send schema_ids along object_ids;
* query for schema in which object_id belongs;
* assuming user is responsible for keeping edge-registry intact;

I would prefer 3rd option. We can always add `safe` route later on.

(by user I mean the system, whoever will be ever responsible for sending edge data)

2021-03-18 09:55 UTC, luke-biel commented on crates/edge-registry/src/lib.rs
> +    #[structopt(long, env)]
I where they were needed.

2021-03-18 09:56 UTC, luke-biel commented on crates/edge-registry/src/main.rs
> +async fn main() {
done

2021-03-18 11:58 UTC, esavier submitted a review, later dismissed

2021-03-18 11:58 UTC, esavier commented on crates/edge-registry/src/lib.rs
> +                .map_err(|err| Status::internal(err.to_string()))?;
Triplet (relation_id schema_id schema_id) can be stored in cache later so querying is okay, but now we do not need it. I am also okay with 3'rd option. We can verify that relation_id exists.
Sending schema_ids alongside object_id is not the best idea imo.

2021-03-18 19:24 UTC, luke-biel commented on deployment/compose/docker-compose.cdl.kafka.base.yml
> +      RUST_LOG: info,edge_registry=trace
Agreed, however this is compose. I tend to use trace here on daily basis, and in terms of tests which run on d-c right now, it's valuable.

Helmfiles are debug or info (don't remember which) so in real deployments nobody will turn trace on unless they explicitly decide to do so.

2021-03-18 19:25 UTC, luke-biel commented on deployment/helm/cdl/values-local.yaml
> +edgeRegistry:
Will do, but first thing first I want this PR accepted. Then I'll adjust documentation.

It's just that I prefer to have final view and no more code changes, so I don't have to change docs along.

2021-03-19 10:33 UTC, Kononnable commented on crates/edge-registry/Cargo.toml
> +name = "edge-registry"
Yeas, but so far we used only `repository` when we were talking about this component.
I'm fine with using repository or with using registry, but not with both. If we want to change this name it should also affect other places(e.g. feature list) so people will at least know that we're talking about the same component.

2021-03-19 10:39 UTC, Kononnable commented on crates/edge-registry/src/lib.rs
> +                .map_err(|err| Status::internal(err.to_string()))?;
I meant only checking if relation under `relation_id` binds `schema_1` and `schema_2`.
As discussed previously we should generally store object_ids with schema_ids  since object_id is not guaranteed to be unique in different repositories.

2021-03-19 10:43 UTC, luke-biel commented on crates/edge-registry/Cargo.toml
> +name = "edge-registry"
Agreed, updated that in rfcs

2021-03-19 11:06 UTC, Kononnable reviewed
I'm not sure about edges being directional(when it comes to querying, not storage). They're for sure directional when it come to storage(otherwise we can't do any tree like structure), but as for 'standard' fetch operation it's hard to tell right now. Anyway, it will be easy to 'change' that later on in the future.

One problem with possible panic and I think we're good here.

2021-03-19 11:06 UTC, Kononnable commented on crates/edge-registry/src/main.rs
> +    });
can `consumer.run` panic(now or in the future)?  If so such panic won't be cought.

2021-03-19 12:12 UTC, luke-biel commented on crates/edge-registry/src/main.rs
> +    });
I've registered panic hook in every application. We use `select!` in some places, but `metrics` for example are always run separately. This will make every panic critical.

2021-03-19 23:09 UTC, merged