chore: Replace logging with tokio::tracing
epiphany-platform/CommonDataLayer pull request #320
Opened 2021-03-17 11:10 UTC by frondeus

2021-03-17 11:17 UTC, frondeus commented on crates/api/src/config.rs
> +    pub report_source: Option<String>,
Some changes (like this one) I made to fix CDL and be able to run the whole stack locally.

2021-03-22 15:19 UTC, luke-biel requested changes
I'm aware that clones were already there, but since the API port needs changing, could you fix them?

Also - I believe `edge-registry` is in and should be included. I can do that if you are busy, just give me a notice.

2021-03-22 15:19 UTC, luke-biel commented on crates/api/src/schema/query.rs
> +                .get_all_views_of_schema(rpc_id.clone())
```suggestion
                .get_all_views_of_schema(rpc_id)
```

2021-03-22 15:19 UTC, luke-biel commented on crates/api/src/schema/query.rs
> +                .join(",");
By relying on fmt::Display you can avoid allocation (this requires Itertools)

```
            let id_list = object_ids
                .iter()
                .join(",");
```

2021-03-22 15:19 UTC, luke-biel commented on deployment/compose/docker-compose.cdl.grpc.postgres.yml
> +      REPORT_ENDPOINT_URL: "http://api:50104"
Shouldn't this reflect the change to api port?

2021-03-22 15:19 UTC, luke-biel commented on crates/command-service/src/args.rs
> +    #[structopt(long = "rpc-input-port", env = "GRPC_PORT")]
Just to be sure - this fixes the previous typo and is already reflected in docs/deployments?

2021-03-22 15:37 UTC, frondeus commented on crates/command-service/src/args.rs
> +    #[structopt(long = "rpc-input-port", env = "GRPC_PORT")]
Exactly.

2021-03-22 15:38 UTC, frondeus commented on deployment/compose/docker-compose.cdl.grpc.postgres.yml
> +      REPORT_ENDPOINT_URL: "http://api:50104"
It should in theory, but this is more a placeholder - API right now supports report notifications only from Kafka or AMQP.

2021-03-22 15:52 UTC, frondeus commented
> I'm aware that clones were already there, but since the API port needs changing, could you fix them?
> 
> Also - I believe `edge-registry` is in and should be included. I can do that if you are busy, just give me a notice.

Done & done

2021-03-22 16:54 UTC, luke-biel approved these changes

2021-03-23 08:55 UTC, Kononnable commented
- How does our logging currently look like? I mean we all knew old format (`path: message`), what is displayed after those changes?
- Do we have to set `RUST_LOG` like variable to enable logging or does it support this one?
- Does our tracing reporter support also `log` syntax?  Can we enable logs from rdkafka by changing environmental variables or do we have to add back `env_logger`?

2021-03-23 12:05 UTC, frondeus commented
> * How does our logging currently look like? I mean we all knew old format (`path: message`), what is displayed after those changes?

![An example](https://user-images.githubusercontent.com/1165825/112142974-8aedc580-8bd7-11eb-8b82-fd9b82bbaa15.png)

So when you use `tracing::instrument`, the message format looks like:
(`call site with arguments: path: message`) where call site can look like `Server::run{addr=0.0.0.0:50106}`.
Please keep in mind that these are structural traces, and while it might look inconvenient in the console output, we could use for example [OpenTelemetry](https://github.com/tokio-rs/tracing/tree/master/tracing-opentelemetry) to collect traces, or send them to for example GreyLog and filter them.

> * Do we have to set `RUST_LOG` like variable to enable logging or does it support this one?

You use `RUST_LOG` just like with `log` crate.

> * Does our tracing reporter support also `log` syntax?  Can we enable logs from rdkafka by changing environmental variables or do we have to add back `env_logger`?

While I didn't enable it we could use a compatibility layer to read `log::debug` from dependencies and treat them as traces.

2021-03-23 12:22 UTC, frondeus commented
> While I didn't enable it we could use a compatibility layer to read `log::debug` from dependencies and treat them as traces.

One note - it is true what I wrote, however now I see that `tracing_subscriber` has one optional dependency:

> tracing-log: Enables better formatting for events emitted by log macros in the fmt subscriber. On by default.

Therefore it should print also logs next to traces. It won't, however, send logs to `GELF`/OpenTracing etc.

2021-03-23 13:36 UTC, luke-biel approved these changes

2021-03-23 13:58 UTC, merged