feat: Object builder
epiphany-platform/CommonDataLayer pull request #337
Opened 2021-03-26 13:01 UTC by frondeus

Closes #330 
It does not send data anywhere as we lack an interface - I guess it would be via GRPC.
However I tested it manually, pushed some data, and checked logs - it builds materialized view nicely.

2021-03-28 12:08 UTC, Kononnable requested changes
Had to check PR title multiple times - first 30% of diff shown by github is refactor completely unrelated to PR. One change really, but it takes a lot of space. Just mentioning, no need to change that now.

- No k8s definitions

2021-03-28 12:08 UTC, Kononnable commented on crates/object-builder/src/service.rs
> +        tokio::time::delay_for(tokio::time::Duration::from_secs(3)).await;
It's not related to service itself, it's related to whole program lifecycle, so it should go to main.

2021-03-28 12:08 UTC, Kononnable commented on crates/utils/src/communication/parallel_consumer.rs
> +    fn new_grpc(addr: SocketAddrV4) -> Result<Self> {
Method is not failing so should not return a result.

2021-03-28 12:08 UTC, Kononnable commented on deployment/compose/setup/schema_registry/initial-schema.json
> +            "insert_destination": "http://postgres_command:50202",
Necessary changes or just leftovers from testing?

2021-03-28 12:13 UTC, Kononnable commented on crates/utils/src/lib.rs
>      }
Not sure if that should go to the `lib.rs` or to some other module(or do we need to create new one). It doesn't feels that global to me to go to `lib.rs`.

2021-03-29 11:24 UTC, frondeus commented on crates/object-builder/src/service.rs
> +}
As soon as I'll prepare first materializer then I'll move it to utils.

> why field is Value?

I don't understand what do you expect here. An enum? Even when we know data type (because we have schema with definition in hand) we still need to serialize it somehow, therefore a `Value`. It can be string, number, array, whatever user defines in its schema. I'd go and just send it to the user, and if the data is mismatched with its type in schema, then he should use validator during ingestion in my opinion.

2021-03-29 11:25 UTC, frondeus commented on crates/object-builder/src/args.rs
> +pub struct MissingConfigError(pub &'static str);
well we have similar logic in command service, should we panic there as well?

2021-03-29 11:25 UTC, frondeus commented on crates/object-builder/src/service.rs
> +        // Via GRPC?
Ill send data to materializer as soon as I define one, if you don't mind

2021-03-29 11:25 UTC, frondeus commented on crates/object-builder/src/service.rs
> +        // Via GRPC?
GRPC - sending in response  - done

2021-03-29 11:29 UTC, frondeus commented on deployment/compose/setup/schema_registry/initial-schema.json
> +            "insert_destination": "http://postgres_command:50202",
moved changes to separate `initial-schema.grpc.json` while the original one became `initial-schema.mq.json`. It solves the problem and can be useful. Thanks for pointing it

2021-03-30 09:53 UTC, Kononnable commented on crates/object-builder/src/args.rs
> +pub struct MissingConfigError(pub &'static str);
From my perspective non-recoverable error = panic, if it can be catched and changed to some default value such error type would be fine. Anyway, keeping code more consistent is more important then this change, so for my taste - either change both(if this error isn't being cought anywhere) or keep it as it is.

2021-03-30 10:10 UTC, frondeus commented on crates/object-builder/src/args.rs
> +pub struct MissingConfigError(pub &'static str);
I'll leave it and later create another PR cleaning it.

2021-03-30 10:12 UTC, Kononnable commented on crates/object-builder/src/service.rs
> +}
I think we're making this more complex then it needs to be. If it's just a `string` it's fine. Problems with `value` is that we're introducing one more place we're depending on another crate and the value needs to be serialized in more complex way(`serde_json` validates json on object creation etc.).

2021-03-30 10:21 UTC, frondeus commented on crates/object-builder/src/service.rs
> +}
We still need to parse objects to some kind of structure to retrieve required fields.
How about using `RawValue` instead?

2021-03-30 10:56 UTC, Kononnable reviewed
Looks fine, but I think one more person should look at this because it can get complex really quick(e.g. we had some discussions during review).

2021-03-30 12:25 UTC, frondeus commented on crates/object-builder/src/service.rs
> +}
Okay, the main question is:

> Do we allow having a view where the field points to a complex data structure like an array or a JSON object, or only primitives like strings & numbers? 

Before we answer that we cannot assume anything about this `HashMap`.

Another thing is we have to keep in mind that this view field might be a result of some aggregation or calculation, for example `avg()`.

We could keep everything in the String, and therefore output json would be:
```
{
  "object_id": "...",
  "fields": {
      "foo": "[ 1, 2, 3 ]", //complex scenario
      "bar": "5", //primitive scenario
   }
}
```
But personally, I think it might not be the best idea from the consumer point of view.
I'd use `RawValue` or `Value` here. Then the consumer can easier distinguish if `"5"` means `5` or string with a glyph `'5'`. Which might not **but might be** important for them.

Of course, type info is in the schema so we could, in theory, have some kind of `WhatTypesReturnsThisView` query which would do basically type inference, but it requires extra work and extra call to the schema registry which we might want to avoid.

2021-03-30 13:37 UTC, Kononnable submitted a review, later dismissed

2021-04-02 13:45 UTC, frondeus commented on crates/rpc/proto/object_builder.proto
> +  map<string, bytes> fields = 2;
after writing tests i can see why `bytes` might not be the best representation.
However I did some research and in theory `proto3` documentation tells me to use `Any` type for any JSON object...

Which seems to be unsuported by `prost` :(

2021-04-02 16:01 UTC, Kononnable approved these changes

2021-04-02 16:22 UTC, frondeus commented on crates/rpc/proto/object_builder.proto
> +  map<string, bytes> fields = 2;
changed to `string` for now

2021-04-07 09:32 UTC, luke-biel commented on Cargo.lock
> +version = "1.0.39"
Why it's downgraded?

2021-04-07 09:40 UTC, frondeus commented on Cargo.lock
> +version = "1.0.39"
I... don't know, it wasn't a conscious decision. I don't know why cargo had chosen `.39`. Anyway, ran `cargo update -p anyhow`

2021-04-07 09:41 UTC, luke-biel approved these changes

2021-04-07 09:41 UTC, luke-biel commented on crates/object-builder/src/lib.rs
> +#[serde(rename_all = "snake_case")]
Isn't this a default?

2021-04-07 09:41 UTC, frondeus commented on crates/object-builder/src/lib.rs
> +#[serde(rename_all = "snake_case")]
No, the default for json is `camelCase`

2021-04-07 09:57 UTC, merged