feat(db): add method for exporting all data from DB to json
epiphany-platform/CommonDataLayer pull request #35
Opened 2020-11-23 10:48 UTC by frondeus

2020-11-24 19:44 UTC, USSAMOH2 requested changes

2020-11-24 19:44 UTC, USSAMOH2 commented on .gitignore
> -.vscode/
Why would we want these things committed?

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/error.rs
> +
What's with the extra space? I personally think we don't need it, but if you would prefer to have it, we should be consistent across all of our error enums.

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/rpc.rs
> +        Ok(result)
```suggestion
        self.db.export_all().context("Failed to export the entire database")
```

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/rpc.rs
> +        Ok(())
```suggestion
        self.db.import_all(imported).context("failed to import database")
```

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/types/storage/edges.rs
> +        SCHEMA_VIEW_EDGE_TYPE.clone()
Do you need the `lazy_static!` definition if you only really need them here?

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/types/storage/edges.rs
> +    pub def_id: Uuid,
I know some people prefer brevity, but I would say that the elision here from `definition` to `def` makes the code less readable. How strongly do you prefer the shorter version?

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/types.rs
> +fn get_vertex_property_or<T: DeserializeOwned>(
```suggestion
fn extract_vertex_property<T: DeserializeOwned>(
```
To imply that we are removing the desired property.

2020-11-24 19:44 UTC, USSAMOH2 commented on schema-registry/src/types.rs
> +fn get_edge_property_or<T: DeserializeOwned>(
```suggestion
fn extract_edge_property<T: DeserializeOwned>(
```

2020-11-25 08:47 UTC, luke-biel commented on schema-registry/src/types/storage/edges.rs
> +use super::*;
Not a fan

2020-11-25 09:04 UTC, frondeus commented on .gitignore
> -.vscode/
We don't!
But as @luke-biel pointed, its committer responsibility to have these folders in his own personal global `.gitignore`.

2020-11-25 09:06 UTC, frondeus commented on schema-registry/src/error.rs
> +
Well for me its easier to read

2020-11-25 09:09 UTC, frondeus commented on schema-registry/src/types/storage/edges.rs
> +        SCHEMA_VIEW_EDGE_TYPE.clone()
As far as I understand `Type::new()` has some validation which we unwrap in lazy_static.
I could use constructor here and forget about it but then we would validate on every callsite.
I we don't care about it then yeah, we can remove lazy_static.

2020-11-25 11:03 UTC, luke-biel commented on schema-registry/src/types/storage/edges.rs
> +        SCHEMA_VIEW_EDGE_TYPE.clone()
We can just create Type with unchecked, we are guaranteed these are correct.

2020-11-25 11:05 UTC, luke-biel commented
@frondeus docs aren't as important as other parts of this commit, so you can add them in separate PR.

2020-11-25 11:12 UTC, frondeus commented on schema-registry/src/types/storage/edges.rs
> +        SCHEMA_VIEW_EDGE_TYPE.clone()
But then we `.clone()` - there is allocation anyway right?

2020-11-25 11:13 UTC, frondeus commented
> @frondeus docs aren't as important as other parts of this commit, so you can add them in separate PR.

I know, that's why i focus on other parts than docs.

2020-11-25 14:08 UTC, USSAMOH2 commented on schema-registry/src/types/storage/edges.rs
> +        SCHEMA_VIEW_EDGE_TYPE.clone()
I'm fine with leaving it as is, because the `unchecked` alternative uses unsafe.

2020-11-25 14:11 UTC, USSAMOH2 approved these changes

2020-11-25 14:11 UTC, merged