Documentation
epiphany-platform/CommonDataLayer pull request #36
Opened 2020-11-23 11:02 UTC by rlawrence25

2020-11-23 12:17 UTC, luke-biel submitted a review, later dismissed

2020-11-24 15:58 UTC, USSAMOH2 requested changes

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Command-Service.md
> +The command service is reponsible for consuming a specific input topic and writing that data to its to a variety of different stroage solutions.
```suggestion
The command service is responsible for consuming a specific input topic and writing that data to a variety of different storage solutions. 
```

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Command-Service.md
> +Communication from command service is done through through Kafka. An input topic is consumed and the message is routed to the corresponding db based on configuration.
```suggestion
Communication from the command service is done through through Kafka. An input topic is consumed and the message is routed to the corresponding database based on configuration. 
```

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Data-Router.md
> +    "data": "{ \"some_propery": \"object\"}"
```suggestion
    "data": "{ \"some_property": \"object\"}"
```

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Query-Service.md
> +The query service is reponsible for querying data from several dabtabases.
```suggestion
The query service is responsible for querying data from several databases.
```

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Query-Service.md
> +To configure query service, set environmet variables for `INPUT_PORT`, `DS_QUERY_URL` or `POSTGRES_QUERY_URL` to configure the corressponding database.
```suggestion
To configure the query service, set environment variables for `INPUT_PORT`, `DS_QUERY_URL` or `POSTGRES_QUERY_URL` to configure the corresponding database.
```

2020-11-24 15:58 UTC, USSAMOH2 commented on docs/Getting-Started.md
> +Query Router works with query service to route requests to the correct stoarge solution per schema's query address.
```suggestion
The Query Router works with the query services to route requests to the correct repository, determined per schema (based on its query address).
```

2020-11-30 10:42 UTC, Kononnable commented on docs/Command-Service.md
> +The command service is responsible for consuming a specific input topic and writing that data to its to a variety of different storage solutions.
```suggestion
The command service is responsible for consuming a specific input topic and writing that data to a variety of different storage solutions. 
```

2020-11-30 10:42 UTC, Kononnable commented on docs/Getting-Started.md
> +Below is a following simple amount of steps to getting started working with the services in the CDL locally on your machine. To build and install container images of services within the cd, run `buil
```suggestion
Below is a following simple amount of steps to getting started working with the services in the CDL locally on your machine. To build and install container images of services within the CDL, run `build.sh` in root directory of this project.
```

2020-11-30 10:42 UTC, Kononnable commented on docs/Getting-Started.md
> +Here is the typical sample JSON schema format that the CDL anticipates and ultimatley will validate data by. Please review [README][schema-registry] in `schema-registry` directory for more informatio
```suggestion
Here is the sample JSON schema format that the CDL anticipates and ultimatley will validate data by. Please review [README][schema-registry] in `schema-registry` directory for more information.
```

2020-11-30 10:42 UTC, Kononnable commented on docs/Getting-Started.md
> +Data can be inserted into the system by data being written to Kafka or ingested through RabbitMQ. Data must be in JSON format with the following fields: `schemaId`, `objectId` and `data` to be routed
Right now we listen only on kafka topics, rabbitmq is ready but require few lines of code to be changed.
Question to the team: How we want to approach that? Do we want to enable both by some sort of configuration, or do we keep that as unused feature for now(will be used in the future)?
@epiphany-platform/cdl-team

2020-12-02 10:39 UTC, luke-biel requested changes

2020-12-02 10:39 UTC, luke-biel commented on docs/Command-Service.md
> +POSTGRES_OUTPUT_URL
Well, this has changed. We had to split POSTGRES config into separate envs for `DE` deployment. 
https://github.com/epiphany-platform/CommonDataLayer/blob/develop/examples/deploy/docker-compose.yml#L103

2020-12-02 10:39 UTC, luke-biel commented on docs/Query-Service.md
> +To configure the query service, set environment variables for `INPUT_PORT`, `DS_QUERY_URL` or `POSTGRES_QUERY_URL` to configure the corresponding database.
Same here for postgres
https://github.com/epiphany-platform/CommonDataLayer/blob/develop/examples/deploy/docker-compose.yml#L130

2020-12-08 03:53 UTC, esavier commented on docs/Query-Service.md
> +To configure the query service, set environment variables for `INPUT_PORT`, `DS_QUERY_URL` or `POSTGRES_QUERY_URL` to configure the corresponding database.
updated, please re-review

2020-12-08 09:27 UTC, frondeus requested changes

2020-12-08 09:27 UTC, frondeus commented on docs/Command-Service.md
> +KAFKA_INPUT_TOPIC:
```suggestion
KAFKA_INPUT_TOPIC
```

2020-12-08 09:27 UTC, frondeus commented on docs/Data-Router.md
> +INPUT_QUEUE:
```suggestion
INPUT_QUEUE
```

2020-12-08 09:27 UTC, frondeus commented on docs/Data-Router.md
> +KAFKA_BROKERS:
```suggestion
KAFKA_BROKERS
```

2020-12-08 09:27 UTC, frondeus commented on docs/Data-Router.md
> +KAFKA_ERROR_CHANNEL:
```suggestion
KAFKA_ERROR_CHANNEL
```

2020-12-08 09:27 UTC, frondeus commented on docs/Command-Service.md
> +POSTGRES_OUTPUT_URL
```suggestion
POSTGRES_USERNAME
POSTGRES_PASSWORD
POSTGRES_HOST
POSTGRES_PORT
POSTGRES_DBNAME
POSTGRES_SCHEMA
```

2020-12-08 09:27 UTC, frondeus commented on docs/Query-Service.md
> +POSTGRES_DBNAME
```suggestion
POSTGRES_DBNAME
POSTGRES_SCHEMA
```

2020-12-08 09:41 UTC, frondeus commented on docs/Getting-Started.md
> +Following this example local deploymet, you can query for data saved. Here data is saved within the PR. Ensure that environment variables are set for `POSTGRES_QUERY_URL`, `INPUT_PORT` and `DS_QUERY_
```suggestion
Following this example local deploymet, you can query for data saved. Here data is saved within the PR. Ensure that environment variables are set for `POSTGRES_USERNAME`, `POSTGRES_PASSWORD`, `POSTGRES_HOST`, `POSTGRES_PORT`, `POSTGRES_DBNAME`, `POSTGRES_SCHEMA`, `INPUT_PORT` and `DS_QUERY_URL` or run query service directly on machine.
```

2020-12-08 11:02 UTC, luke-biel approved these changes

2020-12-08 11:03 UTC, merged