something something dark side
epiphany-platform/CommonDataLayer pull request #372
Opened 2021-04-12 16:11 UTC by esavier

thingies

2021-04-12 19:21 UTC, smores56 requested changes

2021-04-12 19:21 UTC, smores56 commented on crates/schema-registry/migrations/20210215170655_init-db.sql
> +-- if you want your trash untouched write your own migration
pls

2021-04-12 19:22 UTC, esavier commented on crates/schema-registry/migrations/20210215170655_init-db.sql
> +-- if you want your trash untouched write your own migration
please remove or write more? :3

2021-04-12 20:28 UTC, smores56 approved these changes

2021-04-13 07:34 UTC, frondeus commented on crates/schema-registry/src/main.rs
> +    sleep(Duration::from_millis(500)).await;
Why this sleep is necessary?

2021-04-13 13:01 UTC, esavier commented on crates/schema-registry/src/main.rs
> +    sleep(Duration::from_millis(500)).await;
it prevents the dark magic of mordor from finding Frodo

2021-04-13 18:52 UTC, merged