Switch StructOpt to Clap
epiphany-platform/CommonDataLayer pull request #388
Opened 2021-04-19 10:18 UTC by luke-biel

2021-04-20 07:03 UTC, smores56 requested changes

2021-04-20 07:03 UTC, smores56 commented on crates/leader-elector/src/main.rs
> +#[derive(Debug, Deserialize, Clap)]
```suggestion
#[derive(Debug, Clap)]
```

We no longer need it be deserializable, that's for Envy.

2021-04-20 10:36 UTC, luke-biel commented on crates/leader-elector/src/main.rs
> +#[derive(Debug, Deserialize, Clap)]
Correct, thanks for pointing it out. Removed.

2021-04-20 10:37 UTC, luke-biel commented on crates/db-shrinker-postgres/Cargo.toml
> +clap = "3.0.0-beta.2"
I've missed this one. Thanks

2021-04-20 15:46 UTC, frondeus requested changes

2021-04-20 15:46 UTC, frondeus commented on crates/command-service/src/args.rs
> +    #[clap(long, env = "COMMUNICATION_METHOD", possible_values = CommunicationMethod::VARIANTS)]
This is a major breaking change:
It does no longer accepts `grpc`, but `g-rpc`,
```
❯ cargo run --bin command-service -- --communication-method grpc
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/command-service --communication-method grpc`
error: 'grpc' isn't a valid value for '--communication-method <communication-method>'
	[possible values: amqp, g-rpc, kafka]

	Did you mean 'g-rpc'?

USAGE:
    command-service <metrics-port> --communication-method <communication-method> --threaded-task-limit <task-limit>

For more information try --help
```

What's more, its case sensitive:
```
❯ cargo run --bin command-service -- --communication-method g-RPC
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/command-service --communication-method g-RPC`
error: 'g-RPC' isn't a valid value for '--communication-method <communication-method>'
	[possible values: amqp, g-rpc, kafka]

USAGE:
    command-service <metrics-port> --communication-method <communication-method> --threaded-task-limit <task-limit>

For more information try --help
```

So either:
* Make it backwards compatible (probably  `#[clap(arg_enum, case_insensitive(true))]` is your friend here instead of `ArgEnum` derive macro: https://github.com/clap-rs/clap/blob/v3.0.0-beta.2/clap_derive/examples/arg_enum.rs),
* Update documentation and HELM definition cause there is a huge mismatch.

2021-04-21 12:25 UTC, luke-biel commented on crates/command-service/src/args.rs
> +    #[clap(long, env = "COMMUNICATION_METHOD", possible_values = CommunicationMethod::VARIANTS)]
Didn't find the `arg_enum` option. It's neat, what I wanted to begin with. Changed everything.

2021-04-22 08:56 UTC, frondeus approved these changes

2021-04-22 10:04 UTC, merged