Feature: Use PostgreSQL for the Schema Registry Backend
epiphany-platform/CommonDataLayer pull request #392
Opened 2021-04-20 10:21 UTC by smores56

This PR moves the storage back-end of the Schema Registry from Sled to PostgreSQL. This allows us to:
- better allow for replication of multiple instances (using PSQL-compliant distributed databases)
- watch for real-time updates over data irrespective of instance
- remove use of volumes from the CDL's deployment

2021-04-20 14:28 UTC, esavier reviewed
partially done

2021-04-20 14:28 UTC, esavier commented on .github/workflows/publish.yml
> +        crates=(command-service data-router query-service query-service-ts schema-registry query-router api edge-registry partial-update-engine object-builder materializer)
materializer-general

2021-04-20 14:28 UTC, esavier commented on build.sh
> +array=( data-router command-service query-router query-service query-service-ts schema-registry upload-to-kafka upload-to-rabbitmq api edge-registry partial-update-engine object-builder materializer
materializer-general

2021-04-20 14:28 UTC, esavier commented on crates/api/src/schema/mutation.rs
>          let span = tracing::info_span!("add_schema", ?new);
tracing::span changed to function attribute,

2021-04-20 14:28 UTC, esavier commented on crates/api/src/schema/mutation.rs
>                  .add_schema(rpc::schema_registry::NewSchema {
can we extract this elsewhere?
i.e. schema::from(NewSchema) ?

2021-04-20 14:28 UTC, esavier commented on crates/api/src/schema/mutation.rs
> +                patch: rpc::schema_registry::SchemaMetadataPatch {
again
patch::from(update)
and implement creation in separate (maybe inline) function

2021-04-20 14:28 UTC, esavier commented on crates/api/src/schema/query.rs
> +impl FullSchema {
why are we splitting stuff into full-schema and schema-update?

2021-04-20 15:27 UTC, Kononnable commented on crates/data-router/Cargo.toml
> +schema-registry         = { path = "../schema-registry" }
Is it still required? Same for other crates.

2021-04-20 15:27 UTC, Kononnable commented on crates/data-router/src/main.rs
>      .await;
Is it me, or are we fetching that info every time using network, without caching it etc. ? Same in other cases below.

2021-04-20 15:27 UTC, Kononnable commented on crates/query-router/src/main.rs
> +    let cache_filter = warp::any().map(move || addr.clone());
How is it related to cache?

2021-04-20 15:27 UTC, Kononnable commented on crates/query-router/src/main.rs
> +async fn main() -> anyhow::Result<()> {
Don't see anything that returns an error.

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/README.md
> +version of [PostgreSQL][psql].
is `Citus` still a requirement?

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/cache.rs
> +pub struct SchemaCache {
Don't see it being used anywhere.

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/cache.rs
> +                            if let Some(entry) = schemas2.lock().unwrap().get_mut(&schema.id) {
Is such unwrap safe?

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/cache.rs
> +
What happens when connection gets broken?

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/cache.rs
> +            .unwrap()
Is this unwrap safe?

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/error.rs
> +    DbError(sqlx::Error),
Can those leak sensitive information like credentials?

2021-04-20 15:27 UTC, Kononnable commented on crates/schema-registry/src/error.rs
> +    NotificationError(sqlx::Error),
Same as above about sensitive information.

2021-04-20 15:27 UTC, Kononnable commented on crates/utils/src/communication/publisher.rs
> +            .set("allow.auto.create.topics", "true")
I think it's consumer only config. It'll be ignored on producers.

2021-04-20 15:27 UTC, Kononnable commented on crates/utils/src/status_endpoints.rs
> +    }
Is it error we can just skip or will it make services unavailable/crashing?

2021-04-20 15:27 UTC, Kononnable commented on deployment/helm/infrastructure/values.yaml
>      enabled: true
Looks like some leftovers.

2021-04-20 16:21 UTC, frondeus commented on crates/utils/src/status_endpoints.rs
> +    }
i wonder if we should skip. If you don't cate about status you can assign `STATUS_PORT=0` to be random

2021-04-21 07:24 UTC, smores56 commented on .github/workflows/publish.yml
> +        crates=(command-service data-router query-service query-service-ts schema-registry query-router api edge-registry partial-update-engine object-builder materializer)
Neither the crate or the folder for the `materializer` are called `materializer-general`. Should I rename it or ignore this?

2021-04-21 07:25 UTC, smores56 commented on crates/api/src/schema/mutation.rs
>          let span = tracing::info_span!("add_schema", ?new);
Fixed by merging in develop.

2021-04-21 08:01 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +pub struct SchemaCache {
This struct is one of the main takeaways of this PR, but must be improved by avoiding needing a constant connection to the SR, so it remains in the codebase but unused.

2021-04-21 08:04 UTC, smores56 commented on build.sh
> +array=( data-router command-service query-router query-service query-service-ts schema-registry upload-to-kafka upload-to-rabbitmq api edge-registry partial-update-engine object-builder materializer
Same as above.

2021-04-21 08:08 UTC, smores56 commented on .github/workflows/test-deployment.yml
> +        run: |
Implemented.

2021-04-21 08:24 UTC, smores56 commented on crates/api/src/schema/mutation.rs
>                  .add_schema(rpc::schema_registry::NewSchema {
The complex ones have been extracted to helper functions, but I left some of them as-is because they seemed simple enough that they didn't warrant the extraction. Let me know if you think I should be more comprehensive here.

2021-04-21 08:24 UTC, smores56 commented on crates/api/src/schema/mutation.rs
> +                patch: rpc::schema_registry::SchemaMetadataPatch {
See above.

2021-04-21 08:26 UTC, smores56 commented on crates/api/src/schema/query.rs
> +impl FullSchema {
Full schemas retrieve more data than just the schema itself, whereas the update only concerns the metadata of the schema.

2021-04-21 08:27 UTC, smores56 commented on deployment/helm/infrastructure/values.yaml
>      enabled: true
Removed.

2021-04-21 08:37 UTC, smores56 commented on crates/api/src/types/schema.rs
> +
Unless there's a reason we currently need the Debug trait on this struct, we should leave it off.

2021-04-21 08:39 UTC, smores56 commented on crates/api/src/types/schema.rs
> +                version.map(|v| version_req.matches(&v)).unwrap_or(false)
Included.

2021-04-21 08:53 UTC, smores56 commented on crates/cdl-cli/src/args.rs
> +        #[structopt(short, long)]
Re-introduced.

2021-04-21 08:56 UTC, smores56 commented on crates/data-router/Cargo.toml
> +schema-registry         = { path = "../schema-registry" }
Removed until the Schema Cache is re-added.

2021-04-21 09:05 UTC, smores56 commented on crates/query-router/src/main.rs
> +async fn main() -> anyhow::Result<()> {
Removed.

2021-04-21 09:07 UTC, smores56 commented on crates/query-router/src/main.rs
> +    let cache_filter = warp::any().map(move || addr.clone());
This was an artifact of the caching introduction and removal, it has been moved back to how it was.

2021-04-21 09:10 UTC, smores56 commented on crates/schema-registry/README.md
> +version of [PostgreSQL][psql].
Removed the Citus requirement (and the rest of the README, as it was moved to the mdbook).

2021-04-21 09:12 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +                            if let Some(entry) = schemas2.lock().unwrap().get_mut(&schema.id) {
To be re-written anyway (the SR cache will change to include retrying and whatnot, so we will handle it then).

2021-04-21 09:13 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +
To be handled in a later PR.

2021-04-21 09:22 UTC, smores56 commented on crates/schema-registry/src/error.rs
> +    DbError(sqlx::Error),
Great question. This error type only has one worrisome variant `TLS`, and it doesn't have any security info.

2021-04-21 09:23 UTC, smores56 commented on crates/schema-registry/src/error.rs
> +    NotificationError(sqlx::Error),
Short answer, no. (see above)

2021-04-21 09:24 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +            .unwrap()
As above.

2021-04-21 09:24 UTC, smores56 commented on crates/utils/src/communication/publisher.rs
> +            .set("allow.auto.create.topics", "true")
Removed.

2021-04-21 09:43 UTC, smores56 commented on crates/utils/src/status_endpoints.rs
> +    }
This PR is probably not the place to mess with this, as it was not added by this PR.

2021-04-21 10:09 UTC, smores56 commented on .github/workflows/test-component.yml
> +  SQLX_OFFLINE: true
It did, so I removed this.

2021-04-21 10:09 UTC, smores56 commented on .gitignore
> +**/.env
No, removed.

2021-04-21 10:10 UTC, smores56 commented on Dockerfile
> +    SQLX_OFFLINE=true LIB_LDFLAGS=-L/usr/lib/x86_64-linux-gnu CFLAGS=-I/usr/local/musl/include CC=musl-gcc CXX=g++ \
Yes, handled.

2021-04-21 10:11 UTC, smores56 commented on crates/data-router/src/main.rs
>      .await;
This is temporary before we update the schema cache.

2021-04-22 07:35 UTC, esavier commented on .github/workflows/publish.yml
> +        crates=(command-service data-router query-service query-service-ts schema-registry query-router api edge-registry partial-update-engine object-builder materializer)
this will be fixed with on-demand materializer, lets ignore for now

2021-04-22 07:40 UTC, esavier commented on crates/api/src/schema/query.rs
> +impl FullSchema {
i would prefer for simplicity's sake to use only one format.
Although its only a note rather than issue, i think its worth to consider

2021-04-22 07:40 UTC, esavier commented on .gitignore
> +**/.env
.gitignore review :)

2021-04-22 07:49 UTC, frondeus commented on crates/api/src/schema/query.rs
> +impl FullSchema {
IMHO this is perfectly fine. It's good to easily distinguish between SchemaMetadata and FullSchema.

2021-04-22 07:51 UTC, frondeus commented on crates/api/src/schema/query.rs
> +    async fn definition(&self, version_req: String) -> FieldResult<&Definition> {
I'd be nice (but not required) to keep info in trace about `schema.id`. It can help to identify which schema is corrupted etc.

2021-04-22 07:55 UTC, frondeus commented on crates/api/src/types/schema.rs
> +
Well its not a library. Otherwise I'd agree with Kononnable.

2021-04-22 08:06 UTC, frondeus commented on crates/schema-registry/src/db.rs
> +            "SELECT id, name, insert_destination, query_address, schema_type as \"schema_type: _\"
Oh. Yeah. This is much cleaner and easier to reason about than vertices, edges inbounds, and outbounds. Thank you!

2021-04-22 08:10 UTC, frondeus commented on crates/schema-registry/src/db.rs
> +    pub async fn connect(config: &Config) -> RegistryResult<Self> {
Maybe I'm blind but i don't see a way to set Postgres schema here (and this would be a requirement for some env).

I'd see something like this here: https://github.com/epiphany-platform/CommonDataLayer/blob/develop/crates/edge-registry/src/lib.rs#L64-L75

And also, please make it configurable.

2021-04-22 08:11 UTC, frondeus commented on crates/schema-registry/src/main.rs
> +    sleep(Duration::from_millis(500)).await;
why do we want to sleep here?

2021-04-22 08:33 UTC, frondeus commented on crates/schema-registry/src/error.rs
> +    #[error("No topic found named \"{0}\"")]
We already have `NoInsertDestination`.

2021-04-22 08:33 UTC, frondeus commented on crates/schema-registry/src/rpc.rs
> +            return Err(RegistryError::NoTopic(new_schema.insert_destination.clone()).into());
We have `insert destination` not `topic` :(

2021-04-22 08:34 UTC, frondeus commented on crates/schema-registry/src/rpc.rs
> +                return Err(RegistryError::NoTopic(destination.clone()).into());
This change is wrong

2021-04-22 08:36 UTC, frondeus commented on crates/schema-registry/src/rpc.rs
>          utils::tracing::grpc::set_parent_span(&request);
```suggestion
        utils::tracing::grpc::set_parent_span(&request);
        //TODO: Request materializer validation for the options
```

2021-04-22 08:37 UTC, frondeus commented on crates/schema-registry/src/rpc.rs
> +        let fields = if request.update_fields {
```suggestion
        //TODO: Request materializer validation for the options
        let fields = if request.update_fields {
```

2021-04-22 08:47 UTC, frondeus commented on crates/rpc/proto/schema_registry.proto
> +message SchemaMetadataPatch {
Please decide for one standard. Either `Patch` (like here) or `Update` (like `ViewUpdate`)

2021-04-22 08:49 UTC, frondeus commented on crates/schema-registry/src/types/view.rs
> +pub enum FieldDefinition {
There is common type `FieldDefinition` in `utils::types::materialization`. Can we reuse it?

2021-04-22 08:49 UTC, Kononnable commented on crates/schema-registry/src/error.rs
> +    DbError(sqlx::Error),
Errors are `non_exhaustive` so they can be changed anytime, even if now there is nothing that concerns us there. I think that should be changed, but it's not a blocker(at least until we move out of R&D phase).

2021-04-22 08:51 UTC, frondeus commented on tests/common/kafka.py
> +    def __init__(self, topic, brokers='127.0.0.1:9092', group_id=None):
Is this a difference?

2021-04-22 08:51 UTC, frondeus commented on tests/common/schema_registry.py
> +            **self.postgres_config.to_dict()
oh cool, didnt know you can do that.

2021-04-22 08:53 UTC, frondeus requested changes
Besides these minor fixes LGTM.

2021-04-22 09:09 UTC, Kononnable commented on crates/utils/src/status_endpoints.rs
> +    }
It's a great way to discourage anyone from creating large PRs.
As people joked around at my first company - `Touching code is considered taking ownership of it.`

This PR **changed** what happens on error(it's ignored now) so it's definitely a proper place to fix it.

2021-04-22 09:15 UTC, Kononnable commented
>To be re-written anyway (the SR cache will change to include retrying and whatnot, so we will handle it then).

So should it be included in this PR? In general I'm not sure if merging it won't kick us in the future - removing caching means performance drop. So it can lead to same situation as in 0.2.0 when we knew there can be performance drop and decided to release anyway.

2021-04-22 10:05 UTC, frondeus commented
> > To be re-written anyway (the SR cache will change to include retrying and whatnot, so we will handle it then).
> 
> So should it be included in this PR? In general I'm not sure if merging it won't kick us in the future - removing caching means performance drop. So it can lead to same situation as in 0.2.0 when we knew there can be performance drop and decided to release anyway.

well we asked to split PR into smaller parts, one of those splitted PR is going to introduce new cache. We cannot eat a cookie and have a cookie.

2021-04-22 13:47 UTC, smores56 commented on tests/common/kafka.py
> +    def __init__(self, topic, brokers='127.0.0.1:9092', group_id=None):
The issue here was that Kafka was sometimes interpreting `localhost` as an ipv6 address, which would fail to connect. This forces ipv4 usage. Technically, there's a configuration option in Kafka `brokers.family.address` that can specify the type of address, but this Python library doesn't allow configuration of it, hence 127.0.0.1.

2021-04-22 14:39 UTC, frondeus commented on tests/common/kafka.py
> +    def __init__(self, topic, brokers='127.0.0.1:9092', group_id=None):
lol ok

2021-04-23 09:05 UTC, smores56 commented on crates/schema-registry/src/db.rs
> +    pub async fn connect(config: &Config) -> RegistryResult<Self> {
Introduced a way to configure the schema and set it for each connection. I look forward to being able to set it for each connection using SQLx more directly.

2021-04-23 09:07 UTC, smores56 commented on crates/schema-registry/src/error.rs
> +    #[error("No topic found named \"{0}\"")]
Good point, this has been fixed!

2021-04-23 09:08 UTC, smores56 commented on crates/schema-registry/src/rpc.rs
> +            return Err(RegistryError::NoTopic(new_schema.insert_destination.clone()).into());
Fixed.

2021-04-23 09:08 UTC, smores56 commented on crates/schema-registry/src/rpc.rs
> +                return Err(RegistryError::NoTopic(destination.clone()).into());
Fixed.

2021-04-23 09:10 UTC, smores56 commented on crates/rpc/proto/schema_registry.proto
> +message SchemaMetadataPatch {
A patch in REST is an object that can have any subset of its fields specified, whereas an update has at least some fields required.

2021-04-23 09:13 UTC, smores56 commented on crates/schema-registry/src/types/view.rs
> +pub enum FieldDefinition {
Re-used!

2021-04-23 09:15 UTC, smores56 commented
> > To be re-written anyway (the SR cache will change to include retrying and whatnot, so we will handle it then).
> 
> So should it be included in this PR? In general I'm not sure if merging it won't kick us in the future - removing caching means performance drop. So it can lead to same situation as in 0.2.0 when we knew there can be performance drop and decided to release anyway.

I ended up just removing it anyway and reverting the stuff that was caching the schema metadata to cache manually again (e.g. Query Router and Data Router).

2021-04-23 09:54 UTC, smores56 commented on crates/data-router/src/main.rs
>      .await;
As mentioned elsewhere, this has been reverted to the old behavior and the unused cache has been removed.

2021-04-23 09:54 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +pub struct SchemaCache {
Removed until appropriate.

2021-04-23 09:55 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +                            if let Some(entry) = schemas2.lock().unwrap().get_mut(&schema.id) {
Removed.

2021-04-23 09:55 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +
Removed.

2021-04-23 09:55 UTC, smores56 commented on crates/schema-registry/src/cache.rs
> +            .unwrap()
Removed.

2021-04-23 10:06 UTC, smores56 commented on crates/utils/src/status_endpoints.rs
> +    }
Since I didn't personally change this, and I am not willing to commit without looking into this, I reverted the change.

2021-04-23 10:08 UTC, smores56 commented on crates/schema-registry/src/error.rs
> +    DbError(sqlx::Error),
Added a todo.

2021-04-23 10:08 UTC, smores56 commented on crates/schema-registry/src/error.rs
> +    NotificationError(sqlx::Error),
Added a todo.

2021-04-23 11:10 UTC, frondeus approved these changes

2021-04-23 11:35 UTC, merged