Add payload to reported errors
epiphany-platform/CommonDataLayer pull request #4
Opened 2020-11-05 12:50 UTC by luke-biel

Resolves #2

2020-11-06 13:13 UTC, luke-biel commented
PR is split into 2 commits - first is refactoring, second is adding `payload`

2020-11-06 13:46 UTC, Kononnable reviewed
Q: How much of this will be applicable after merging #5?

Please limit force pushes to minimum when PR is waiting for reviews - github errors with 'out of date diff' then

2020-11-06 13:46 UTC, Kononnable commented on command-service/src/report/mod.rs
> +    Verbose(VerboseReportServiceConfig),
Not sure if verbose is a good name - right now it's the only option other then no reporting. Anyway it's just an internal name so no problems here.

2020-11-09 12:41 UTC, luke-biel commented on command-service/src/report/mod.rs
> +    Verbose(VerboseReportServiceConfig),
I renamed it to `Full`. Can't really think of any valid name.

As for #5, my changes remove channels from this module, which is exclusive to your changes, however I assume some rebasing will be necessary.

2020-11-09 12:42 UTC, luke-biel commented
> Please limit force pushes to minimum when PR is waiting for reviews - github errors with 'out of date diff' in such cases

I assumed nobody looked at it yet :)

2020-11-17 13:13 UTC, esavier reviewed
looks okay, but since its kinda big commit, someone else also needs to approve it

2020-11-18 10:05 UTC, luke-biel commented
@USSAMOH2 Can you please review code? I guess nobody else can push this forward.

2020-11-19 06:42 UTC, USSAMOH2 requested changes

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/mod.rs
> +}
This has code smell written all over it. Please avoid defaulting to dynamic dispatch when possible, and either reimplement this as an enum or at least remove the need for this `instantiate` method to be called.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/mod.rs
> +pub trait ReportServiceInstance: Send + Sync + 'static {
I assume you did this as a way to not have to rename the existing struct `ReportService`, but the trait should be a verb and the struct should be a noun, not the other way around. Please rename this trait to `ReportService` or `Reporter`, and then rename `ReportService` to something else.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/full_report_service.rs
> +pub struct FullReportServiceInstance {
Instance refers to a literal, singular value, not a type. Please remove the `Instance` suffix.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/full_report_service.rs
> +        let payload = json!({
Though it will technically make the code longer, we should avoid allocating a dynamic JSON object and then rendering it to a string every time (I'd be surprised if that was optimized away, as good as LLVM is). This can be avoided by deriving Serialize on a struct with a lifetime like so:

```rust
#[derive(Serialize)]
pub struct ReportMessage<'a> {
    pub application: &'static str,
    ...
}
```

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/full_report_service.rs
> +        Ok(())
I know it's a common pattern to have an `Ok(())` at the end of the function, but you could just remove the `?;` and not even need the extra 2 lines.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/report/full_report_service.rs
> +pub struct FullReportServiceConfig {
Should this derive Clone?

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/output/victoria_metrics/mod.rs
>          let mut url = self.url.clone();
You shouldn't need to `.clone()` these anymore now that we aren't spawning a future to handle them.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/output/victoria_metrics/mod.rs
> +        let resolution = process_message(url, client, msg).await;
Why not just wrap the resolution in an Ok?

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/output/mod.rs
> +    async fn handle_message(&self, msg: GenericMessage) -> Result<Resolution, OutputError>;
In the scope of this PR, there is no way for any of the implementors of this method to return an error, only a bad resolution. This should be changed (along with all of its implementors) to either return errors when appropriate or to simply return a resolution.

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/output/druid/mod.rs
> +        let producer = self.producer.clone();
Do these still need to be cloned with the lack of future spawning?

2020-11-19 06:42 UTC, USSAMOH2 commented on command-service/src/main.rs
> +    .expect("Running services")
Why not just return an error from `main`?

2020-11-19 12:38 UTC, luke-biel commented on command-service/src/output/psql/mod.rs
>          let payload: Value = match serde_json::from_slice(&msg.payload) {
Can't do, method returns Resolution which is not Try (and I'm not sure I want to implement Try for it)

2020-11-19 12:47 UTC, luke-biel commented on command-service/src/report/config.rs
> +    pub broker: Option<String>,
If env is not set it evaluates to None.

```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
struct TestEnv {
    #[structopt(env = "HOME")]
    home: Option<String>,
    #[structopt(env = "NOHOME")]
    no_home: Option<String>,
}

fn main() {
    let test = TestEnv::from_args();
    
    println!("{:?}", test);
}
```

2020-11-19 12:51 UTC, luke-biel commented on command-service/src/report/mod.rs
> +}
This is Null Object Pattern.
I had real issue to come up with a way to not allocate memory when report service is disabled, but to allow message to be passed if it's enabled. I would love to discuss this if you see different approach, but it's as clean as I could do alone.

2020-11-19 13:06 UTC, luke-biel commented on command-service/src/main.rs
> +    .expect("Running services")
I guess it wasn't there when I started this feature. We need to standarize this, we have some apps unwrap and some `?`

2020-11-20 11:21 UTC, luke-biel commented on command-service/src/report/mod.rs
> +pub trait ReportServiceInstance: Send + Sync + 'static {
Naming things is difficult... Well, I changed them, you can verify if they are ok.

2020-11-20 11:21 UTC, luke-biel commented on command-service/src/report/full_report_service.rs
> +pub struct FullReportServiceInstance {
Changed

2020-11-20 11:21 UTC, luke-biel commented on command-service/src/report/full_report_service.rs
> +        let payload = json!({
Good idea, done that.

2020-11-20 11:23 UTC, luke-biel commented on command-service/src/report/full_report_service.rs
> +pub struct FullReportServiceConfig {
I don't see reason why except for `standard` that all struct should derive Debug and Clone. Well, I've added Clone.

2020-11-20 11:24 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
>          let mut url = self.url.clone();
Url has to be cloned sadly. But I checked other variables that I clone, and removed unnecessary.

2020-11-20 11:24 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> +        let resolution = process_message(url, client, msg).await;
Good point

2020-11-20 11:25 UTC, luke-biel commented on command-service/src/output/mod.rs
> +    async fn handle_message(&self, msg: GenericMessage) -> Result<Resolution, OutputError>;
Agree, good find. Changed Result to Resolution

2020-11-20 11:25 UTC, luke-biel commented on command-service/src/output/druid/mod.rs
> +        let producer = self.producer.clone();
It doesn't have to.

2020-11-20 11:25 UTC, luke-biel commented on command-service/src/main.rs
> +    .expect("Running services")
Changed to anyhow

2020-11-23 09:23 UTC, esavier submitted a review, later dismissed

2020-11-23 20:29 UTC, luke-biel commented on command-service/src/report/full_report_service.rs
> +        Ok(())
Changed

2020-11-23 21:20 UTC, USSAMOH2 requested changes

2020-11-23 21:20 UTC, USSAMOH2 commented on command-service/src/output/sleigh/mod.rs
> +        let resolution = match self.pool.get().await {
You explicitly handle the error when getting a pool connection here, but `unwrap` when getting it elsewhere. You should pick one.

2020-11-23 21:20 UTC, USSAMOH2 commented on command-service/src/output/sleigh/mod.rs
> +        let resolution = match self.pool.get().await {
No need to wrap this in another scope

2020-11-24 09:46 UTC, luke-biel commented on command-service/src/output/sleigh/mod.rs
> +        let resolution = match self.pool.get().await {
I totally missed that leftover unwrap(). Good find. I've removed it.

2020-11-24 09:47 UTC, luke-biel commented on command-service/src/output/sleigh/mod.rs
> +        let resolution = match self.pool.get().await {
I think I did what you meant by that 🤔

2020-11-24 09:52 UTC, esavier approved these changes

2020-11-24 11:03 UTC, USSAMOH2 approved these changes

2020-11-24 11:14 UTC, merged

2020-11-27 14:23 UTC, Kononnable commented on command-service/src/input/service.rs
> +pub struct KafkaInput<P: OutputPlugin> {
Wasn't the whole idea of plugins architecture to keep input and output as separate entities?

2020-11-27 14:23 UTC, Kononnable commented on command-service/src/input/service.rs
> +                        process::abort();
Why is this critical? Failing to save a specific message doesn't really mean that whole service is in an unknown state.
There is a question of kafka changing offsets instead of acknowledging each message on its own but as I recall we've got it 'handled' by `enable.auto.commit`

2020-11-27 14:23 UTC, Kononnable commented on command-service/src/report/full_report_sender.rs
> +pub struct FullReportSender {
I think this should rather contain `FullReportSenderBase` instead of repeating those fields again and again(fields are small so memory footprint isn't a big issue probably).

2020-11-27 14:23 UTC, Kononnable commented on command-service/src/report/full_report_sender.rs
> +                "command_service.status",
Can be extracted as const.