feat: Schema registry validates view's relation ID
epiphany-platform/CommonDataLayer pull request #488
Opened 2021-05-17 15:26 UTC by frondeus

2021-05-18 15:06 UTC, smores56 requested changes

2021-05-18 15:06 UTC, smores56 commented on crates/edge-registry/src/lib.rs
> +    async fn validate_relation_impl(&self, relation_id: &Uuid) -> anyhow::Result<bool> {
From a naming perspective, validate is a verb that implies that the method will do something, not return info. Since this returns whether or not the relation exists, you should either rename it `relation_exists` or return `anyhow::Result<()>`, generating an appropriate error if there is no relation.

2021-05-19 02:16 UTC, esavier approved these changes

2021-05-19 02:17 UTC, esavier commented on crates/edge-registry/src/lib.rs
> +    async fn validate_relation_impl(&self, relation_id: &Uuid) -> anyhow::Result<bool> {
yeah, i agree with Sam, although its just cosmetics

2021-05-19 02:54 UTC, esavier commented
i would like this feature to be configurable
there is a plan to add configuration to each module, similar to MATERIALIZER_CONFIG for the materializer, so while we are adding validation we can add it as well, 
i.e. it will provide a way to turn the validation on/off on per-module base, in this case it would be per view,
proposed struct 
```
Relation { 
  relation_id: uuid,      
  parent_schema_id: uuid,
  child_schema_id: uuid,
  config {
    validate_schema: bool,
  }
}
``
similarly with objects_id for each relations edge

2021-05-19 08:33 UTC, frondeus commented
How about moving this configuration to another PR?

2021-05-19 12:07 UTC, esavier commented
> 
> 
> How about moving this configuration to another PR?
okay, sure i agree

2021-05-19 12:07 UTC, esavier approved these changes

2021-05-20 13:43 UTC, smores56 approved these changes

2021-05-20 13:43 UTC, merged