abstraction over messaging queues
epiphany-platform/CommonDataLayer pull request #5
Opened 2020-11-06 11:35 UTC by Kononnable

- abstraction over communication method
   - allows easy change from kafka to rabbit and vice versa - only consumer/publisher initialization is message system specific
   - doesn't support runtime/compile flag selection of which messaging system we want to use
- some code cleanup(e.g. unused feature flags, unused code)

TODO(outside of this PR scope):
- a way to change messaging system without making code changes - feature flags, runtime check or something else
- there might be some obsolete method/variable names

I'm not exactly sure how to handle errors here. Currently I'm converting each error to common error type - alternatively we can use same approach as in command service(different error type for each error) or deal with that some other way.

2020-11-06 11:40 UTC, Kononnable commented on command-service/src/input/service.rs
> +        let consumer = Box::leak(Box::new(self.consumer));
Not the nicest thing to do, but consumer needs to have static lifetime(or be passed everywhere) and it's static according to application logic anyway.

2020-11-09 12:30 UTC, luke-biel requested changes
Only `leak` comment is kinda blocking. Otherwise you may merge it in my opinion.

2020-11-09 12:30 UTC, luke-biel commented on data-router/src/main.rs
> +        let since_the_epoch = SystemTime::now()
We probably should allow this data to have timestamp already, instead of always inserting it.

2020-11-09 12:30 UTC, luke-biel commented on data-router/src/main.rs
> +                // no error handling necessary - message won't be acked - it was never delivered properly
This is fine for now, but we definitely need to report these incidents somewhere.
- have some log scrapper
- have counter go up in metrics
- send info to report service

2020-11-09 12:30 UTC, luke-biel commented on command-service/src/input/service.rs
> +        let consumer = Box::leak(Box::new(self.consumer));
I would see this in one, well documented place, because someone may miss this leak in the future otherwise.
Options are -
- move creating consumer to main, and there leak it (we will have such behaviour only on top level, it's easier to debug, nobody accidentaly puts this in a loop)
- create method within consumer (or utils in general), eg.`elevate_lifetime_to_static`, that would be explicit in what it does, but is done once in whole codebase - then we can replace it easier
- try and put that in lazy_static or Once at top of this file

I'm leaning towards 2nd option, it's fastest and since you leak this consumer more than once (in data router too), it would merge it all

2020-11-09 12:30 UTC, luke-biel commented on utils/src/messaging_system/message.rs
> +    pub(super) message: BorrowedMessage<'a>,
I'd say we just use pub and limit visibility in parent directory.

2020-11-09 13:18 UTC, frondeus commented on utils/src/messaging_system/consumer.rs
> +        _channel: Box<Channel>,
Why do we wanna store `_connection` and `_channel`? As far as I remember since lapin 1.3 `Channel` and `Connection` are not closed automatically if there is active consumer.

2020-11-10 09:11 UTC, Kononnable commented on data-router/src/main.rs
> +        CommonConsumer::new_rabbit(&config.input_addr, "CDL_DATA_ROUTER", &config.input_queue)
Moved to const. There is no need for configuration variable since it's 'internal' data - no one should be interested in it unless he/she is debugging.

2020-11-10 09:11 UTC, Kononnable commented on utils/src/messaging_system/consumer.rs
> +        _channel: Box<Channel>,
Yep, legacy reasons. Removed.

2020-11-10 09:20 UTC, Kononnable commented on data-router/src/main.rs
> +        let since_the_epoch = SystemTime::now()
Yeah, we definitively need to change that in the future. The question 'how' is kind of problematic. Requiring value from external systems(users) can be problematic since we have no idea if their clocks are synchronized(even if there are there can be some timing problems in specific scenarios). We have no idea what would happen if someone enters timestamp from the past(we have not tested that scenario).

For now I'll leave it be but that need to be changed in the future.

2020-11-10 09:26 UTC, luke-biel approved these changes

2020-11-10 09:27 UTC, Kononnable commented on data-router/src/main.rs
> +                // no error handling necessary - message won't be acked - it was never delivered properly
It's 'internal' error so I wouldn't go for report service(users doesn't really care about error which can be automatically fixed).
Log scrapping is already part of epiphany, if someone decides to deploy cdl on its own they can use `kubectl logs` if they don't use custom logging scrapper.

As for metrics - I think this is a good idea, but currently we have no other similar metrics(debug/performance monitoring centered) - only user centered(throughput).

2020-11-10 09:35 UTC, Kononnable commented on utils/src/messaging_system/message.rs
> +    pub(super) message: BorrowedMessage<'a>,
You mean removing `pub` from `pub mod message;` and just reexport the trait from this module? 
My intention here was to allow types like `KafkaCommunicationMessage` to be accessed from outside, but forbid creating new values of such types in case there are some method on such types which aren't part of the trait - we still don't know how we're gonna decide which messaging we're using(in runtime or by feature flags or similar construct).

2020-11-10 17:15 UTC, luke-biel commented
@Kononnable before you are gone? Can we merge it? Assuming nobody speaks up that something is wrong.

2020-11-10 18:43 UTC, merged