Feat/427/develop
epiphany-platform/CommonDataLayer pull request #506
Opened 2021-05-24 13:00 UTC by frondeus

2021-05-25 13:06 UTC, frondeus commented
Work left: 
```
// TODO: Plan
pub mod notification; // -> cdl_notification
pub mod parallel_task_queue; // -> task_tools
pub mod psql; // -> postgres_tools
pub mod query_utils; // -> query_tools
pub mod status_endpoints; // -> status_tools
```

2021-05-26 07:02 UTC, luke-biel requested changes
I'm not fully sold on `misc_utils` name but I don't have better option as well, so it may stay.

2021-05-26 07:02 UTC, luke-biel commented on crates/utils/src/notification/mod.rs
> +        publisher: CommonPublisher, // FIXME
Can you clean up this FIXME? I don't even remember why I left it now (if it was me)

2021-05-26 07:17 UTC, frondeus commented on Cargo.lock
> +version = "0.15.1"
Sorry, leftovers of some merge

2021-05-26 07:18 UTC, frondeus commented on crates/utils/crates/communication/src/consumer.rs
> +    Unimplemented(std::marker::PhantomData<&'a ()>),
Otherwise it wont compile when no flags are enabled because of unused lifetime

2021-05-26 07:18 UTC, frondeus commented on crates/utils/crates/communication/src/consumer.rs
> +            _ => unreachable!("Enable at least one feature"),
okay, thats good idea

2021-05-26 07:19 UTC, frondeus commented on crates/utils/src/notification/mod.rs
> +        publisher: CommonPublisher, // FIXME
By cleaning up do you mean refactor or just removal of the comment?

2021-05-26 07:35 UTC, frondeus commented on crates/utils/crates/communication/src/consumer.rs
> +            _ => unreachable!("Enable at least one feature"),
One thing - in theory it is not fully an compile error - what if user enables only gRPC?
Then in my opinion CommonConsumer is invalid, but the rest like ParallelCommonConsumer is.

I think I'm just gonna exclude whole module in that case instead of throwing compile error here

2021-05-26 08:20 UTC, esavier approved these changes

2021-05-26 09:57 UTC, luke-biel commented on crates/utils/src/notification/mod.rs
> +        publisher: CommonPublisher, // FIXME
Remove it :)

2021-05-26 09:59 UTC, luke-biel approved these changes

2021-05-26 09:59 UTC, merged