feat: store type of schema
epiphany-platform/CommonDataLayer pull request #56
Opened 2020-11-30 09:33 UTC by damszew

This change:
- extends `schema-registry` so it stores *TYPE* of schema per schema_id
- adds necessary gRPC methods to `schema-registry` to allow malipulations of schema *TYPE*
- adds subcommands to `cdl-cli` to use gRPC methods of `schema-registry`

This is only a part of #15 - `query-router` part will be done in a separate PR when `query-service-ts` is delivered.

2020-11-30 10:07 UTC, frondeus submitted a review, later dismissed

2020-11-30 13:28 UTC, luke-biel submitted a review, later dismissed

2020-11-30 13:28 UTC, luke-biel commented on schema-registry/src/types.rs
> +        write!(f, "{}", printable)
```suggestion
        f.write_str(match self {
            SchemaType::DocumentStorage => "DocumentStorage",
            SchemaType::Timeseries => "Timeseries",
        })```

2020-11-30 13:35 UTC, damszew commented on schema-registry/src/types.rs
> +        write!(f, "{}", printable)
ok

2020-11-30 13:48 UTC, Kononnable reviewed
Apart from this one issue LGTM.

2020-11-30 13:48 UTC, Kononnable commented on cdl-cli/src/actions/schema.rs
> +    schema_type: i32,
Can we use enum type here? This would force simple argument checking on cli tool side.

2020-11-30 13:48 UTC, Kononnable commented on cdl-cli/src/actions/schema.rs
> +    schema_type: i32,
As above

2020-11-30 14:26 UTC, damszew commented on cdl-cli/src/actions/schema.rs
> +    schema_type: i32,
It could be done by implementing `FromStr` trait for enum but this enum would still need to be casted to `i32` to be send over gRPC

2020-12-01 10:05 UTC, Kononnable submitted a review, later dismissed

2020-12-02 10:26 UTC, luke-biel submitted a review, later dismissed

2020-12-02 10:58 UTC, esavier submitted a review, later dismissed

2020-12-03 15:09 UTC, USSAMOH2 requested changes

2020-12-03 15:09 UTC, USSAMOH2 commented on cdl-cli/src/actions/schema.rs
> +    schema_type: i32,
I still think that having the enum that is concerted before sending sets a smaller cardinality of the possible inputs for the CLI, and "self-documents" the options.

2020-12-03 15:09 UTC, USSAMOH2 commented on cdl-cli/src/actions/schema.rs
> +    Ok(())
Shouldn't this return the schema type?

2020-12-03 15:09 UTC, USSAMOH2 commented on cdl-cli/src/args.rs
> +        schema_type: i32,
As mentioned above, this exposes implementation details and is less clean than an enum, so please consider using an enum for the SchemaType.

2020-12-03 15:09 UTC, USSAMOH2 commented on cdl-cli/src/args.rs
> +        #[structopt(short, long)]
See above.

2020-12-03 15:10 UTC, USSAMOH2 commented
You should also make sure that backing up and restoring the schema registry saves the schema types as well.

2020-12-04 07:43 UTC, damszew commented on cdl-cli/src/actions/schema.rs
> +    schema_type: i32,
Ok, in that case I'll use enum here

2020-12-04 07:47 UTC, damszew commented on cdl-cli/src/actions/schema.rs
> +    Ok(())
No because we are returning only if operation was successful or not. Schema type is shown to user via `println` (same as in other functions).

2020-12-04 07:47 UTC, damszew commented on cdl-cli/src/args.rs
> +        schema_type: i32,
ok, I will use enum

2020-12-04 10:10 UTC, damszew commented
@USSAMOH2 There shouldn't be any problems with import/export as unit tests cover this functionality. Nevertheless I have manually tested it and it works as expected (After I've added creation of file before writing export data to it).

2020-12-08 09:07 UTC, frondeus approved these changes
LGTM

2020-12-08 09:43 UTC, Kononnable submitted a review, later dismissed

2020-12-08 13:40 UTC, USSAMOH2 commented on schema-registry/src/types.rs
> +pub enum SchemaType {
Because you cast to an i32, you should maybe use repr(i32) or implement Into<i32> to ensure that the correct type is used.

2020-12-08 13:41 UTC, USSAMOH2 approved these changes
Other than the i32 thing, this looks great!

2020-12-08 14:53 UTC, damszew commented on schema-registry/src/types.rs
> +pub enum SchemaType {
All right, I will add `repr(i32)`

2020-12-08 16:53 UTC, smores56 approved these changes

2020-12-09 07:49 UTC, luke-biel approved these changes

2020-12-09 07:51 UTC, merged