feat(query-service): Add RAW path to Postgres
epiphany-platform/CommonDataLayer pull request #57
Opened 2020-11-30 10:39 UTC by MrDarthShoe

Added RAW path to query-service: 
-Postgresql- manually tested
-Druid- not implemented
-Sled- not implemented

2020-11-30 10:53 UTC, esavier approved these changes
Good for me, but let's wait for others

2020-11-30 11:03 UTC, esavier submitted a review, later dismissed

2020-11-30 14:18 UTC, Kononnable commented on query-service/proto/query.proto
> +    string raw_msg = 1;
Raw message contains raw message?
Statement, query or something similar might be a better name.

2020-11-30 14:31 UTC, MrDarthShoe commented on query-service/proto/query.proto
> +    string raw_msg = 1;
In terms of the same naming I see a convention here: like ObjectIds have object_ids, SchemaID has schema_id-> so RawMsg has raw_msg.
But I agree- I didn't notice duplication of: message with name "raw message"- fixing

2020-11-30 14:34 UTC, USSAMOH2 requested changes

2020-11-30 14:34 UTC, USSAMOH2 commented on query-service/src/psql.rs
> +        let rows = self.make_query(&request.into_inner().raw_msg, &[]).await?;
Since this expects the query to return the same format (not just arbitrary data), this should either document the expected output format somewhere, or use a different response type to allow for such arbitrary data.

2020-11-30 14:42 UTC, USSAMOH2 commented
You'll also need to add an endpoint to the REST API in the query router so that end-users can use this.

2020-11-30 15:03 UTC, MrDarthShoe commented on query-service/src/psql.rs
> +        let rows = self.make_query(&request.into_inner().raw_msg, &[]).await?;
I've discussed that with @esavier and I think we made a conclusion that inside Postgres there will be only tables which contain two strings and user should know that query will result in this kind of response

2020-11-30 15:04 UTC, MrDarthShoe commented
> You'll also need to add an endpoint to the REST API in the query router so that end-users can use this.

This will be included in another PR from my teammate after we get this QS part done

2020-11-30 16:58 UTC, Kononnable commented on query-service/src/psql.rs
> +        let rows = self.make_query(&request.into_inner().raw_msg, &[]).await?;
Ok, table structure contains only two strings, but in sql you can even `select 1, 1, 1` and such raw query will result in three columns. I think the reason to introduce raw queries in sql database in the first place is to let it do much more then just get single key and value(probably use some json functions to prepare data on the server).

2020-12-03 14:34 UTC, USSAMOH2 approved these changes

2020-12-04 15:05 UTC, MrDarthShoe commented on query-service/src/psql.rs
> +        let rows = self.make_query(&request.into_inner().raw_msg, &[]).await?;
This should be fixed now- I return Vec<u8> in GRPC.
It is not pretty though... Maybe you guys can propose a better way of getting values from rows in tokio_postgres

2020-12-08 13:49 UTC, USSAMOH2 commented
@MrDarthShoe wouldn't you want to return `Vec<Vec<u8>>` a.k.a. `repeated bytes` for arbitrary query if someone returns multiple rows?

2020-12-08 14:06 UTC, MrDarthShoe commented
> @MrDarthShoe wouldn't you want to return `Vec<Vec<u8>>` a.k.a. `repeated bytes` for arbitrary query if someone returns multiple rows?

@USSAMOH2  currently I made a convention, that splits multiple columns just by inserting '\t', and rows by inserting '\n' between data-bytes.
Vec<Vec<u8>> is also an option, but what with multiple columns? In that case columns would be split by tab and rows by next Vec.
I think that Vec<Vec<Vec<u8>>> (every row has vector of columns and every field in column has vector of bytes) isn't pretty solution too.
If we want to merge these conventions into Vec<Vec<u8>>, I can do it but I need a green light for that

2020-12-08 16:50 UTC, smores56 approved these changes

2020-12-09 07:58 UTC, luke-biel commented
> > @MrDarthShoe wouldn't you want to return `Vec<Vec<u8>>` a.k.a. `repeated bytes` for arbitrary query if someone returns multiple rows?
> 
> @USSAMOH2 currently I made a convention, that splits multiple columns just by inserting '\t', and rows by inserting '\n' between data-bytes.
> Vec<Vec> is also an option, but what with multiple columns? In that case columns would be split by tab and rows by next Vec.
> I think that Vec<Vec<Vec>> (every row has vector of columns and every field in column has vector of bytes) isn't pretty solution too.
> If we want to merge these conventions into Vec<Vec>, I can do it but I need a green light for that

Vec<Vec<String>> OR Json containing array of arrays of strings are good. Vec<u8> is good as long as it's json too. Right now we require client of QS or QR to write custom parser for raw queries (also, tabs in column value will break it). I don't think that's the way.

2020-12-09 11:47 UTC, MrDarthShoe commented
> > > @MrDarthShoe wouldn't you want to return `Vec<Vec<u8>>` a.k.a. `repeated bytes` for arbitrary query if someone returns multiple rows?
> > 
> > 
> > @USSAMOH2 currently I made a convention, that splits multiple columns just by inserting '\t', and rows by inserting '\n' between data-bytes.
> > Vec is also an option, but what with multiple columns? In that case columns would be split by tab and rows by next Vec.
> > I think that Vec<Vec> (every row has vector of columns and every field in column has vector of bytes) isn't pretty solution too.
> > If we want to merge these conventions into Vec, I can do it but I need a green light for that
> 
> Vec<Vec> OR Json containing array of arrays of strings are good. Vec<u8> is good as long as it's json too. Right now we require client of QS or QR to write custom parser for raw queries (also, tabs in column value will break it). I don't think that's the way.

Now I understand: json should be coded inside raw bytes instead my own encoding convention. I've updated code to do so

2020-12-09 12:06 UTC, luke-biel approved these changes

2020-12-09 12:27 UTC, esavier approved these changes

2020-12-09 12:39 UTC, merged