chore: put cache in utils
epiphany-platform/CommonDataLayer pull request #601
Opened 2021-06-30 10:59 UTC by luke-biel

This is refactor I did while implementing validation. Basically, we had boilerplate for pulling data into cache in 3 places. I've merged them into something a little more condensed.

I've also found out I missed 2 routes in QR when implementing static routing. I've fixed my mistake.

2021-06-30 11:01 UTC, Kononnable commented on crates/data-router/src/handler.rs
> +    // #[tracing::instrument(skip(self, message))]
?

2021-06-30 11:03 UTC, luke-biel commented on crates/data-router/src/handler.rs
> +    // #[tracing::instrument(skip(self, message))]
A mistake, fixed

2021-06-30 13:38 UTC, Kononnable commented on crates/data-router/src/handler.rs
> +    cache: Arc<Mutex<DynamicCache<Uuid, String>>>,
```suggestion
    cache: &Mutex<DynamicCache<Uuid, String>>,
```
plus replacing ` route(self.cache.clone(),` to `route(&self.cache,` in two places.
We don't have to clone `Arc`. Not much but this saves us from unnecessary synchronization between different threads(cloning Arc).

2021-06-30 13:38 UTC, Kononnable commented on crates/data-router/src/handler.rs
> +    cache: Arc<Mutex<DynamicCache<Uuid, String>>>,
Tbh. I think we can safely remove `Arc` now - it was needed earlier, but I don't see any more of it being cloned.

2021-06-30 13:38 UTC, Kononnable commented on crates/data-router/src/handler.rs
> +    let insert_destination = cache.get(event.schema_id).await?;
I'm not sure this is a correct behavior - we're keeping a lock while requesting (over the network) destination address. This will block the whole data router until a response is received - messages sent to different schemas should not be blocked by a request for another schema(unless the same order group id is used but this is handled elsewhere).

2021-06-30 13:38 UTC, Kononnable commented on crates/materializer-general/src/lib.rs
> +        let view_definition = view_cache.get(view_id).await.map_err(error_handler)?;
```suggestion
        {
            let mut view_cache = self.view_cache.lock().await;
            let view_definition = view_cache.get(view_id).await.map_err(error_handler)?;
        }
```
We don't have to keep mutex locked the whole time + same issue as with the previous comment. However, that might not be a problem with materialization yet - OB is still limited to process one view at a time(for now).

2021-07-01 10:48 UTC, luke-biel commented on crates/data-router/src/handler.rs
> +    let insert_destination = cache.get(event.schema_id).await?;
Good find, didn't think about this case.
Difficult change - for me `get` should receive `&mut`, as it's, well, mutating state. But I can't achieve this from outside unless I change cache to be behind a mutex, or `handle` would have signature mentioning `&mut self` (which is impossible, cause &mut is exclusive). Thus I have to put mutex within the cache itself, and call `get()` with normal reference. This also forces me to clone, unfortunately, as guards are short lived. I've experimented with returning a reference, but that's more work than I'm willing to put into it at this moment. So I'm cloning internally. In practice, this doesn't change performance, as we were already cloning fetched data.
I guess there could be a better solution somewhere, but probably with mentions of `unsafe` or `static`.

2021-07-01 11:20 UTC, luke-biel commented
I've changed `lru_cache` as it was unmaintained.
Benches
```
test tests::bench_lru_insert                 ... bench:      52,968 ns/iter (+/- 5,991)
test tests::bench_lru_cache_insert     ... bench:     115,097 ns/iter (+/- 7,874)
test tests::bench_lru_cache_get         ... bench:       1,693 ns/iter (+/- 295)
test tests::bench_lru_get                     ... bench:         836 ns/iter (+/- 69)
```

2021-07-01 13:33 UTC, smores56 requested changes

2021-07-01 13:33 UTC, smores56 commented on crates/query-router/src/schema.rs
> +impl CacheSupplier<Uuid, (String, SchemaType)> for SchemaMetadataSupplier {
Though this is a simple use case, I would rather us make a struct with the fields `query_address` and `schema_type` to avoid having a bare string thrown around.

2021-07-01 13:33 UTC, smores56 commented on crates/data-router/src/schema.rs
> +        let mut client = rpc::schema_registry::connect(self.schema_registry_url.to_owned()).await?;
Did you intend to remove the `trace!`'s, or did they get clobbered. I'm fine without them, just wanna make sure it was intentional.

2021-07-01 14:13 UTC, Kononnable commented on crates/utils/crates/cache/src/lib.rs
> +    cache_supplier: Box<dyn CacheSupplier<Key, Value> + Send + Sync>,
Maybe it's about what someone is used to, but I think it's easier to read code without unnecessary boxing.
My proposal - plus it can be made more readable by creating type alias eg. `type SchemaCache = DynamicCache<SchemaMetadataSupplier, Uuid, String>`. 
https://gist.github.com/Kononnable/b7892073ce1dbd23a3a8c7f9269edccc

Feel free to ignore it if it's a matter of being accustomed to something in your opinion.

2021-07-02 08:07 UTC, luke-biel commented on crates/query-router/src/schema.rs
> +impl CacheSupplier<Uuid, (String, SchemaType)> for SchemaMetadataSupplier {
Yeah, I can agree on that. Changed.

2021-07-02 08:08 UTC, luke-biel commented on crates/data-router/src/schema.rs
> +        let mut client = rpc::schema_registry::connect(self.schema_registry_url.to_owned()).await?;
Well, tracing requires addition fmt::Display or Debug trait to signatures for Key, but I think it's not a problem. I've reinstated tracing in lib itself.

2021-07-02 08:11 UTC, luke-biel commented on crates/utils/crates/cache/src/lib.rs
> +    cache_supplier: Box<dyn CacheSupplier<Key, Value> + Send + Sync>,
I've switched to static dispatch. I'm usually on conservative side when Implementing things, cause `<>` can grow fast. But it wasn't case this time, so I have no problem changing it, and it should be ever so slightly faster.

I'm not a fan of enums if there are many branches, and i'm almost certain that this enum would grow to house at least one more CacheSupplier.

2021-07-02 09:20 UTC, Kononnable approved these changes

2021-07-02 09:37 UTC, merged