chore: feature list update
epiphany-platform/CommonDataLayer pull request #603
Opened 2021-07-01 10:50 UTC by Kononnable

continuation of #596

Introducing materializers isn't a feature on its own, it's part of CDLF-00013-00 Materialized views.
- described in the same RFC as materialized views
- materializers without materialization don't provide any value to a client(or CDL internals), the same goes for the other way around(materialization with no materializers - CDL will report errors). There is no known use case for materialization without any materializers nor for materializers without materialization.

2021-07-01 11:56 UTC, luke-biel approved these changes

2021-07-01 11:56 UTC, luke-biel commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
Is this about CIM format or CDL IM format? I don't wanna be nitpicky about changes that are partially unrelated to this PR, but I'm no longer sure.

2021-07-01 12:22 UTC, esavier requested changes
Both components you mentioned are features that are undocumented. Both components are features since they do introduce behavior that is noticeable by users. There is information what those are doing, but there is no documentation about those.

2021-07-01 12:22 UTC, esavier commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
CDL input format or whatever mononclature is used rn
its a object validataion against schema

2021-07-01 12:30 UTC, luke-biel commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
In rest of the document it's referred as `CDL Input Message`, thus confusion.

2021-07-01 12:38 UTC, esavier commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
when i was writing this it still was CIM, it can be changed but there is nothing official that was chosen

2021-07-01 12:47 UTC, luke-biel commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
Hmm, can we agree on `CDL Input Message` maybe? @frondeus @smores56 @Kononnable . I can provide PR which changes it in all docs if we agree on that.
I understand in this case it's just legacy, but if I'm getting confused, chance is, others will too, so let's get over with it.

2021-07-01 12:50 UTC, smores56 commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
> Hmm, can we agree on `CDL Input Message` maybe? @frondeus @smores56 @Kononnable @esavier  . I can provide PR which changes it in all docs if we agree on that.
> I understand in this case it's just legacy, but if I'm getting confused, chance is, others will too, so let's get over with it.

The correct means is probably `CDL Input Message` defined in the glossary, abbreviated as `CIM` as we would abbreviate Data Router to DR.

2021-07-01 13:05 UTC, luke-biel commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
I would skip abbreviations then, for now. Or change it to CDLIM.

2021-07-01 13:35 UTC, smores56 commented on docs/features/index.md
> +| CDLF-0001B-00 | CIM Object Valdiation                    | Suggestion | -----       |                                       |
Okay, no abbreviations, then.

2021-07-01 13:35 UTC, frondeus commented
> Both components you mentioned are features that are undocumented. Both components are features since they do introduce behavior that is noticeable by users. There is information on what those are doing, but there is no documentation about those.
> Additionally there is no developer documentation for object builder, and it was released.

Okay, this is the matter of "what is a feature". Is a new component a feature? Or the feature is "the new behavior of our system" and the component is only the implementation of this feature? Could this behavior be implemented in one single mono service for the sake of simplicity (but knowing its limitations regarding scalability)?

From my perspective, the feature is behavior, not a component. A component is only a tool used to deliver behavior. Therefore I agree with Paul.

However, I agree with you, Matthew, that both this behavior, its implementation, and its components are **undocumented**. Now what Paul proposed requires that all this documentation would be merged into one single RFC document. It's simply a matter of organizing stuff and being formal. No matter what option we choose, the same amount of work has to be put into this RFC[s].

2021-07-01 15:22 UTC, Kononnable commented
Put on hold until we define what "a feature" actually means.

2021-07-19 08:16 UTC, luke-biel commented
@Kononnable I don't think this is moving forward. Can we just close it?

2021-07-19 10:10 UTC, frondeus commented
> @Kononnable I don't think this is moving forward. Can we just close it?

Probably related task: #645

2021-07-19 11:24 UTC, Kononnable commented
Superseded by #645

2021-07-19 11:24 UTC, closed without merging