chore: e2e materialization tests
epiphany-platform/CommonDataLayer pull request #637
Opened 2021-07-13 10:22 UTC by Kononnable

closes #618

E2E tests for functionalities covered my materialization phase II (#405). 
Some tests are currently placeholders(no code) as some part of the API is under redesign(#624, #631)

2021-07-19 08:47 UTC, luke-biel requested changes

2021-07-19 08:47 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +    async fn should_compute_field_from_another_object() -> Result<()> {
```suggestion
    async fn should_compute_field_when_more_than_one_objects_in_relations() -> Result<()> {
```

I don't see a place where you'd take value from object b for computation.

2021-07-19 08:47 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +                assert!(field_a == 1 || field_a == 2);
I would prefer more explicit asserts as tests are a form of documentation. If you have problems with order of values, use `.sort(&mut self)`.

This test will accept result `[{field_a: 1}, {field_a: 1}]`.

2021-07-19 08:47 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +            }
Same as above - please convert to explicit asserts instead of loop.

2021-07-19 08:47 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +use crate::{api::*, *};
Notes about readability:

I'm a fan of using tests as a way to document processes, and any file with over 1000 lines won't be really read by developers - sifting though it is difficult.

I would love to see some adjustments that would help improving this readability, my ideas are:
* put submodules in separate files
* use macros to reduce boilerplate regarding building Filter or Compute fields

I understand that there are e2e that will supersede this soon, but we don't yet know when.

2021-07-19 08:47 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +        async fn should_allow_filtering_using_field_not_materialized_in_view() -> Result<()> {
This behavior has to be documented for end user.

2021-07-19 09:17 UTC, frondeus commented on e2e/src/on_demand_materializer.rs
> +use crate::{api::*, *};
I vote for option 1

2021-07-19 09:18 UTC, frondeus commented on e2e/src/on_demand_materializer.rs
> +        insert_message(object_id_a, schema_a, "{}").await?;
I think we should insert more objects to really see whether this is inner join or outer join

2021-07-19 09:34 UTC, luke-biel commented on e2e/src/on_demand_materializer.rs
> +use crate::{api::*, *};
Well, it's not `one_of options` combinator, it's `all_of options`, if possible of course

2021-07-19 12:18 UTC, Kononnable commented on crates/dto/src/materialization.rs
> +        // TODO: Consider adding optional base field - for fields from related schema without need of using subobject - currently workaround as computed field
I was planning to go through all TODOs(write them into issues if necessary) when phase II is close to being finished(all major features are implemented, docs are more or less there - scope is well known). There are a couple of TODOs left, some may get invalidated once other parts of phase II are finished.

Is it ok with you to keep it untill then?

2021-07-19 12:35 UTC, Kononnable commented on e2e/src/on_demand_materializer.rs
> +        async fn should_allow_filtering_using_field_not_materialized_in_view() -> Result<()> {
Yes, like all other changes related to materialization. However, materialization documentation is blocked until its scope is known(until we decide what is a feature and what is not and how to group materialization feature documentation). This was partially solved by #608, #645 contains what is left(splitting features). After merging #608 at least the writing of part of the documentation can be done.
In general, we should document things sooner, I decided to add those tests before documentation so the whole partially implemented feature is not completely blocked and can be somewhat tested during implementation.

2021-07-19 12:40 UTC, Kononnable commented on e2e/src/on_demand_materializer.rs
> +        insert_message(object_id_a, schema_a, "{}").await?;
2 objects are enough to tell if it's inner or any of the outer joins. It wouldn't be enough to be specific about which outer join strategy is used.
I don't see any more asserts necessary here, but If you think we need something more please add an example of a situation that this test misses.

2021-07-19 12:58 UTC, luke-biel commented on crates/dto/src/materialization.rs
> +        // TODO: Consider adding optional base field - for fields from related schema without need of using subobject - currently workaround as computed field
Yeah, if you are taking responsibility of doing this, it's ok with me.

2021-07-20 06:59 UTC, Kononnable commented on e2e/src/on_demand_materializer.rs
> +        assert_eq!(view_data.rows.len(), 1);
and it's even a reason why this test was skipped :|

2021-07-20 07:46 UTC, Kononnable commented on e2e/src/on_demand_materializer.rs
> +use crate::{api::*, *};
I have split the module into separate files. I decided not to go macro way for now - we plan to remove that code sooner and reading more verbose is easier for people unfamiliar with rust(not sure who will rewrite those tests into a new testing framework).

2021-07-20 08:37 UTC, luke-biel approved these changes

2021-07-20 09:40 UTC, frondeus approved these changes

2021-07-20 09:46 UTC, merged