docs: rfc: CI/CD setup R&D
epiphany-platform/CommonDataLayer pull request #640
Opened 2021-07-13 13:00 UTC by esavier

2021-07-19 12:40 UTC, luke-biel requested changes
A typo, rest looks ok

2021-07-19 12:40 UTC, luke-biel commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +It is very versatile tool that allows for adjustments and modifications. Community is quite active and thre is a lot of plugins for different systems and usecases. Hoewver in our case there were prob
```suggestion
It is very versatile tool that allows for adjustments and modifications. Community is quite active and there is a lot of plugins for different systems and usecases. Hoewver in our case there were problems with proper configuration of the service itself. Numerous issues with HTTPS reverse proxy (among others) was noticed and prevented us from, for example, providing or changing configuration and communicating with the agents. Despite that the setup can be adjusted to take that into account, for example by providing proper vpn connections, switching to plain http and locking the machine itself from outside world. Anoher problem is that java errors are not easy to understand nor to fix.
```

2021-07-19 12:52 UTC, frondeus commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +Currently, all our tests are being ran on the GitHub public cloud. We do have, as a OSS project, a lot of flexibility in this matter and GitHub provides for us almost infinite resources to help with
```suggestion
Currently, all our tests are being run on the GitHub public cloud. We do have, as an OSS project, a lot of flexibility in this matter, and GitHub provides us almost infinite resources to help with our development. However, being the generic system, we are using VM's and environments that we do not control fully. We cannot guarantee that tests that we want to do will run in the same environment and thus tests are not comparable with each other.
```

2021-07-19 13:00 UTC, frondeus commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +Currently, all our tests are being ran on the GitHub public cloud. We do have, as a OSS project, a lot of flexibility in this matter and GitHub provides for us almost infinite resources to help with
Besides that, looks good to me

2021-07-19 13:44 UTC, pgr-automation approved these changes

2021-07-19 14:21 UTC, frondeus commented
Please rename RFC filename to for example:
`0015_CI_CD_setup_RnD_01.md`

2021-07-20 08:35 UTC, luke-biel approved these changes

2021-07-20 09:43 UTC, Kononnable reviewed
I don't agree with all Architecture Considerations(e.g. need of tinkering with the kernel), but as it's research, not resulting in any direct decisions it's fine with me.

However, those two comments probably should be taken care of before merging.

2021-07-20 09:43 UTC, Kononnable commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +Due to us being partially lazy and partially having limited resources for our disposal, we decided that it would be the best idea to follow a hybrid solution for now. That means that we will keep Git
```suggestion
We decided that it would be the best idea to follow a hybrid solution for now. That means that we will keep GitHub actions for whatever we are doing right now, i.e. code quality and compliance testing, that can be run multiple times in parallel, and thus unlimited resources GitHub provides would be the best option for it. For performance testing, we will use the playground server stack which is configured, stable and persistent across tests. That also means that each test will be started in the environment as similar to each other as possible.
```
This has nothing to do with laziness or limited resources(in a reasonable way). Github actions have some benefits that private hosted CI does not. E.g. CI status and run details are available publicly, any contributor can run tests on CI, even on their own fork - you don't need access to the internal environment.

2021-07-20 09:43 UTC, Kononnable commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +In addition, we will be able to perform server tuning and advise for best HW and SW configuration for CDL to run on.
What does `HW`, `SW` stands for?

2021-07-20 09:51 UTC, frondeus commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +In addition, we will be able to perform server tuning and advise for best HW and SW configuration for CDL to run on.
Hard Ware and Soft Ware I presume?

2021-07-29 06:32 UTC, esavier commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +Due to us being partially lazy and partially having limited resources for our disposal, we decided that it would be the best idea to follow a hybrid solution for now. That means that we will keep Git
yeah i wrote that because i was lazy

2021-07-29 11:11 UTC, Kononnable approved these changes

2021-07-29 11:11 UTC, Kononnable commented on docs/rfc/NAF-CI_CD_setup_rnd.md
> +Last updated    : 2021-07-19
I guess it's should be updated again

2021-08-06 10:03 UTC, Kononnable submitted a review, later dismissed

2021-08-06 10:07 UTC, frondeus approved these changes

2021-08-06 10:07 UTC, frondeus requested changes
Please fix filename

2021-08-06 10:37 UTC, esavier commented
done, cheers mate :+1:

2021-08-06 10:40 UTC, frondeus approved these changes

2021-08-06 10:44 UTC, merged