feat: config generator - provide grpc and rabbitmq development env for developers
epiphany-platform/CommonDataLayer pull request #643
Opened 2021-07-15 13:32 UTC by luke-biel

Well, this is bigger than expected, had to refactor more cdl parts than I anticipated.

* Moved all *settings* structs to one central place, `setting_utils`
* Moved `notification_utils` to separate crate due to cyclic deps
* Added `cdl-config-generator` crate, `cargo run -p cdl-config-generator`
* Removed `.cdl` folder, now user should generate one on their own
* There were leftover `args.rs` files in some crates, I deleted them
* Some deployment details were adjusted

2021-07-19 07:16 UTC, frondeus commented
I think cdl-config-generator could be a part of `cargo xtask`. What do you think?

2021-07-27 09:21 UTC, Kononnable reviewed
General review is done, I didn't get much into implementation yet(will do once current discussions are resolved).

Why do we keep app startup parameters in utils? 
This isn't something reusable, so they probably should live much closer to where they're used.

2021-07-27 09:21 UTC, Kononnable commented on crates/command-service/src/lib.rs
> +                }),
`.into()` or some similar conversion impl?

2021-07-27 09:21 UTC, Kononnable commented on crates/command-service/src/lib.rs
> +                    .filter(|s| !s.is_empty()),
We should check if both iterators are not empty - if so configuration has errors.
Not sure if it was tested before.

2021-07-27 09:21 UTC, Kononnable commented on crates/command-service/src/lib.rs
> +    for topic in ordered_sources.chain(unordered_sources) {
According to this, there is no difference between ordered and unordered sources?

2021-07-27 09:47 UTC, luke-biel commented on docs/configuration/command-service.md
> +unordered_sources = "of,topics,queues,or,urls"
We accept string here, docs were wrong, this fixes that.

String is necessary because we still didn't switch to configs in helm and envs cannot into arrays.

2021-07-27 09:49 UTC, luke-biel commented on xtask/src/config_generator/defaults.rs
> +pub const DEFAULT_VICTORIA_METRICS_HOST: &str = "http://localhost:8428";
This can be changed in the `creator` tool. I had to set something `default`. Other option is to have user fill this in on startup, which is tedious.

2021-07-27 09:50 UTC, luke-biel commented on xtask/src/config_generator/defaults.rs
> +);
It's about consistency. Otherwise I have to copy port number twice. It can be fallible - you change one, but not the other.

2021-07-27 09:51 UTC, luke-biel commented on xtask/src/config_generator/context.rs
> +                rust_log: "info,schema_registry=debug".to_string(),
I need to have some defaults. There are only for config generation. There's no default logging in settings themselves.

2021-07-27 09:53 UTC, luke-biel commented on crates/api/src/events.rs
> +use settings_utils::apps::api::ApiSettings;
I had places where this was necessary, otherwise I had to rename in `use` section. I choose this as simplier method.

2021-07-27 09:53 UTC, luke-biel commented on crates/command-service/src/input/service/mod.rs
>  use async_trait::async_trait;
Clippy, don't remember doing this by hand

2021-07-27 13:12 UTC, esavier commented
i have small problem to solve,
`Removed .cdl folder, now user should generate one on their own`
that means that there is additional action to do before tests can be started and in case of horust, generated config by default won't work, and have to be adjusted manually. 
i do not know how to fix that though, i will try to find a solution and come back to you

2021-07-27 13:52 UTC, luke-biel commented
> i have small problem to solve,
> `Removed .cdl folder, now user should generate one on their own`
> that means that there is additional action to do before tests can be started and in case of horust, generated config by default won't work, and have to be adjusted manually.
> i do not know how to fix that though, i will try to find a solution and come back to you

Tests still use their own cdl config, I didn't touch them. Unless we are talking dotNet tests, but I see they are passing on CI.
As for horust - generated config should be identical to the one currently added to .cdl folder, with exception, all configs are currently in `development` subfolder. I think this should be backwards compatible, unless there's some setup caveat that I didn't take into account.

2021-07-28 08:00 UTC, Kononnable commented on crates/api/src/events.rs
> +use settings_utils::apps::api::ApiSettings;
I personally in similar cases often use:
`use settings_utils::apps::api`
and then 
`api::Settings` in code.

However, it's probably a personal habit.

2021-07-28 08:07 UTC, Kononnable commented on xtask/src/config_generator/context.rs
> +                rust_log: "info,schema_registry=debug".to_string(),
From a user perspective, I think defaults(when no value is passed) should be fine. We can make them obvious(pass with default value), to make it easier for developers to change.
Default is `error`, I'm fine with `warning` or `info` levels (from the user's perspective). If we decide that 'default' should be the settings for developers then `debug` is fine. I don't think users should see debug info by default.

2021-07-28 08:11 UTC, Kononnable commented on xtask/src/config_generator/defaults.rs
> +);
I don't think it's worth it. `$host_var` can be created using a previously defined variable without macros as well(if the problem is copying port number).
However, probably it's all about personal feelings/opinions again :)

2021-07-28 09:16 UTC, luke-biel commented on xtask/src/config_generator/context.rs
> +                rust_log: "info,schema_registry=debug".to_string(),
Hmm, I'm taking what was in .cdl currently there. You point is valid, what if user uses config-generator. But as long as it's xtask and not separate binary, i think we are fine, this is a developer tool for time being.

2021-07-28 09:17 UTC, luke-biel commented on xtask/src/config_generator/defaults.rs
> +pub const DEFAULT_COMMAND_SERVICE_URL: &str = "0.0.0.0:50201";
It's listening address vs connecting address. I'm gonna change sufix to `LISTEN_URL` to disambiguate.

2021-07-28 09:30 UTC, luke-biel commented on xtask/src/config_generator/context.rs
> +                otel_service_name: "schema_registry".to_string(),
I can store this as const, and I will do that, but from outside SR i can't reliably get that name. One idea is to depend on SR, but this introduces cyclic deps.

2021-07-28 09:34 UTC, luke-biel commented
> Why do we keep app startup parameters in utils?
> This isn't something reusable, so they probably should live much closer to where they're used.

You mean settings? Two reasons - I had to move them in order to be able to reuse them in config-generator (otherwise cyclic deps); We will require same structures in `CfgS` - and them we'll move them anyway.
I agree it felt weird at first, but one of benefits of what I'm seeing now is that it's easier to maintain, especially when reusing some structs.

2021-07-28 10:08 UTC, luke-biel commented on crates/command-service/src/lib.rs
> +    for topic in ordered_sources.chain(unordered_sources) {
That's a copypasta. It was changed long ago, previously we used:
```
let mut consumers = Vec::new();
        for ordered in config.ordered_configs() {
            let consumer = ParallelCommonConsumer::new(ordered)
                .await
                .map_err(Error::ConsumerCreationFailed)?;
            consumers.push(consumer);
        }

        for unordered in config.unordered_configs() {
            let consumer = ParallelCommonConsumer::new(unordered)
                .await
                .map_err(Error::ConsumerCreationFailed)?;
            consumers.push(consumer);
        }
```

Chain is just a simplification of the loop. You can lookup #470

2021-07-28 10:10 UTC, luke-biel commented on crates/command-service/src/lib.rs
> +                    .filter(|s| !s.is_empty()),
It wasn't tested, that's a copypasta. I can add a guard though.

2021-07-28 10:12 UTC, luke-biel commented on crates/command-service/src/lib.rs
> +                }),
Done

2021-07-28 10:12 UTC, luke-biel commented on crates/query-router/src/handler.rs
> +fn convert_schema_type(typ: RepositoryType) -> SchemaType {
I've changed this to `From` and moved to settings.

2021-07-28 10:41 UTC, luke-biel commented on crates/command-service/src/lib.rs
> +    for topic in ordered_sources.chain(unordered_sources) {
I've noticed this removed exclusive from amqp consumer, so this may be an issue

2021-07-28 11:41 UTC, esavier commented
> > i have small problem to solve,
> > `Removed .cdl folder, now user should generate one on their own`
> > that means that there is additional action to do before tests can be started and in case of horust, generated config by default won't work, and have to be adjusted manually.
> > i do not know how to fix that though, i will try to find a solution and come back to you
> 
> Tests still use their own cdl config, I didn't touch them. Unless we are talking dotNet tests, but I see they are passing on CI.
> As for horust - generated config should be identical to the one currently added to .cdl folder, with exception, all configs are currently in `development` subfolder. I think this should be backwards compatible, unless there's some setup caveat that I didn't take into account.

For horust there are two options, one is grpc and the second is kafka. I think both will fail since for example metrics ports will clash. What i ment by the "additional actio" was adjusting the config to work on bare metal.

2021-07-28 11:51 UTC, luke-biel commented
> > > i have small problem to solve,
> > > `Removed .cdl folder, now user should generate one on their own`
> > > that means that there is additional action to do before tests can be started and in case of horust, generated config by default won't work, and have to be adjusted manually.
> > > i do not know how to fix that though, i will try to find a solution and come back to you
> > 
> > 
> > Tests still use their own cdl config, I didn't touch them. Unless we are talking dotNet tests, but I see they are passing on CI.
> > As for horust - generated config should be identical to the one currently added to .cdl folder, with exception, all configs are currently in `development` subfolder. I think this should be backwards compatible, unless there's some setup caveat that I didn't take into account.
> 
> For horust there are two options, one is grpc and the second is kafka. I think both will fail since for example metrics ports will clash. What i ment by the "additional actio" was adjusting the config to work on bare metal.

And how are you dealing with this right now? Cause current .cdl specifies ports as random, same as this config generator will.

2021-07-28 11:54 UTC, Kononnable commented
Maybe we should add metrics serving as an option - if you don't specify a port they're disabled. This will solve problems that may happen on bare metal(using random ports feels weird).

2021-07-28 13:31 UTC, esavier commented
> Maybe we should add metrics serving as an option - if you don't specify a port they're disabled. This will solve problems that may happen on bare metal(using random ports feels weird).

sorry i am not able to respond right now, lets meet up and discuss it around Friday or Thursday

2021-07-29 10:39 UTC, Kononnable commented on crates/command-service/src/lib.rs
> +    for topic in ordered_sources.chain(unordered_sources) {
I don't think we either can use `ParallelCommonConsumer` everywhere and don't need configuration split, or it can be used only in one place. I have to check that, anyway, it's not related to current PR.

2021-07-30 08:08 UTC, smores56 requested changes

2021-07-30 08:08 UTC, smores56 commented on xtask/src/config_generator/context.rs
> +use crate::config_generator::defaults::{
Is there anything in this file that can be extracted? GitHub wouldn't even render it by default because it is too big, and it has a lot of different stuff in it.

2021-07-30 08:08 UTC, smores56 commented on docs/configuration/generator.md
> +# cdl-config-generator
Can we add documentation to the main README or some CONTRIBUTORS document to tell new developers that they should run this every time they clone the repo?

2021-07-30 08:08 UTC, smores56 commented on crates/utils/crates/settings/src/apps/mod.rs
> +const fn default_status_port() -> u16 {
Considering that a lot of the default config is being consolidated, should this be removed in favor of our new options?

2021-07-30 08:08 UTC, smores56 commented on .gitignore
> +.cdl
Should this maybe be renamed to config? Not that it matters much, but this not that descriptive of a name.

2021-07-30 13:29 UTC, luke-biel commented
Needs an update according to new requirements in the issue

2021-08-10 10:18 UTC, luke-biel commented on xtask/src/config_generator/defaults.rs
> +}
done

2021-08-10 10:20 UTC, luke-biel commented on xtask/src/config_generator/mod.rs
> +                Err(error) => println!(
I thought about it, initially didn't want to add another dep `erased_serde` plus this boxing, but in the end it's cleaner. done

2021-08-10 10:20 UTC, luke-biel commented on xtask/src/config_generator/mod.rs
> +const START_FILE_BASE: &str = r#"#!/usr/bin/env bash
good point

2021-08-10 10:24 UTC, luke-biel commented on xtask/src/config_generator/mod.rs
> +    fs::write(
done

2021-08-10 10:24 UTC, luke-biel commented on xtask/src/config_generator/mod.rs
> +        match option {
done

2021-08-10 10:24 UTC, luke-biel commented on xtask/src/config_generator/context.rs
> +            Repo::Postgres => bail!("postgres is not a valid timeseries repo backend"),
checked this file; I didn't look anywhere else, I think we have consistency issuess across the project

2021-08-10 10:25 UTC, luke-biel commented on xtask/src/config_generator/context.rs
> +use crate::config_generator::defaults::{
I've split it per app

2021-08-10 10:25 UTC, luke-biel commented on docs/configuration/generator.md
> +# cdl-config-generator
We'll return config, I'll look into fixing our readme, but maybe after we merge this

2021-08-10 10:26 UTC, luke-biel commented on crates/utils/crates/settings/src/apps/mod.rs
> +const fn default_status_port() -> u16 {
I'd love to, but this would be a breaking change in theory - I've already made some fields skippable, and this means that even with config generation, users may use hand-written configuration that would break in absence of these defaults

2021-08-10 10:27 UTC, luke-biel commented on .gitignore
> +.cdl
I've named this like e.g. `.cargo` calls it's config folder. It's application specific. I dunno, feels like personal pref

2021-08-11 10:12 UTC, merged