docs: add uml diagrams of our services, add query-router API spec
epiphany-platform/CommonDataLayer pull request #66
Opened 2020-12-02 13:45 UTC by luke-biel

2020-12-02 14:27 UTC, frondeus approved these changes

2020-12-02 14:44 UTC, frondeus submitted a review, later dismissed

2020-12-02 16:30 UTC, USSAMOH2 requested changes

2020-12-02 16:30 UTC, USSAMOH2 commented on docs/Architecture.md
> +Two query-services are present. One for timeseries databases, one for documents.
```suggestion
The gRPC frontend of each database. Each Query Service serves a common set of queries, and translates those into their respective database's query language. Two query-services are present: one for timeseries databases, and one for documents.
```

2020-12-02 16:30 UTC, USSAMOH2 commented on docs/Architecture.md
> +Query router is capable of retrieving data from various sources. More at [documentation][query-router].
```suggestion
The Query Router is capable of retrieving data from various sources. More at [documentation][query-router].
```

2020-12-02 16:30 UTC, USSAMOH2 commented on docs/graphs/DataRouter-MessageIngestion.puml
> +DR -> MQ: Reroute message to coresponding topic
```suggestion
DR -> MQ: Re-route message to corresponding topic
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +REST interface over CDL. Used to retrieve data from repositories.
```suggestion
The REST interface over the CDL, used for retrieving data from any repository.
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +To run **query-router** requires [schema-registry][schema-registry] and [query-services][query-service] connected to repositories.
```suggestion
To run the **query-router** requires the [Schema Registry][schema-registry] to be running and the [Query Services][query-service] connected to their respective repositories.
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +Environment required is provided via variables:
```suggestion
Configuration is expected through the following environment variables:
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +| name | short description | example |
```suggestion
| Name | Short Description | Example |
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +| CACHE_CAPACITY | How many entries can cache hold | 1024 |
```suggestion
| CACHE_CAPACITY | How many entries the cache can hold | 1024 |
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +Please note that currently cache is valid forever - changes to schema **query-service** address will not be updated in **query-router**.
```suggestion
_Note: Currently, the cache is valid forever: changing a schema's **query-service** address will not update in the **query-router**._
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/README.md
> +Currently **query-router** can handle querying data by id from document repositories.
```suggestion
Currently, the **query-router** can handle querying data by ID from document repositories.
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +      operationId: getSingeObject
```suggestion
      operationId: getSingleObject
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +            JSON containing document retrieved from repositories.
```suggestion
            JSON containing document retrieved from repositories
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +            Given object_id is missing.
```suggestion
            Given `object_id` is missing
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +            JSON containing documents retrieved from repository.
```suggestion
            JSON containing documents retrieved from repository
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +            At least one object is missing.
```suggestion
            At least one object is missing
```

2020-12-02 16:30 UTC, USSAMOH2 commented on query-router/api.yml
> +            JSON containing documents retrieved from repository.
```suggestion
            JSON containing documents retrieved from repository
```

2020-12-03 09:29 UTC, luke-biel commented on docs/Architecture.md
> +CommonDataLayer is cloud targeted system, oriented into allowing **user** to ingest *any* data, sort it and retrieve, *raw* or *mapped*.
Well, technically, route to correct repo is what I mean

2020-12-03 14:27 UTC, smores56 approved these changes

2020-12-03 14:28 UTC, USSAMOH2 approved these changes

2020-12-04 13:12 UTC, Kononnable commented on docs/graphs/DataRouter-MessageIngestion.puml
> +@startuml
Isn't mentioned anywhere. I'm not sure if We should end up with going to same MQ we started - it suggest some kind of response to client.
Not sure if we should show message passing on per service basis - docs will have to be changed on each(even small)  PR with new features.

2020-12-04 13:12 UTC, Kononnable commented on docs/graphs/DataRouter-MessageIngestion.puml
> +@startuml
Applies to other files.

2020-12-04 13:12 UTC, Kononnable commented on docs/graphs/SchemaRegistry-Structure.puml
> +@startuml
Are views supported or is it a planned feature(not yet implemented).
Currently we've got something called view, but I don't think it supports multiple schemas(it would require some join-like logic).

2020-12-04 13:12 UTC, Kononnable commented on query-router/api.yml
> +openapi: 3.0.0
Can we somehow force this file to be up to date(to generate it on build/fail build if it's out-of-date?

2020-12-07 09:46 UTC, luke-biel commented on docs/Architecture.md
> +![./graphs/QueryRouter-DataRetrieval.puml](http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/epiphany-platform/CommonDataLayer/develop/docs/graphs/CDL.puml)
Our default branch is develop. We can switch to main, but intil this changes were there, develop would lack graphs (they would not generate). (I don't consider this a permament solution - we should generate them ourselves at some point)

Putting QS and CS with repo looked better. I'm open to change.

2020-12-07 09:53 UTC, luke-biel commented on docs/Architecture.md
> +We can distinguish 3 types of supported repositories:
I don't think we want to stand behind either of those until we test them. We can easily expand this list later.

2020-12-07 10:02 UTC, luke-biel commented on docs/Architecture.md
> +and is built in such way that it can support multiple databases (one at a time).
I mean, I've already changed this once, and I don't think changing `database` to `storage solution` brings a lot.

2020-12-07 10:10 UTC, luke-biel commented on docs/graphs/DataRouter-MessageIngestion.puml
> +@startuml
For now we use only one message queue (be it rabbit or kafka). Problem with this graph is, it's hard to make them readable and also carry valuable information. Adding duplicate of query in order to stress that's unique to other (when it doesn't have to be) would convolute drawing, in my opinion.

I say we should keep docs up to date on how services work or communicate. Some rough sketch always is welcome by developer just joining team. It's much easier to grasp flow by looking at uml than code. I disagree however, that we need to update everything in here (there's no cache for example).

2020-12-07 10:11 UTC, luke-biel commented on docs/graphs/SchemaRegistry-Structure.puml
> +@startuml
It's planned feature. Since object materializer is an existing topic, I've added it. That's how our system is designed to function in the end.

2020-12-07 10:12 UTC, luke-biel commented on query-router/api.yml
> +openapi: 3.0.0
We can add api tests to CI, and basing these tests on this file is fairly easy. But I see no option to generate a file out of warp/http.

2020-12-07 10:13 UTC, luke-biel commented on docs/Architecture.md
> +# Architecture of CDL
We did this case due to how github handles wikis. We can do whatever.

2020-12-08 03:55 UTC, esavier approved these changes

2020-12-08 09:11 UTC, frondeus approved these changes

2020-12-08 13:53 UTC, USSAMOH2 approved these changes

2020-12-08 13:53 UTC, USSAMOH2 commented on docs/getting_started.md
> +See [kubernetes_local_deployment]
This looks like a broken reference, as it has a different casing than the link below. Does this work?

2020-12-09 13:40 UTC, Kononnable approved these changes

2020-12-09 13:45 UTC, esavier approved these changes
nice

2020-12-09 13:49 UTC, frondeus approved these changes

2020-12-09 13:49 UTC, merged