Error reporting for materialization
epiphany-platform/CommonDataLayer pull request #663
Opened 2021-07-26 16:43 UTC by frondeus

2021-07-26 16:45 UTC, frondeus commented on .cdl/development/schema-registry.toml
> +import_file = "bare/setup/schema-registry/initial-schema.kafka.json"
We need a nice way to patch those entries on horust level, maybe using `patch`? Or creating a more sophisticated `overrides` mechanism?

2021-07-26 16:45 UTC, frondeus commented on .cdl/development/schema-registry.toml
> +import_file = "bare/setup/schema-registry/initial-schema.kafka.json"
For now either
```suggestion
#import_file = "bare/setup/schema-registry/initial-schema.kafka.json"
```
or
```suggestion
```

2021-07-26 16:46 UTC, frondeus commented on crates/partial-update-engine/src/main.rs
>  enum PartialNotification {
We could extract it into DTO and reuse in API, perhaps

2021-07-29 10:32 UTC, luke-biel commented on .cdl/development/schema-registry.toml
> +import_file = "bare/setup/schema-registry/initial-schema.kafka.json"
That's y I would prefer for everyone to create their own set of configs. I dunno, maybe Friday meeting will shed some light onto this. I'ma note that this is an use case.

2021-07-29 11:25 UTC, Kononnable reviewed
Looks like I forgot to press submit review button :|

2021-07-29 12:37 UTC, esavier commented on .cdl/development/schema-registry.toml
> +import_file = "bare/setup/schema-registry/initial-schema.kafka.json"
its problematic for horust deployment to have some additional steps before launching, config management left on user side is a problem since  you have technically have to make matrix consisting of (deployment * version * variant).
I was under the impression we will be able to make a directory with variants in the cdl repo so that we can patch it up against deployment automatically during the start.
I dunno, we will have to think something out.

2021-07-29 12:41 UTC, esavier reviewed
lets wait for comment resolutions

2021-07-30 08:20 UTC, smores56 requested changes

2021-07-30 08:20 UTC, smores56 commented on crates/object-builder/src/lib.rs
>      pub object_id: Uuid,
If this type has its own module, its definition should be moved there.

2021-07-30 08:20 UTC, smores56 commented on crates/object-builder/src/lib.rs
> +                        report_sender.clone().notify(error.as_str()).await?;
This seems fragile. What happens if we fail halfway through? If this is the desired behavior, maybe we should document our approach (both here and in our docs?).

2021-07-30 08:20 UTC, smores56 commented on crates/object-builder/src/lib.rs
> +    Pin<Box<dyn Stream<Item = anyhow::Result<MaterializedView>> + Send + 'static>>; // Why this cannot be Sync?
This comment should be removed before merging.

2021-07-30 08:20 UTC, smores56 commented on crates/materializer-general/src/lib.rs
> +    #[tracing::instrument(skip(self))]
Why do we skip `self` here and not in the above function? Because this one is `async` and the other one is not?

2021-07-30 08:20 UTC, smores56 commented on crates/materializer-general/src/lib.rs
>          let error_handler = |err| {
If all of these fallible components use the same error handler, they should maybe be wrapped in a better-named helper function or a `try` block. https://yaah.dev/try-blocks

2021-08-02 07:21 UTC, frondeus commented on crates/materializer-general/src/lib.rs
> +    #[tracing::instrument(skip(self))]
By `above function` do you mean `validate_options_inner`?

2021-08-02 07:30 UTC, frondeus commented on crates/object-builder/src/lib.rs
>      pub object_id: Uuid,
Okay, Ill rename module to `object_id_pair_serde`

2021-08-03 15:01 UTC, smores56 commented on crates/materializer-general/src/lib.rs
> +    #[tracing::instrument(skip(self))]
Yes

2021-08-03 15:24 UTC, frondeus commented on crates/materializer-general/src/lib.rs
> +    #[tracing::instrument(skip(self))]
Okay, then the answer is - not really.
First of all, you add `#[tracing::instrument]` to attach span to the function.
It does not matter whether it is a method (receiving `self` argument) or async (returns Future).

This span can be sent to, for example, jaeger so you can see when the function was called, how long it took, and what events were created (for example, `tracing::error!()` is one event, `tracing::info!()` is another.

This attribute macro also attaches context - each argument passed to the function is serialized into the span. Serialization usually is achieved by using the `Debug` trait.

Now, `skip(self)` means, `do not serialize self when you create a new span, ignore it` just like you can `serde(ignore)` field of the structure.

So the question should be - why are we not attaching span into `validate_options_inner`, and we do for `upsert_view_inner`. 

And the answer is - because we didn't have to. Validate options do not produce a single log (event); it is unused for now (it's a stub of future implementation), and we do not care right now how long it takes (recording span) because it is a stub after all.

`upsert_view_inner` on the other hand, takes some time (it writes to DB) which we would like to measure and see in jaeger, it generates at least one event (see line 149) which we want to link to this function, and therefore I attached `tracing::instrument` to it.

2021-08-03 19:24 UTC, smores56 commented on crates/materializer-general/src/lib.rs
> +    #[tracing::instrument(skip(self))]
Okay, thanks for the perfect explanation!

2021-08-03 21:21 UTC, smores56 approved these changes

2021-08-04 13:47 UTC, smores56 approved these changes

2021-08-04 13:47 UTC, merged