docs: rfc: Configuration Service
epiphany-platform/CommonDataLayer pull request #666
Opened 2021-07-27 10:28 UTC by esavier

fixes #224

2021-07-28 11:38 UTC, Kononnable reviewed
Didn't go with the review of each proposed solution yet. Some of my problems with them are related to other mentioned issues(e.g. security section). Just two questions about p2p solution for now.

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- allowing services to be configured by group or instance
Not sure I understand this one correctly.
I don't think we need the ability to configure 1 of 2 instances of DR to work in some way. It will always be all of DR instances or none of them(configuration by service group, not instance).

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- solution has to be neutral against deployment
This is something different from the last point from requirements or just a repetition to make sure everyone is aware of this?

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
I think this feature may be nice to have, but it's not really possible to implement without limiting users' deployment strategy in any way.

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
One of many options presented as the only solution. Not sure why those are the criteria you have chosen, they're probably the reason why some of the solutions below are marked as 'no security/no authentication' even though they provide methods for both(even HTTP protocol has authentication support https://datatracker.ietf.org/doc/html/rfc1945#section-11).

I'm not saying that just http basic authentication is enough, but the World Wide Web is fine with HTTPS and sending logins and passwords in plain text for authentication purposes.

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Integration with GraphQL or management panel has to be considered in later stages of the implementation to provide API for human end users.
Not sure if we should discuss it now or later on - our GraphQL API is user-centered. It has no admin configuration so far, so it may be wise to split admin configuration(e.g. topic names) from user ones(schemas, views).

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +[1](¯\_(ツ)_/¯)
(¯\_(ツ)_/¯)

2021-07-28 11:38 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
How does changing the value work in the proposed p2p solution: can any client change the value of data or only the owner(CFGS)? 
Can we scale CFGS service or it can only have one instance(one owner of data) but the load is spread over the network(only passive replicas are mentioned here)?

2021-07-28 12:53 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing proper authentication and authorization of configurations
2FA is authorization confirmation method, not authorization itself. In case of 2FA login for linux, pam is responsible for your authorization based on 2FA you provide.
in that case authorization is about admitting connection to do specific work, i.e. changing the configuration.

2021-07-28 12:53 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- configuration provisioning and configuration service should be abstract from the way CDL is deployed and should not limit deployment in any way.
requirements were checked with PO,
if you will do it against cdl that is supposed to work only on k8s then it won't work anywhere else.

2021-07-28 12:57 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing dynamic configuration
first version does not have to provide dynamic configuration, worst-case scenario it will be taken care of in the expansion of the initial CFGS, 
There are a lot of problems related to dynamic configuration, some of which are explored in depth in the document. Providing all cases and solutions for those, where dynamic config is problematic, would expand the document to twice the size.

2021-07-28 13:03 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- allowing services to be configured by group or instance
This is related to access groups.
There is for example deployment case where we have two different possesses and command services for those require different configs (so two groups of similar configs)

2021-07-28 13:04 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- solution has to be neutral against deployment
yeah this shouldn't be here

2021-07-28 13:05 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
it's how the p2p approach is doing things, that's why it's recommended.

2021-07-28 13:07 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
http authentication model is session authentication, which is not secure.
I believe that any kid with a keyboard can break this.

2021-07-28 13:24 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Integration with GraphQL or management panel has to be considered in later stages of the implementation to provide API for human end users.
This i am not sure how to tackle, so probably you are right, meeting is needed, but in worst-case scenario we will put second GraphQL service for that.

2021-07-28 13:25 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +[1](¯\_(ツ)_/¯)
because there are changes in the rfc naming etc, its waiting

2021-07-28 13:29 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
1. no, clients, can report their change (which is not described in this document). In first release, CFGS is a source of Truth. 

2. it can make replicas, both passive and active, so spreading the load is possible, although some code will be required. Replicas do not replicate automagically, but there is a basic consensus mechanism available. Load can be spread across instances if needed.

2021-07-29 11:45 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing dynamic configuration
Even if the first version is not required to provide dynamic configuration, but it will be required later on I don't think we should choose technology that doesn't allow it. Otherwise, we would have to rewrite the configuration service completely then.

That's why I don't think this requirement is optional for choosing technology behind the CFGS even if it's optional for the first version of the service.

2021-07-29 12:07 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing proper authentication and authorization of configurations
2FA is 'part of' Multi-factor authentication, it's about authentication, not authorization.

It can be treated as a confirmation method, but it doesn't change the fact that it's part of the authentication process, so if we want to take care of authentication we also have to decide if we support 2FA, what authentication methods do we support, etc.

2021-07-29 12:13 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- allowing services to be configured by group or instance
Access groups as described some time ago allows for multiple tenants to share the environment and resources. It doesn't start a separate set of services for each tenant, it uses application logic to serve multiple tenants in a single service instance.

What you're referring to sounds like two separate CDL deployments sharing single configuration service.

2021-07-29 12:24 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
I think we're supposed to choose the best option for CDL. I wouldn't say everything about how p2p works will work well for CDL.

And I think it doesn't change the fact that implementing high-level service management is impossible without limiting user deployment strategy - which is marked as a hard requirement earlier in the document.

2021-07-29 12:29 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
WWW currently uses multiple authentication models and most of them are not classified as insecure. This paragraph suggests that only using described method provides enough security for CDL which I don't think it's true and using this specific authentication model may not be a requirement when it comes to CDL security.

2021-07-29 12:34 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
Ok, so if it is either a multi-leader or a leaderless approach how is the problem of split-brain handled?
We cannot allow data corruption or data inconsistency here, so the resolution of the split-brain problem may be critical here.

2021-07-29 12:34 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +[1](¯\_(ツ)_/¯)
I don't think any changes will affect your branch unless you merge them in(and fix the link then).

2021-07-29 12:45 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing dynamic configuration
As an item, it is optional, but i know and i do agree that taking a path that prevents this to be implemented somewhere will be problematic. 
I will confirm with @pljadru if its okay.
I can also rephrase it if its okay (i.e. rename the section, but i do not know how thought) or make a comment.

2021-07-30 08:48 UTC, smores56 requested changes

2021-07-30 08:49 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +It is a mutation of the previous method. Server is a custom service that serves configuration in request-response model. Additionally, the server can support both mutability and notifications. Servic
It isn't the method directly above, so I would say "It is a mutation of the above (or aforementioned) method" instead.

2021-07-30 08:51 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +-- Second option means that Server will act as a client and Client will act as a server. Configuration service will send the notification to servers that will look like a simple request with all nece
This is not being rendered properly as a sub list by GitHub. You should use `  - ...` instead. (2 spaces in front)

2021-07-30 08:52 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +In this section, libp2p was taken into consideration as way-to-go library. P2P network can alleviate most of the programmer-side issues that are explained in previous section, while providing transpa
Transparent what? Did you mean to say transparency here?

2021-07-30 08:56 UTC, smores56 requested changes

2021-07-30 08:56 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +-- Services are building the network automatically and keeping only few connections to nearby peers, building a "mesh".
Again, please use GitHub-compatible sub lists.

2021-07-30 08:56 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- lot of work initially
I'd say that even more negative than the initial front-loading of work is the issue that we don't know how long this will take. Should that be mentioned here?

2021-07-30 08:56 UTC, smores56 commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
To opt out is to choose not to do something. You probably meant opt in (to choose an option with what it entails).

2021-07-30 09:01 UTC, smores56 commented
I like this document, and think that most of my discussion points with it will be relevant when we meet to discuss it, more so than now, where I have mainly only seen minor grammar issues. Good job!

2021-08-02 12:17 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing proper authentication and authorization of configurations
Authorization is idea that is kind of larger than authorization itself, if we are talking about users, there is no proper authorization without authentication, and there is no reason for 2FA for authentication itself. 
Here we are talking about message authentication inside the deployment, not really about outside, user-facing security since we do not have this defined yet, additionally user-facing security will depend on the implementation which first have to be chosen. From my understanding, if we assume graphql, then there is not really much we can do, if a different approach is taken, then there are few options, however this document does not take any assumptions on that. 

For libp2p solution, internal security is given out of the box, with exclusion to authorization, for other solutions it has to be planned and implemented when the time for it comes.

2021-08-02 12:42 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
what is tackled in the paragraph is security on top of the transport layer inside cdl, as configuration changes can not be accepted from malicious services running in the same stack. User security is not described but its also out of the scope. It will be designed when there is time for that. Currently, there is only a need to have a place for it or. 
libp2p just delivers most of it out of the box, without testing nor explicit implementation from our side.

2021-08-03 07:32 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
you gave nothing to support your argument, this comment is so vague i do not how or what should address  here

2021-08-03 07:33 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +[1](¯\_(ツ)_/¯)
thanks dad, for telling me how to merge my things

2021-08-03 07:38 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
the same way as in any other solution,
if you interested in details, go and read either documentation or spec of libp2p, and you will know how to handle this

2021-08-03 07:50 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +It is a mutation of the previous method. Server is a custom service that serves configuration in request-response model. Additionally, the server can support both mutability and notifications. Servic
in high level i think it is, you are still serving static data over an endpoint with req-response model. How and in what server is written is completely secondary, may it be bash, nginx, zig or rust. Only difference in here is that some kind of mutability is preserved which in case of nginx can not

2021-08-03 07:52 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +In this section, libp2p was taken into consideration as way-to-go library. P2P network can alleviate most of the programmer-side issues that are explained in previous section, while providing transpa
yeah, i tried to do this as fast as possible, i read this through twice but i missed few things,
i wanted to write "transparent communication channel"

2021-08-03 07:57 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- lot of work initially
we have PoC working separately, i think we gauged pretty neatly how much work we have to put in this,
1. [done] make req-resp work
2. [done] test req-resp
3. test req-resp + pub-sub
4. wrap it in the coherent module (*)
5. implement handlers for services (*)
6. implement configuration exchange proto (*)
7. implement synchronization (**)
voila

* can be done partially, i.e. mvp at this time and expanded later
* can be done when scaling is requested

2021-08-03 07:57 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- lot of work initially
also by a lot i do not mean "a lot", rather "a lot more, but its not so terrible"

2021-08-03 07:59 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
> 
> 
> I like this document, and think that most of my discussion points with it will be relevant when we meet to discuss it, more so than now, where I have mainly only seen minor grammar issues. Good job!

Thank you very much, I worked really hard on this  ❤️ 😁

2021-08-03 08:00 UTC, esavier commented
> I like this document, and think that most of my discussion points with it will be relevant when we meet to discuss it, more so than now, where I have mainly only seen minor grammar issues. Good job!

Thank you a lot, i put a lot of effort in this ❤️

2021-08-03 08:58 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing proper authentication and authorization of configurations
So what exactly is the optional requirement here? 
Safety of internal messages (e.g. configuration changes propagation) not the safety of user requests to change config value?

If so this should be clarified in the document.

2021-08-03 09:04 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
Again, it's not about specific proposed technology(libp2p), it's about what we require from any solution. If it's a description of libp2p it should go into its section.

For other technologies, different 'verification protocols' may be used if they provide enough security. We're not limited to using private keys.

2021-08-03 09:09 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
Different solutions use different methods, there is no silver bullet here. Some solutions even don't have this problem at all - they always have a single source of truth(but do not qualify for high-availability standards).
It's important as sometimes the split-brain problem is not handled at all on the protocol level, or is handled in a way that doesn't provide guarantees needed for configuration service.

I think this document is supposed to help to decide which way we want to go without everyone getting into specs of each proposed technology.

2021-08-04 08:43 UTC, Kononnable commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
I'm just saying that if `the choice of solution should be influenced by its possibility to support that feature` then we should not say it's recommended to do this way because one of the solutions is doing it this way. We're here to pick a solution, not to argue why we choose a specific one(the decision was not made yet).

Anyway, we got off the topic here. Original problem was that operations like restarting services on-demand are something that cannot be done without limiting users' deployment strategy - which is specified as a requirement.

2021-08-06 09:35 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing proper authentication and authorization of configurations
okay, i can stand behind that

2021-08-06 09:38 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- allowing services to be configured by group or instance
technically AG doe not have proper rfc yet, we only had a sketch of the functionality. 
Technically we may have different (abstract) groups with different functionalities and access levels, its not clear yet. That means we will have to change properties per group not per type of service.
i.e. type of service does not match 1:1 with group, or for example we may have two postgres instances with different functionalities enabled.

2021-08-06 09:46 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
i kinda disagree, we can restart the services both on baremetal and on container management platform, which are two, most basic ways to deploy the CDL. Other options, like istio or linkerd are variants of the second approach. 
In case of both deployments, the easiest way would be to gracefully exit the application, and reload with new config, and this is possible both in case of baremetal with proper functionalities (like proper systemd service file) and with container mangement.

2021-08-06 09:51 UTC, Kononnable commented
Discussions about requirements were clarified(solved or we know what exactly we have problems with), so it's probably a good time to add more solutions to choose from.


## File configuration instead of adding another service:
Actually, this idea was proposed a long time ago. Its core is that we put all of our configuration data into files. Single service can read from multiple files or all services reads the same big file(it's up to us on if/how we want to split configs, probably some splitting is a good idea to keep deployment setting separate from settings related to user application). Services watch for file changes(inotify) and act on them when files get changed(detect changes and apply them). We(as CDL) don't really have to care how files are replicated over the network however, we should provide some default options. In custom deployments, it's up to the ops team to decide which way of file synchronization is good for them(based on the requirements for that deployment - e.g. time for all services to read new config).
For k8s deployments, we can simply use config maps/secrets(if we assume CDL admin will have direct access to k8s) or use sidecars to fetch/synchronize files in a different way. Those sidecars can be custom-made for deployments which gives a lot of customization and flexibility for end-users(users can define the ultimate source of truth). We can add a new service on top of that configuration propagation if we need more programmatic API for configuration service or we want to validate configuration before it is applied.

One rough thing about this approach is configuration validation. With a file-based approach, configuration can't be validated at the moment of the change(we can't deny the change if the configuration is not valid). Services would have to know how to act when the configuration is corrupt - report errors and continue working on the older version. This approach would work well on already existing services(including service restarts) but is hard to achieve with instances created once invalid configuration is set(e.g. automatic scaling). 
To migrate the risks we can ask CDL admins to validate the configs before pushing them(config file validation is already planned as part of #567) and watch for reported errors after the change.
As for k8s, we can write a simple operator which job would be to validate the configuration settings and propagate them(update config maps) or utilize a separate new service mentioned earlier. This will not disrupt CDL's ability to scale if someone provides the wrong config file(the whole CDL would be running under old configs).

Pros:
- easy to implement/setup
- simplicity
- dynamic configuration
- secure(attacker needs direct access to k8s or depends on user-specific synchronization method)
- no split-brain problems - unless the user use a synchronization method that is vulnerable to this problem(not likely)
- customization and flexibility - users can completely change the behavior of 'config service' if they need to(they can easily add custom logic on top of that, use different source of truth), with other mentioned solutions that would require changes to CDL code
- no real resource runtime costs(default synchronization method uses k8s(etcd)/docker volumes/filesystem to propagate changes - no runtime costs of listening for change events)

Cons:
- configuration change is async(same as with others mentioned methods so far) - user has to manually check logs to see if configuration change was successful
- lack of configuration validation check on saving the new configuration


## Central service:
Each CDL service connects to a single(or replicated) configuration service and keeps the connection open(e.g. WebSocket). Configuration service provides API to end-user - it's up to us to decide if that should be REST/GRPC API or e.g. changing values stored in pg should be enough to trigger the change. Configuration service on change request validates new data and pass configuration change event to interested services. 
In theory configuration service may be seen as a single point of failure, however in this case it shouldn't be a big problem:
- K8s or other deployment methods can easily decide if service is unresponsible and restart it if necessary. Downtimes shorter than a minute are not problematic for configuration service as it's not serving the users directly.
- If any CDL service loses the connection to configuration service(e.g. network problems) it can still work and try to reconnect in the background. We may want to introduce a configuration parameter to stop the 'unresponding' service from working if it cannot connect with the configuration service for a specific amount of time(to make sure we're not running any service with old config).
- We can add replication to configuration service(raft or similar protocol) so even if one instance is unresponsible clients will be able to connect to another one thanks to load balancers

Pros:
- easy to implement/setup
- dynamic configuration
- automatic configuration validation
- secure(we are free to decide on the usage of any authentication/authorization protocols)
- no split-brain problems - configuration service(or its database) is a single source of truth, in case of replication we can use any protocol which handles that problem well(e.g. raft)
- configuration change can be sync(in case of REST/GRPC we can delay sending the response until all connected services acknowledge the change) - nice error reporting for scripting purposes(no need to check logs)
- small runtime resource costs - WebSocket and similar protocols have low resource costs, a single configuration service instance can easily handle thousands of connections(and it's unlikely that CDL will be scaled in thousands)

Cons:
- theoretical single point of failure(described earlier)

2021-08-06 09:54 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Additionally, the payload have to be protected by hash authentication code (i.e. AES-GMAC) in the future. This is the mechanism that protects both the message and its hash with control sum, which is
all kinds of security protocols will boil down to either symmetric encryption or asymmetric one. I think its a little to much to describe diffie-helman key exchange mechanism or different symmetric keys here. If its still the TLS you are drinking to, its a combination of both symmetric and asymmetric encryption wrapped inside a specific mechanism, problem with that is that we will have to provide proper certificates and certificate authentication mechanism to consider together with TLS wrapper itself. Technically TLS will work with CFGS and it covers the requirements, but its very problematic for local network, and that's why i did not propose it as a solution.

2021-08-06 10:03 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +### P2P network
libp2p protocol provides message identification mechanism, i.e. you can define which message happened first, additionally it provides a way to keep the knowledge about the last n messages on protocol level. Consolidation have to be implemented, as in any other approach, but we have consensus and knowledge about all the messages in proper order. It behaves literally the same way as a message queue system. 
On first stage consolidation does not have to be implemented, in case we want it to scale at some point, we will have to do that, also with libp2p (unless we will go with kademlia model which is not described but also a possibility).
Desynchronization of states is therefore not handled on protocol level. The protocol only provides facilities to implement it since consistent state is easy to achieve using limited network broadcasts. 
Thats why i deemed it not a problem for now, and that is also why i advised to read a specification of the protocols, it is really nice lecture to have.

2021-08-06 10:49 UTC, esavier commented
i am not sure but its amost the same i wrote on solutions 1 and 2, although with greater emphasis on it ?

2021-08-06 11:04 UTC, Kononnable commented
Yes, using files for configuration is similar to the first two approaches. However, because of differences(and some generalizations with different 'defaults'), most of the negatives are no longer valid or even converted into positives.

Central service is similar to the rest server approach, but again the more detailed design of some aspects allows to migrate most of the negatives.

2021-08-06 11:44 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +-- Services are building the network automatically and keeping only few connections to nearby peers, building a "mesh".
done?

2021-08-09 09:15 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing proper authentication and authorization of configurations
Do you mean access groups by this?

2021-08-09 09:16 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing dynamic configuration
Literaly first sentence of this paragraph mentions this. It is confusing

2021-08-09 09:21 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
What have notifications that are sent by CS and ER to do with this+

2021-08-09 09:22 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
```suggestion
High level service management is something that's not utilized yet, but it may be necessary to provide it in the future. The simplest example of which is to restart the service on demand by operator (administrator, for example). Such behavior is not required right now, however the choice of solution should be influenced by its possibility to support that feature in the future.
```

2021-08-09 09:23 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
```for example when service will crash and restart with different port``` k8s handles that

2021-08-09 09:24 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
```High level service management is something is not utilized yet``` well, we have some guards on k8s level that restart service on death, if that's what you mean.

2021-08-09 09:25 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +In context of this document, we will only discuss protocol security inside cdl network. User facing security features are ommited, but solution have to provide space for its implementation. We need t
User facing security features?

2021-08-09 09:28 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +Various security options have to be explored for future use. Authentication and authorization are both related to the general security (and as such to the nature of configuration service), and to sep
This again assumes PUSH

2021-08-09 09:32 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +-- secret used to identify the permissions of the client
I'm not sure this is method of authentication we want to follow on with. Such authorization is inflexible.

2021-08-09 09:36 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- solution has to provide api that is permissive to 3rd party services which may be written in different languages.
This, kind of, contradicts line 115: ```Configuration Service will be treated as an internal API and changes to it will not be considered breaking change.``` Not directly, but if we assume we are providing this api, we need to defend clients from breaking changes.

2021-08-09 09:38 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +Configuration is accessible as a URI tree served by static server. Configuration is immutable, and lives as long as the deployment (i.e. in case deployment have to change, everything is scrapped and
Even simplier would be k8s config mapping, as it's already present (but it'd limit us from bare metal deployments)

2021-08-09 09:39 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- heavy load on the server in case of large deployments
load balancer?

2021-08-09 09:39 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- it will be increasingly harder to implement further features upon this solution
why?

2021-08-09 09:40 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- immutable
if server serves files, then we can easily modify these files in some cases, which allows for some mutability.

2021-08-09 09:41 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- no authentication
I believe there are nginx plugins for jwt

2021-08-09 10:00 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +
I miss exploration of existing solutions.

There's zookeeper, which we already have deployed on our clusters https://zookeeper.apache.org/.

There's whole topic of cmdbs (second link sends us to some ranking):
https://www.servicenow.com/products/it-operations-management/what-is-cmdb.html
https://www.capterra.com/cmdb-software/?pricing_options=%5B8%5D&sortOrder=sponsored
https://www.dmtf.org/standards/cmdbf. But I guess we strive only for parts of the functionality.

2021-08-09 10:02 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
One problem I see, with requirements we specified our clients have to be able to easily plug in, and with libp2p req-response it may difficult. It wasn't explored in this rfc.

2021-08-09 10:48 UTC, frondeus commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
> What have notifications that are sent by CS and ER to do with this?
I think this paragraph does not mention notification reports sent by CS/ER/MG but notifications that "hey, configuration XYZ changed"

2021-08-09 10:54 UTC, frondeus commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing dynamic configuration
Perhaps we want to express that "dynamism" is in our goal but can be deferred in stage 2?

2021-08-09 10:55 UTC, frondeus commented on docs/rfc/0020_Configuration_Service_01.md
> +- solution has to provide api that is permissive to 3rd party services which may be written in different languages.
I think this might be connected to #636

2021-08-09 10:57 UTC, frondeus commented on docs/rfc/0020_Configuration_Service_01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
I know that libp2p is a young concept but it seems to be supported by many languages and companies: https://blog.ipfs.io/2020-06-09-libp2p-in-2020/
Is this really a problem?

2021-08-09 11:12 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing dynamic configuration
Yeah, we even agreed to this, but it's not mentioned in rfc and well, it is confusing. First sentence describes ConfS as dynamic config provider.

I'd just change that.

2021-08-09 11:12 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
Hmm, then it's not clear enough, we should change wording

2021-08-09 11:13 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +- solution has to provide api that is permissive to 3rd party services which may be written in different languages.
Hmm, may be related, yeah.

2021-08-09 11:15 UTC, luke-biel commented on docs/rfc/0020_Configuration_Service_01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
It's not a problem per se - but I think it's good to note how are we gonna approach interchangeability of our services with this change - as a note for future readers. (also, probably we should decide what is the prio on making it easy to reimplement)

2021-08-09 11:51 UTC, Kononnable commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing dynamic configuration
I think the decision on which way we should proceed should include dynamic configuration as a requirement.
It's fine if we don't implement it for now(delay implementation of 'dynamic part'), but the design and chosen technologies should allow for it to be implemented. Otherwise, we would have to do all the work from scratch.

In other words - we can delay implementation, however, design decisions should not block future implementation. If we're sure right now that dynamic configuration will be a feature later on we have to make design decisions with this feature in mind. 
As those are requirements for design, not the implementation I agree that this point should not be marked as optional.

2021-08-09 12:03 UTC, Kononnable commented on docs/rfc/0020_Configuration_Service_01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
Based on that article(I didn't do research on the current state):
Support for
- go
- js
- rust
- cpp
- py
- jvm

Not all major language families are covered here(e.g. dotnet). As for Python and JVM implementations are marked as heavy work in progress and are not recommended to be used in production.

Is it a big problem? Hard to say, probably no one will be interested in implementing theirs custom CDL components for the time being. However, this is a risk for the future to be at least acknowledged - the current state of some of those libraries is not good and there is no guarantee that they won't be just abandoned.

2021-08-09 14:25 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
todo : clarify

2021-08-18 05:29 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- configuration provisioning and configuration service should be abstract from the way CDL is deployed and should not limit deployment in any way.
fixed in next commit

2021-08-18 05:29 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- providing dynamic configuration
also fixed in next commit, resolving

2021-08-18 05:36 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +Integration with GraphQL or management panel has to be considered in later stages of the implementation to provide API for human end users.
yeah, we discussed that and it appears that there  are options to secure the access for users. Therefore I am marking this as resolved :)

2021-08-18 05:36 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +[1](¯\_(ツ)_/¯)
removed altogether, changed whole footnotes

2021-08-18 05:37 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +-- Second option means that Server will act as a client and Client will act as a server. Configuration service will send the notification to servers that will look like a simple request with all nece
i think i resolved this ?

2021-08-18 05:37 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +In this section, libp2p was taken into consideration as way-to-go library. P2P network can alleviate most of the programmer-side issues that are explained in previous section, while providing transpa
also fixed :)

2021-08-18 05:37 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +- lot of work initially
done?

2021-08-18 05:38 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
fixed !

2021-08-18 06:45 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +While notifications are optional, its availability can influence deployment's behavior. For example, in case of lack of dynamic configuration, the whole deployment will have to be reset and started a
done in new update

2021-08-18 06:49 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing proper authentication and authorization of configurations
no, there are two security features described, configuration tags, and protocol security. Access groups are mentioned elsewhere in the document (look for tags, it gives a gist of what i ment).
cfgs is so important that i want to prevent configuration from malicious services being pushed, so we need to authenticate the configuration message and confirm its source (mitigate mitm attacks for example)

2021-08-18 06:51 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- providing dynamic configuration
sorry, yeah i fixed that,
I meant something else under "optional" in that case

2021-08-18 06:53 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +High level service management is something is not utilized yet, but may be necessary to provide it in the future. The Simplest example of which is to restart the service on demand by operator (admini
this is for now a result of implementation. Currently we have to kill stuff to reconfigure it in 80% of cases, but there will be different management options later, like switching access groups etc. that will require only permission updates and not necessarily killing stuff.

2021-08-18 06:54 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +In context of this document, we will only discuss protocol security inside cdl network. User facing security features are ommited, but solution have to provide space for its implementation. We need t
its the api that faces user, whatever its grpc, graphql or rest, its different from service side, it requires proper user authorization etc.

2021-08-18 06:56 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +-- secret used to identify the permissions of the client
those are components of the authorization and its only on protocol level.
how user is authenticated/authorized is different thing not in the scope of this document (we do not care right now about it tbh). We need to ensure that config we are getting is not malicious or from malicious source. Thats all. I updated the doc with examples.

2021-08-18 06:58 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- solution has to provide api that is permissive to 3rd party services which may be written in different languages.
agree, but yeah, tackled in 636,
does it resolve it?

2021-08-18 07:01 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +Configuration is accessible as a URI tree served by static server. Configuration is immutable, and lives as long as the deployment (i.e. in case deployment have to change, everything is scrapped and
as written, different tools may be used, nginx, etcd, k8s, even nfs share if someone feels adventurous :D
honestly, i wrote simple tcp server using bash and netcat back in the days and it also should work. This is a concept, not a specific solution. There are so many options that it would require yet another rfc, probably.

2021-08-18 07:05 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- heavy load on the server in case of large deployments
i removed it after reading what konon wrote. 
This is hard to graps but this is not concrete solution, whats common is that we have central server that will have to take care of all of the requests. I do not know if load balancer can help since its a mapper from one to many, where one is requester and many is server (chooses the most under loaded instance). In case of single central server we need to make a lot of optimizations on the request part of the services, especially that there are no notifications about changes and no fine-tuning from top to bottom. only clients can be optimized here.

2021-08-18 07:08 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- it will be increasingly harder to implement further features upon this solution
again, depends on the solution, but for example if we will go with the simplest solution of sharing file directory, there is initially no way of preventing unauthorized access to the configuration, everyone may read everything. There is also no way of assigning specific pools to specific groups i.e. i won't be able to say, i want from pool of 10 DRs for only 3 of them to serve cold-storage and the rest to work on hot-storage etc. More advanced features usually needs more stable and advanced groundwork to already be there, so simple solutions, while providing MVP faster, will make it harder to expand upon.

2021-08-18 07:09 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- immutable
yeah but it requires restart of for example k8s deployment. 
what you describing is written in second part, "Central Server"
also what you mentioned is reflected by large maintenance score, since there will be a lot of manual work with this

2021-08-18 07:12 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- immutable
mutability with static server requires from us something like secondary service that will interact with this static server, and this is the same as central server with extra steps

2021-08-18 07:12 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +- no authentication
again, no user auth, only protocol security.

2021-08-18 07:13 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +
next update will have this, i need to read some of this stuff :)

2021-08-18 07:16 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +I, personally, would opt out for libp2p solution, as the investment seems to be worth it. The amount of work required is quite high, however it can be treated as an investment, since after initial fe
libp2p in rust is very stable and used by many projects,  although for neferious resons (damn those blockchains) so i wouldn't worry about it,
for the most basic functionality we just need req-response endpoint to be there and even incomplete libp2p implementations have this
worst case scenario the service will ask for config over graphql api or "user-facing" api, whatever we decide it to be

2021-08-18 08:06 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +
about zookeeper, its coordination tool, not configuration, and should not be used as one. There a lot of problems regarding zookeeper but before all of this, it's just not the purpose of this tool to provide initial configuration. For this purpose, a better choice would be simply redis instance. 
Zookeeper works literally from outside perspective and in our case also, will look like a KV database with extra steps. Usually Zookeeper is used not as configuration provider but discovery service and communication bus though. Even for Kafka its used (past tense, kafka is leaving zookeeper ecosystem) in 4 places and only one is configuration (and even in this case its partial) : leader election, broker discovery, ACL, and topic configurations. Even Kafka's configuration is not maintained inside zookeeper.

2021-08-18 08:08 UTC, esavier commented on docs/rfc/0020_Configuration_Service_01.md
> +
As for the CMDB, yes its a configuration service specification but for organizations, i.e. keeping track of inventory and other boring stuff. If you find the documents its literally CDL on very low-grade crack :D

2021-08-20 14:09 UTC, frondeus approved these changes

2021-08-20 14:09 UTC, frondeus commented
I Will merge it in next 2 hours if there are no objections

2021-08-23 07:30 UTC, esavier commented on docs/rfc/CDLF-0000F-00-rfc-01.md
> +It is a mutation of the previous method. Server is a custom service that serves configuration in request-response model. Additionally, the server can support both mutability and notifications. Servic
okay, its solved from my udnerstanding ?

2021-08-23 07:33 UTC, merged