WIP: Clean RFC and docs
epiphany-platform/CommonDataLayer pull request #667
Opened 2021-07-27 14:45 UTC by frondeus

* [ ] All already existing RFC have human readable filenames
* [ ] All already existing RFC have ordering number assigned
* [ ] ENV variables from `architecture` chapter are removed
* [ ] `features/materialization.md` is moved into `examples` directory
* [ ] `features/index.md` is updated
* * [ ] update Guidelines section
* * [ ] update links to RFCs
* * [ ] update feature list - check if all items mentioned there are in fact separate features, check if there are any missing items (e.g. defining if materialization is a single feature or this term covers multiple features, if so define those features)
* * [ ] update feature internal list (confluence)
* [ ] `SUMMARY.md` is updated
* [ ] `processes` directory is created
* [ ] `processes/index.md` is created
* [ ] All processed based on RFCs are created and indexed

As for ordering number I propose:

| Ordering number | Last update date | Title                                                  | Feature ID | 
|-----------------|------------------|--------------------------------------------------------|------------|
| 0001            | 2021/02/11       | Alternative communication method to Kafka and RabbitMQ | 0000C      |
| 0002            | 2021/02/11       | Materialization                                        | 00011      |
| 0003            | 2021/02/17       | Usage of Message Pack format as CDL input              | 0000E      |
| 0004            | 2021/03/17       | Commit message formalization and enforcement           | NAF        |
| 0005            | 2021/03/19       | CDL Ingestion API versioning                           | 00010      |
| 0006            | 2021/03/19       | Edge registry                                          | 00012      |
| 0007            | 2021/03/19       | Materialized views                                     | 00013      |
| 0008            | 2021/05/17       | CDL publishing deployment configurations               | 00015      |
| 0009            | 2021/06/14       | CDL Ingestion API versioning - changes to the format   | 00010      |
| 0010            | 2021/06/24       | Schema-Registry-less CDL deployment                    | 00016      |
| 0011            | 2021/06/30       | Branching strategy                                     | NAF        |
| 0012            | 2021/07/01       | CDL documentation generation                           | NAF        |
| 0013            | 2021/07/02       | Documentation restructure and RFC process              |  NAF          |
| 0014            | 2021/07/06       | Query raw routes                                       | 00017      |

Fixes #645

2021-07-28 09:34 UTC, frondeus commented
I think cleanup in features/index.md can be done in separate PR

2021-07-28 11:46 UTC, esavier approved these changes

2021-07-29 06:34 UTC, esavier commented
i can merge it, is it done?
if so, clean up tasklist.

2021-07-30 09:23 UTC, smores56 requested changes

2021-07-30 09:23 UTC, smores56 commented on docs/SUMMARY.md
> +    - [0021 - Development process]()
Why put them in reverse order? Wouldn't chronological order make more sense?

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0001_Commit_message_formalization_and_enforcement.md
> +# Commit message formalization and enforcement
Generally, I prefer title case when writing headers in MD documents. https://www.grammar-monster.com/glossary/title_case.htm
In this case, it would be:
```suggestion
# Commit Message Formalization and Enforcement
```

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0001_Commit_message_formalization_and_enforcement.md
> +# Commit message formalization and enforcement
And in the rest of this document, that would be preferable. If not possible, I'm amenable to deciding on a different, but consistent standard.

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0002_Branching_strategy.md
> +=========================================================
This looks nice, but is an unconventional way of embedding notes in MD documents. I usually see a:

_Note: A (tl;dr)[#tl-dr] is available at the end of this document._

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +architecture
Consider using title case here.

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +It does not contain information about a single component (its current state, as this is the purpose of `architecture`).
This seems like a more specific way to inform the reader that our intended usage of RFC's (in the context of the CDL and its development) is design changes, and that we aim to avoid implementation-specific details when possible. Does that seem more useful to you, or would you rather keep it as is?

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +Each RFC must contain a deadline to speed up the process.
This implies that the deadline should be embedded in the RFC itself. Can you mark where the deadline should be recorded, or at least that it shouldn't be done in the RFC itself?

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +The author of the RFC should create a new document in the `rfc` directory. This directory has a flat structure, and each RFC should have a filename in human-readable format with RFC ordering prefix n
Is there a strict requirement of a minimum of 4 digits? That doesn't seem to be notated anywhere, which technically leaves it ambiguous.

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +CDL feature ID is required only for the feature description. If RFC describes the process, this field should be omitted.
```suggestion
CDL feature ID is only required for feature descriptions. If the RFC describes a process, this field should be omitted.
```

2021-07-30 09:23 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +* When abandoned - RFC should be updated with `Abandon reason`.
Should this section go at the bottom or the top? Bottom leaves it away from the content, not distracting the reader, whereas the top is a good place to inform the reader of the status quickly, like an archived banner on an abandoned GitHub repo.

2021-08-02 07:43 UTC, frondeus commented on docs/SUMMARY.md
> +    - [0021 - Development process]()
The question is what RFC you would want to read first.
Chronological order makes sense for a newbie, who is still learning about CDL.
For the rest - you probably would want to see the latest changes or the future design of CDL than some old RFC from 2 years ago.

It is the same reason why you make CHANGELOG.md with the latest released version on the top.

2021-08-02 07:44 UTC, frondeus commented on docs/processes/0002_Branching_strategy.md
> +=========================================================
This is literally a copy from RFC that you created. I don't mind further changes, but should it block this PR?

2021-08-02 07:45 UTC, frondeus commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +architecture
In that case `architecture` means directory, and directory in Linux world is case sensitive.

2021-08-02 07:48 UTC, frondeus commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +It does not contain information about a single component (its current state, as this is the purpose of `architecture`).
Implementation details are fine, but this sentence was written to resolve an issue if we should keep `RFC describing what Object Builder or Materializer General is`. And the answer is "no - if we need to describe whats the current state of the already existing component then we should simply create document in `architecture` directory. Object Builder is not a feature, Materialization is"

2021-08-02 07:52 UTC, frondeus commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +Each RFC must contain a deadline to speed up the process.
The content of this process is based on the already accepted RFC. I understand that there is always room for improvement, but maybe we should create another issue to review and clarify all comments regarding the content of these processes?

The purpose of this RFC was to organize documents, and not necessarily change the content.

Regarding your question:
Deadline is included in RFC itself, see line 95

2021-08-02 09:47 UTC, esavier commented on docs/SUMMARY.md
> +    - [0021 - Development process]()
i think it does not matter to be honest, its not like a 10k lines list

2021-08-02 09:48 UTC, esavier commented on docs/processes/0001_Commit_message_formalization_and_enforcement.md
> +# Commit message formalization and enforcement
smarter every day 
this is good, i like it.

2021-08-02 10:02 UTC, esavier approved these changes

2021-08-02 11:31 UTC, esavier commented on docs/processes/0001_Commit_message_formalization_and_enforcement.md
> +# Commit message formalization and enforcement
lets fork this as an issue for the rest of the docs, and just apply this for the current docs, the rest will be fixed in another issue

2021-08-02 11:42 UTC, esavier commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +* When abandoned - RFC should be updated with `Abandon reason`.
only `abandon reason` or the whole section ?

2021-08-02 11:46 UTC, esavier approved these changes

2021-08-02 11:56 UTC, esavier commented on docs/SUMMARY.md
> +    - [0021 - Development process]()
okay, i am solving it, since its mostly about cleaning docs not review of the rfc itself :)

2021-08-02 11:57 UTC, esavier commented on docs/processes/0001_Commit_message_formalization_and_enforcement.md
> +# Commit message formalization and enforcement
solving it with the same intent, fixes goes to another separate issue

2021-08-02 11:57 UTC, esavier commented on docs/processes/0002_Branching_strategy.md
> +=========================================================
needs clarification, do we need to move whole section or only this line, because if this line only then i am against it

2021-08-02 11:58 UTC, esavier commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +architecture
as a quick fix, please apply this to this and similar entries, and we are done over here :)

2021-08-02 11:59 UTC, esavier commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +It does not contain information about a single component (its current state, as this is the purpose of `architecture`).
simple rewording (clarification to the doc) proposed, besides that its closed
about Sam's issue, its not about the rfc discussion, only cleaning up,

2021-08-02 12:00 UTC, esavier commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +Each RFC must contain a deadline to speed up the process.
solved

2021-08-02 12:01 UTC, esavier commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +The author of the RFC should create a new document in the `rfc` directory. This directory has a flat structure, and each RFC should have a filename in human-readable format with RFC ordering prefix n
clarification accepted, 
@frondeus, please resolve when ready

2021-08-03 07:28 UTC, frondeus commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +
> When abandoned - RFC should be updated with `Abandon reason`.

2021-08-03 07:29 UTC, frondeus commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +
Maybe it needs to be more explicit? `Abandon reason` in Front Matter (top of the document)

2021-08-03 14:19 UTC, smores56 commented on docs/processes/0002_Branching_strategy.md
> +=========================================================
We can leave it as-is. This was created by Matthew, which is why I was surprised, but it works.

2021-08-03 14:22 UTC, smores56 approved these changes

2021-08-03 14:24 UTC, smores56 commented on docs/processes/0003_Documentation_structure_and_RFC_process.md
> +* When abandoned - RFC should be updated with `Abandon reason`.
Abandon.

2021-08-03 15:02 UTC, smores56 approved these changes

2021-08-03 15:09 UTC, merged