docs: rfc development process
epiphany-platform/CommonDataLayer pull request #668
Opened 2021-07-28 07:47 UTC by Kononnable

Should clarify some things about what to do with tasks during a sprint.

Some of it is proposals, others are writing down what we're already using. So as usual everything is up for discussion.

Rendered: https://github.com/epiphany-platform/CommonDataLayer/blob/rfc-dev-process/docs/rfc/NAF-Development_process.md

I did not make changes to RFC lists etc, those things are planned for a lot of changes, will add once PR is closer to merging.

2021-07-28 08:01 UTC, frondeus commented on docs/rfc/NAF-Development_process.md
> +ACCEPTANCE TESTS - author of RFC describing the feature, can be changed to another person
ACCEPTANCE TEST is not for RFC

2021-07-28 08:20 UTC, Kononnable commented on docs/rfc/NAF-Development_process.md
> +ACCEPTANCE TESTS - author of RFC describing the feature, can be changed to another person
Most feature changes/additions are based on RFC. Acceptance tests are not part of RFC process, however, It might be good to let the creator of RFC that change is based on to check for covering all the cases after the change is implemented. In most scenarios, this should be a person knowing what exactly he/she proposed, what use cases they were trying to solve, etc.
I'm proposing RFC creator here to make sure that there is no miscommunication on what RFC creator and the team know about this change solving user cases. RFC should cover all the use cases, but sometimes things go missing - this is just a fallback check.

2021-08-02 09:46 UTC, esavier requested changes

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| ACCEPTANCE TESTS | GENERAL TESTS   | Functionality works as defined in documentation |
we usually do not have up to date docs, you mean RFC? also some things do not have RFCs, then what

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| GENERAL TESTS    | DONE            | Functionality works on all supported configurations, corner cases, error handling are covered by tests |
that requires test driven development, which in turn requires us to first do spec, then tests, then actually code,

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| ACCEPTANCE TESTS | IN PROGRESS     | Adding acceptance tests reviled that some parts of the functionality are missing/major use case is not working correctly. If that use case wasn't covered by doc
again by docs you mean RFC?
ususally it should be done case by case since there are a lot of things that can go wrong in that case,

If usecase was not covered in the docs it means it's either out of scope or rfc is done incorrectly.
how do you know if use case is missing if it's not in the docs? Additionally, i would say it's architect responsibility to check if rfc covers all use cases and define the scope of the feature according to people who requested it.

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| CODE REVIEW | GENERAL TESTS| Code quality is fine, task should go to the top of the column(prioritizing) |
its not always on the top, its done so per usecase

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| GENERAL TESTS | DONE | Functionality works on all supported configurations, corner cases, error handling are covered by tests  |
its not defined what is configuration, nor we have tests to do that. There is a lot going on in this sentence.
We can not afford to enforce it right now despite how much i would love to.

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +|GENERAL TESTS | TO DO | Bug was not resolved. It's up to the tester to decide if the issue closed(during testing another wrong behavior was observed) or sent back to TO DO(the same wrong behavior st
"...ck person previously implementing the ta..." missing comma i guess

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +|GENERAL TESTS | TO DO | Bug was not resolved. It's up to the tester to decide if the issue closed(during testing another wrong behavior was observed) or sent back to TO DO(the same wrong behavior st
well, a lot of missing commas...

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +|GENERAL TESTS | TO DO | Bug was not resolved. It's up to the tester to decide if the issue closed(during testing another wrong behavior was observed) or sent back to TO DO(the same wrong behavior st
why person doing it previously should be assigned?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +|GENERAL TESTS | TO DO | Bug was not resolved. It's up to the tester to decide if the issue closed(during testing another wrong behavior was observed) or sent back to TO DO(the same wrong behavior st
Prioritization is another topic and again, should be done in per-case scenario

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| CODE REVIEW | DONE  | Documentation quality is fine |
can't we just mention that docs are not a subject for testing?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| CODE REVIEW | DONE  | RFC meeting ended with a positive conclusion. Problems mentioned at the meeting were fixed. PR with RFC are merged. |
what if rfc is a r'n'd and rfc do not have conclusion?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +| CODE REVIEW | DONE  | Code quality is fine, change works correctly(manual testing may be required) |
what if internal enhancement should go through the testing? i.e. library was changed or something similar?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +- GENERAL TESTS: waiting for automated and/or manual tests to be done on the functionality - checking for corner cases, proper error handling/propagation, testing in multiple different configurations
Manual testing have to be performed by developer asignedto the task (code author). manual testing should (but not must) be done again by the reviewer.

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +- ACCEPTANCE TESTS: waiting for automated tests to be written on new/changed functionality. Those tests should focus mostly on covering all of the use cases - check if business logic is implemented p
those are done automatically, why do we need to for another state of something being done automatically by the github?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> + In general, tasks taken for the sprint should be finished by end of the sprint. However, it's common to define some states which will be treated as valid for sprint end.
they are not, since they can drop back to todo, its manager's decision if sprint is delivered.

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +Due to the difference in development vs testing manpower I recommend we don't treat ** feature-related** tasks in the GENERAL TESTING state as not-delivered. Such tasks should be added to the next sp
how would you mark something as non feaure-related?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +Due to the difference in development vs testing manpower I recommend we don't treat ** feature-related** tasks in the GENERAL TESTING state as not-delivered. Such tasks should be added to the next sp
> Such tasks should be added to the next sprint in the same column.

again, case by case

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +> Note: Bugs in the GENERAL TESTING state should mark sprint as undelivered. They can move tasks back on the pipeline - they check if the issue was solved(with feature-related tasks this requirement
> Bugs in the GENERAL TESTING state should mark sprint as undelivered. They can move tasks back on the pipeline

...and again, case by case, some should, some shouldn't

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +Those are general rules - we may make exceptions on per-issue cases(e.g. someone is out of office for the rest of the sprint, etc.).
sooooo... those are the rules, but we will still do it, you know, case-by-case :wink:  ?

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +IN PROGRESS - person actively working on the issue
persons involved in the issue, you do not have to be working on it full time, or in cases of per-programming it will be weird.

2021-08-02 09:46 UTC, esavier commented on docs/rfc/NAF-Development_process.md
> +TODO - no assign, exceptions: bug issues getting back from GENERAL TESTS state(person implementing the issue), on planning we may decide that specific task should be done by a specific person(on per
>  on planning we may decide that specific task should be done by a specific person(on per task basis)

and how will you mark it?
whats wrong in asking on comms person who is assigned if its free to be taken?

2021-08-04 09:15 UTC, Kononnable commented
Closing as the idea was completely misunderstood by at least half of the team.  I don't think moving these ideas forward is worth the time and energy investment in the process.

2021-08-04 09:15 UTC, closed without merging