docs: rfc: Custom Data Passthrough
epiphany-platform/CommonDataLayer pull request #687
Opened 2021-08-11 12:36 UTC by esavier

2021-08-13 08:09 UTC, frondeus commented on docs/SUMMARY.md
> +    - [0021 - Custom Data Passthrough](./rfc/0020_Custom_Data_Passthrough_01.md)
```suggestion
    - [0021 - Custom Data Passthrough](./rfc/0021_Custom_Data_Passthrough_01.md)
```

2021-08-13 08:11 UTC, frondeus submitted a review, later dismissed

2021-08-17 11:09 UTC, Kononnable commented on docs/rfc/0020_Custom_Data_Passthrough_01.md
> +            "data": {...}
Everything stored in data is user data, or everything stored in passthrough is user data(data property is optional, multiple user properties may exist)?
Later in the text you refer to `options.passthrough`, not `options.passthrough.data`.

2021-08-19 07:03 UTC, esavier commented on docs/rfc/0020_Custom_Data_Passthrough_01.md
> +            "data": {...}
based on the other passthrough RFC there is another property, options.passthrough.metadata (or headers for what i care), that does the same but takes data not from a field but from a headers. 
also there will be other options like options.router.valdidate = bool 

we can not cover "all" the things that are in pass through since we can not deserialize it, anything extra will be a malformed message

2021-08-23 07:49 UTC, frondeus commented on docs/features/index.md
> +| CDLF-00021-00 | Custom Data Passthrough                | TechSpec   | -----       | [RFC](../rfc/0020_Custom_Data_Passthrough_01.md)                        |
invalid link reference

2021-08-23 09:54 UTC, esavier commented on docs/features/index.md
> +| CDLF-00021-00 | Custom Data Passthrough                | TechSpec   | -----       | [RFC](../rfc/0020_Custom_Data_Passthrough_01.md)                        |
0020_Custom_Data_Passthrough_01 ? fixed

2021-08-23 10:28 UTC, frondeus approved these changes

2021-08-23 22:11 UTC, smores56 requested changes

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +This features is added to comply with systems that uses some fields that are not specifically used by CDL itself, but are needed forther down the pipeline.
```suggestion
This feature is being added to allow compatibility with systems that require metadata coordinated with data entering the CDL. Specifically, when that metadata is not needed by the CDL, but further down the pipeline.
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +new format:
```suggestion
New Format:
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +Current format:
```suggestion
Current Format:
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +* general api tests
```suggestion
* General API tests
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +## References:
Since these aren't visible in the rendered MD document, you should not have a title here.

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +This field should be treated as fully optional. Data inside `options.passthrough` structure should not be acted upon in any capacity - is not stored nor used.
```suggestion
This field should be treated as fully optional. Data inside the `options.passthrough` object should not be acted upon in any capacity, including storage or usage.
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +Currently, we do not expect any conflicts with internal formats.
```suggestion
Currently, we do not expect any conflicts with internal formats, as the new field is purely additive.
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +Fields provided have to go through the system and be emitted in Command Service's notification system. Since this data is not used, its not going to be provided for notification methods in materializ
```suggestion
The provided fields have to go through the system and be emitted by the Command Service's notification system. Since this data is not used, it should not be provided for notification methods in materialization or anywhere further than the data storage layer, excluding the database itself.
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +The notification format is so far not defined, and as so there is no way to describe what the output should be. Therefore, it is left for implementor to decide.
```suggestion
The notification format is not yet defined, and as such there is no way to describe what the output should be. Therefore, it is left for the implementer to decide.
```

2021-08-23 22:11 UTC, smores56 commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +If later RFC or documentation will define the format, it will have to be changed then.
```suggestion
If a later RFC or documentation defines a format, the notification format will have to be changed then.
```

2021-08-23 22:15 UTC, esavier commented on docs/rfc/0021_Custom_Data_Passthrough_01.md
> +## References:
roger roger

2021-08-24 02:36 UTC, smores56 approved these changes

2021-08-24 02:36 UTC, merged