chore: tracing utils refactor
epiphany-platform/CommonDataLayer pull request #703
Opened 2021-08-18 12:25 UTC by frondeus

2021-08-19 06:49 UTC, esavier submitted a review, later dismissed
I am starting to think that we need to move "0.0.0.0" to configuration option, but this is not about this PR, for me it looks okay, approved
i will merge it today if there are no more comments

2021-08-19 14:10 UTC, smores56 requested changes

2021-08-19 14:10 UTC, smores56 commented on crates/schema-registry/src/rpc.rs
> +            tracing::info!("Ok!");
Can you put a more descriptive message here?

2021-08-19 14:58 UTC, frondeus commented on crates/utils/Cargo.toml
> +tracing_utils           = { path    = "crates/tracing", features = ["with_kafka", "with_grpc", "with_http"] } # TODO: Use these feature flags
Yes. We need to either create separate features for this `utils` crate or split it further into smaller crates.

2021-08-19 15:01 UTC, smores56 approved these changes

2021-08-20 12:53 UTC, luke-biel approved these changes

2021-08-20 12:53 UTC, merged