Query-service-ts
epiphany-platform/CommonDataLayer pull request #73
Opened 2020-12-04 11:09 UTC by Tesel

2020-12-04 13:26 UTC, Kononnable commented
This is finished or should it be marked as a draft? (no description etc.)

2020-12-04 14:25 UTC, Tesel commented
> 
> 
> This is finished or should it be marked as a draft? (no description etc.)
Fixed

2020-12-07 08:25 UTC, frondeus commented on examples/deploy/docker-compose.yml
> +    links:
> Links are a legacy option. We recommend using networks instead.

2020-12-07 09:23 UTC, Tesel commented on examples/deploy/docker-compose.yml
> +    links:
fixed

2020-12-07 09:32 UTC, frondeus submitted a review, later dismissed

2020-12-07 09:33 UTC, frondeus commented
LGTM but I'd wait with merging and add helm charts

2020-12-08 02:36 UTC, esavier requested changes
Looks nice, I see no issues with code so far.
one requested change is to fix Pull Message to conform with angular style, please check other pull requests for clues, also please remember to merge via squash

2020-12-08 09:53 UTC, Tesel commented
> 
> 
> Looks nice, I see no issues with code so far.
> one requested change is to fix Pull Message to conform with angular style, please check other pull requests for clues, also please remember to merge via squash

What do you mean with `angular style`?

2020-12-08 16:02 UTC, frondeus commented
He meant that in CDL we try to follow a similar commit format like in https://gist.github.com/brianclements/841ea7bffdb01346392c

2020-12-09 12:30 UTC, esavier approved these changes

2020-12-09 13:25 UTC, frondeus approved these changes

2020-12-09 13:25 UTC, esavier approved these changes

2020-12-09 13:29 UTC, merged