chore: test: update k8s deployment
epiphany-platform/CommonDataLayer pull request #731
Opened 2021-08-30 06:16 UTC by esavier

2021-08-30 08:58 UTC, frondeus approved these changes

2021-08-31 09:07 UTC, Kononnable commented
Please run deployment tests on CI before merging. As I recall `v1.21.3` didn't work with the current setup(#662).

2021-08-31 09:09 UTC, Kononnable requested changes
Blocking so no one merges that by mistake before running changed workflow to test if it works.

2021-09-01 14:18 UTC, Kononnable approved these changes

2021-09-01 14:28 UTC, merged