Ci speedup
epiphany-platform/CommonDataLayer pull request #74
Opened 2020-12-05 14:49 UTC by Kononnable

- Add cache to our CI tests(~3x speedup).
- Check lock file compatibility on each build 

Currently cache usage default storage(cloud). We can probably get under 2 minutes if we configure storage locally: change caching method or point CI to local cache server: https://github.com/actions/toolkit/blob/7ad5004f874ebbe42d119b785dacb4360a0ce8f8/packages/cache/src/internal/cacheHttpClient.ts#L33

@luke-biel: I see `deny.toml` file, but don't see any CI action which uses that file. Is that intentional, or have we removed too much last time we changed github actions?

2020-12-07 07:11 UTC, frondeus commented on .github/workflows/testing.yml
> +  CARGO_INCREMENTAL: 0
Why disabling incremental compilation?

2020-12-07 10:04 UTC, Kononnable commented on .github/workflows/testing.yml
> +  CARGO_INCREMENTAL: 0
- first time(clean) compilation is slower with incremental builds(which is not really an issue when caching)
- incremental compilation gives us a lot of artifacts(size) - pushing incremental build artifacts to the cloud and fetching it again on next build in most cases takes more time then building without incremental. This might be different if files are cached locally.

2020-12-07 10:51 UTC, luke-biel commented
> @luke-biel: I see `deny.toml` file, but don't see any CI action which uses that file. Is that intentional, or have we removed too much last time we changed github actions?
It wasn't set up in the first place.

2020-12-07 12:06 UTC, Kononnable commented
So we ran it manually before? It looks like something which should be automatized.

2020-12-07 12:15 UTC, luke-biel commented
Problem is, there's a lot of issues that would need to be checked before so, otherwise we'd just turn our pipeline red.
I've added it as a way to check licenses easily back then, I think it's even mentioned somewhere. There was no time to do anything more.

2020-12-08 02:31 UTC, esavier requested changes
please fix the merge's name

2020-12-09 14:42 UTC, luke-biel approved these changes

2020-12-09 16:47 UTC, esavier approved these changes

2020-12-09 21:18 UTC, merged