feat:(druid): Move druid to timeseries service
epiphany-platform/CommonDataLayer pull request #80
Opened 2020-12-10 10:29 UTC by Tesel

Druid was supposed to be moved at timeseries quesry service, so i made it

2020-12-10 10:52 UTC, frondeus approved these changes

2020-12-10 12:09 UTC, luke-biel requested changes
Druid ain't that simple.
It is not turned on (cannot be used), and when integrating we need to make sure it and vm use same gRPC protocol.

Definitely remove lines added to proto.
You can either put work in integrating druid inte qs or leave it as is but adding comment for future us that druid is WIP and needs to be readjusted. I'm okay with you leaving it to us since it's not related directly to VM. But if you have spare time, adjusting would be of great help.

2020-12-10 12:09 UTC, luke-biel commented on query-service-ts/proto/query.proto
> +
This shouldn't be added, we want to have unified interface

2020-12-14 08:42 UTC, Kononnable commented on query-service/src/druid.rs
> +// This service is not supported atm
Who will see that comment? I think using `unimplemented` or todo in place something is lacking would be a better solution. 
Unless that's comment just for you to not forget about something - in that case please make PR as draft for the time being.

2020-12-15 09:34 UTC, Tesel commented on query-service/src/druid.rs
> +// This service is not supported atm
Removed

2020-12-15 12:09 UTC, luke-biel commented
I meant that we should move code but not integrate it, not just add comment, but well, let's not waste more time on this. I'm closing it.

2020-12-15 12:09 UTC, closed without merging