Refactor/change internal msg format
epiphany-platform/CommonDataLayer pull request #87
Opened 2020-12-14 12:26 UTC by luke-biel

2020-12-14 13:30 UTC, Kononnable requested changes
What is the reasoning behind those changes? It's not clear to me why we should have both cases.

2020-12-14 13:30 UTC, Kononnable commented on utils/src/message_types.rs
> +    #[serde(default = "default_timestamp")]
Will lead to logic error which are hard to find. This should be set explicitly.

2020-12-14 13:30 UTC, Kononnable commented on examples/deploy/docker-compose.yml
> +      POSTGRES_SCHEMA: cdl
Was this intended or is it some change which is applicable only to your local environment(I have no idea if schema would be created automatically)?

2020-12-14 13:30 UTC, Kononnable commented on command-service/src/output/victoria_metrics/mod.rs
> -        #[test_case("y00=32q,y01=14.0f" => matches Err(Error::DataIsNotValidJson(_)))]
Removing test case in refactor PR isn't a good idea.

2020-12-14 14:06 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> -        #[test_case("y00=32q,y01=14.0f" => matches Err(Error::DataIsNotValidJson(_)))]
It's not applicable anymore. RawValue cannot be an invalid json, str could.

2020-12-14 14:09 UTC, luke-biel commented on utils/src/message_types.rs
> +    #[serde(default = "default_timestamp")]
Then DataRouter will require timestamps. This is now shared between DR and CS. I could make it optional, or '-1' by default. I don't know however if it's better. What do you think?

2020-12-14 14:12 UTC, luke-biel commented on examples/deploy/docker-compose.yml
> +      POSTGRES_SCHEMA: cdl
It's intended. Scripts provision this schema, example got out of sync.

2020-12-14 14:18 UTC, luke-biel commented
> What is the reasoning behind those changes? It's not clear to me why we should have both cases.

I don't understand which `both cases` are you referring to. If it's Owned and Borrowed message - it was already there. CS had Owned message which was called GenericMessage. I replaced it with common construct, and removed one unnecessary allocation in the process.

2020-12-14 15:54 UTC, USSAMOH2 requested changes

2020-12-14 15:54 UTC, USSAMOH2 commented on utils/src/message_types.rs
> +    #[serde(default = "default_timestamp")]
Between those two alternatives, I'd think that making it into a `pub timestamp: Option<i64>` makes it safer.

2020-12-14 15:54 UTC, USSAMOH2 commented on command-service/src/report/mod.rs
>                  producer: config.producer.clone(),
If this consumes `self`, then we probably don't need to `clone` these.

2020-12-15 09:04 UTC, Kononnable commented on utils/src/message_types.rs
> +    #[serde(default = "default_timestamp")]
>Then DataRouter will require timestamps. 

I say this shows need for another structure. Data router input format(client data) can't have this field - it's internal to CDL(in theory we could just overwrite its value but its very unclean). If we allow users to use it we would lock ourselves to current format of data(timestamp) which is likely to change in the future. After some time we would get questions on why something doesn't work. We don't support inserting historical data at this point and people would try to use it as such and probably broke their CDL data in some future version.

2020-12-15 09:08 UTC, Kononnable commented on command-service/src/output/victoria_metrics/mod.rs
> -        #[test_case("y00=32q,y01=14.0f" => matches Err(Error::DataIsNotValidJson(_)))]
It's a refactor so errors/tests don't get obsolete. The only possibility is if this error was redundant in the first place(code could never be executed because of logic conditions, technically value could be just unwrapped).

2020-12-15 09:14 UTC, Kononnable commented on command-service/src/output/victoria_metrics/mod.rs
> -        #[test_case("y00=32q,y01=14.0f" => matches Err(Error::DataIsNotValidJson(_)))]
Or the other way around - in this PR we skip this error because of unwraping
`data: serde_json::from_str(&self.data.get()).expect("RawValue wasn't valid json Value"),`

2020-12-15 10:06 UTC, luke-biel commented on command-service/src/output/victoria_metrics/mod.rs
> -        #[test_case("y00=32q,y01=14.0f" => matches Err(Error::DataIsNotValidJson(_)))]
```        let event: BorrowedInsertMessage =
            serde_json::from_str(json).map_err(Error::PayloadDeserializationFailed)?;
``` is a place where this error will be caught now.
This refactor removed one unnecessary conversion. Earlier we checked if json was ok on deserializaton and then on serialization. Propagating type `InternalMessage` and RawValue means it is checked only on deserialization, and RawValue guarantees it holds a valid json. `build_line_protocol` had `payload: [u8]` argument, now accepts `payload: RawValue`. Slice could contain errors (in theory), RawValue can't. This function cannot, literally, fail here. Test is obsolete, because function changed.

2020-12-15 10:10 UTC, luke-biel commented on utils/src/message_types.rs
> +    #[serde(default = "default_timestamp")]
Ok, this was my misconception about cdl's timestamp. This needs separate type for DataRouter, since DR isn't supposed to receive timestamps.

2020-12-15 11:28 UTC, Kononnable reviewed
I don't like how FullReportSender is implemented(or at least its name compared to what it does), not sure if `BorrowedInsertMessage` and `OwnedInsertMessage` could be handled better(seems like that but don't see a concrete solution yet).
Anyway those issues should not block that PR.

Only the one more comment about moving `DataRouterInsertMessage` should be addressed, otherwise LGTM.

2020-12-15 11:28 UTC, Kononnable commented on data-router/src/main.rs
> +pub struct DataRouterInsertMessage<'a> {
I think this should go back to utils. Even if it's used only here it would be easier to find common message types when they're in one place.

2020-12-15 11:42 UTC, luke-biel commented on data-router/src/main.rs
> +pub struct DataRouterInsertMessage<'a> {
done

2020-12-15 11:45 UTC, luke-biel commented
> I don't like how FullReportSender is implemented(or at least its name compared to what it does), not sure if `BorrowedInsertMessage` and `OwnedInsertMessage` could be handled better(seems like that but don't see a concrete solution yet).
> Anyway those issues should not block that PR.
> 
> Only the one more comment about moving `DataRouterInsertMessage` should be addressed, otherwise LGTM.

I introduced NullObjectPattern because I could't come up with anything better that would not allocate memory when Reporting is disabled (coz payload has to be copied, for DE). Maybe we can hide that behind a feature? I'm just not sure whether that's the way.

2020-12-15 13:13 UTC, Kononnable approved these changes

2020-12-15 13:14 UTC, merged