docs: cdl-cli basic usage and schema-repo interaction
epiphany-platform/CommonDataLayer pull request #89
Opened 2020-12-14 13:36 UTC by esavier

fixes #88

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +`cdl --registry-address "http:/localhost:6400 schema <add|get|names|update> --name <schemaname> \
```suggestion
`cdl --registry-address "http://localhost:6400 schema <add|get|names|update> --name <schemaname> \
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +Cdl-cli is currently the only tool able to interact with Schema-Registry. Its purpose is to interact with the Schema-Registry database by setting and viewing its content.
```suggestion
Cdl-cli is currently the only tool able to interact with schema registry. Its purpose is to interact with the schema registry database by setting and viewing its content.
```
I think we never use schema registry written as crate name in the docs.

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +Please mind that this tool is a reference. Schema-Registry port should be configured open, and every tool that is able to communicate to it should be able to set and get information about schemas fro
```suggestion
Please mind that this tool is a reference. Schema registry port should be configured open, and every tool that is able to communicate to it should be able to set and get information about schemas from schema registry. Currently only schema regisry only supports GRPC protocol, but there are some progress with both REST and webgui parts, which may be presented in the future as GRPC's alternative.
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +views are a WIP feature, currently not used widely beside some cases in development.
```suggestion
Views are a WIP feature, currently not used widely beside some cases in development.
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +#### manipulate views
```suggestion
#### Manipulate views
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +#### manipulate schemas
```suggestion
#### Manipulate Schemas
```
empty section?

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +###### add schema
```suggestion
###### Add schema
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +- if `--file` is provided, specific file must have valid json inside.
```suggestion
- If `--file` is provided, specific file must have valid json inside.
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +- if `--file` is missing, you will be asked to provide json inside cli,
```suggestion
- If `--file` is missing, you will be asked to provide json inside cli,
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +  to do so, insety valid json, followed by newline, and then press `ctrl+d` to finish editing
```suggestion
  To do so, insert valid json, followed by newline, and then press `ctrl+d` to finish editing
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +###### list schemas
```suggestion
###### List schemas
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +- will print all existing schema names and IDs:
```suggestion
Will print all existing schema names and IDs:
```

2020-12-14 14:17 UTC, Kononnable commented on docs/CDL-Cli.md
> +`cdl --registry-address "http:/localhost:6400 schema names`
```suggestion
`cdl --registry-address "http://localhost:6400 schema_names`
```
Can we pass multiple names here?

2020-12-14 14:17 UTC, Kononnable commented on docs/schema_registry.md
> +Schema Registy (also, `SR` for short) is responible for storing configuration about the data types handled by CDL. Schema Registry is a persistant graph database, that can be interfaced via grpc (oth
```suggestion
Schema registry (also, `SR` for short) is responsible for storing configuration about the data types handled by CDL. It is a persistent graph database, that can be queried via grpc (other means of interaction are in progress). Currently there is no GUI nor TUI. User interaction consist of internal tool [CDL-cli][CDL-cli]. There is also basic replication ability built-in.
```

2020-12-14 14:17 UTC, Kononnable commented on docs/schema_registry.md
>  - nothing on its own
Technically it checks if passed kafka topic exists. Not sure if we should mention it here as it's not a cdl service.

2020-12-14 15:11 UTC, esavier commented on docs/CDL-Cli.md
> +`cdl --registry-address "http:/localhost:6400 schema names`
nah, i dont think so, 
i also don't know what would happen if multiple jsons are provided inside file or in body

2020-12-14 15:25 UTC, USSAMOH2 requested changes
You should also rename this document to `CDL-CLI.md`.

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +Cdl-cli is currently the only tool able to interact with schema registry. Its purpose is to interact with the schema registry database by setting and viewing its content.
Both CDL and CLI are acronyms, and so both should be capitalized.

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +Cdl-cli is currently the only tool able to interact with schema registry. Its purpose is to interact with the schema registry database by setting and viewing its content.
```suggestion
The CDL-CLI is the official tool for interacting with the CDL's Schema Registry, used both for viewing and manipulating schemas and their respective data.
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +Please mind that this tool is a reference. Schema registry port should be configured open, and every tool that is able to communicate to it should be able to set and get information about schemas fro
```suggestion
For this tool to work, please make sure that the Schema Registry's gRPC server is listening on a public port. Currently, the Schema Registry only exposes a gRPC API, which is faster than a JSON API but less convenient to use. There is some progress with a JSON API for convenience, as well as a TUI (terminal user interface) and a website.
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +#### Manipulate views
```suggestion
#### Manipulate Views
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +- random schema id will be assigned to the request
```suggestion
- If `--file` is missing, the CLI will expect JSON to be piped in over `stdin`.
- A schema containing `true` will accept any valid JSON data.
- New schemas are assigned a random UUID on creation, which will be printed after a successful insert.
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/schema_registry.md
> +Schema registry (also, `SR` for short) is responsible for storing configuration about the data types handled by CDL. It is a persistent graph database, that can be queried via grpc (other means of in
```suggestion
The Schema Registry (`SR` for short) is responsible for storing configuration about the data types handled by CDL. It is a persistent graph database, that can be queried via gRPC (other means of interaction are in progress). Currently there is no GUI nor TUI; user interaction is currently performed with the [CDL-CLI][CDL-CLI]. Replication across multiple instances of the Schema Registry is supported.
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/schema_registry.md
> +[CDL-cli]: CDL-cli.md
```suggestion
[CDL-CLI]: CDL-CLI.md
```

2020-12-14 15:25 UTC, USSAMOH2 commented on docs/CDL-Cli.md
> +`cdl --registry-address "http:/localhost:6400 schema names`
```suggestion
###### List Schemas

 To print all existing schema names and their respective ID's:
`cdl --registry-address "http://localhost:6400 schema names`
```

2020-12-23 13:29 UTC, esavier commented on docs/schema_registry.md
>  - nothing on its own
i am leaving it out then?

2020-12-23 13:36 UTC, luke-biel approved these changes

2020-12-23 13:39 UTC, Kononnable submitted a review, later dismissed

2020-12-23 13:39 UTC, luke-biel approved these changes

2020-12-23 14:40 UTC, luke-biel approved these changes

2020-12-23 14:40 UTC, merged