Add acceptance tests to command-service
epiphany-platform/CommonDataLayer pull request #9
Opened 2020-11-10 14:20 UTC by luke-biel

Resolves #7 command-service

2020-11-16 19:46 UTC, luke-biel commented
Integration tests require a bit more thinking. I cannot run them on github actions because they require several services ran on docker - this is suboptimal. We need to rethink how we want to approach testing things and probably integration will be done via some other CI.

2020-11-19 06:49 UTC, USSAMOH2 requested changes

2020-11-19 06:49 UTC, USSAMOH2 commented on tests/common/postgres.py
> +    curr = db.cursor()
Should you close this cursor as well?

2020-11-19 06:49 UTC, USSAMOH2 commented on tests/common/__init__.py
> +    for i in range(1, retries):
```suggestion
    for _ in range(1, retries):
```

2020-11-19 06:49 UTC, USSAMOH2 commented on tests/command_service/test_postgres_insertion.py
> +    producer\
Is the formatting terrible without these ugly backslashes?

2020-11-19 06:49 UTC, USSAMOH2 commented on tests/command_service/test_postgres_insertion.py
> +    db, data, expected = prepare
```suggestion
def test_inserting(db, data, expected):
```

2020-11-19 06:49 UTC, USSAMOH2 commented on tests/README.md
> +eg. db_shrinker_postgres. Named after application they test.
I'd normally do this as a table, but if you don't care enough or really like what you already have here, then feel free to leave it.

2020-11-19 06:51 UTC, USSAMOH2 requested changes

2020-11-19 06:51 UTC, USSAMOH2 commented on tests/common/__init__.py
> +    delay = kwrags.get('delay', 6)
```suggestion
def retry_retrieve(fetch, expected_rows, retries=10, delay=6):
```

2020-11-20 11:47 UTC, luke-biel commented on tests/command_service/test_postgres_insertion.py
> +    db, data, expected = prepare
Can't do, pytest finds fixtures based on argument name

2020-11-20 11:48 UTC, luke-biel commented on tests/command_service/test_postgres_insertion.py
> +    producer\
Didn't notice it. Autoformater added them because of line too long by 1 character =,=

2020-11-20 12:00 UTC, luke-biel commented on tests/common/__init__.py
> +    delay = kwrags.get('delay', 6)
Wasn't sure I can do this

2020-11-20 12:01 UTC, luke-biel commented on tests/README.md
> +eg. db_shrinker_postgres. Named after application they test.
Too few apps for now I'd say.

2020-11-24 14:22 UTC, USSAMOH2 approved these changes

2020-11-25 15:56 UTC, USSAMOH2 approved these changes

2020-11-27 12:41 UTC, esavier approved these changes

2020-11-27 12:55 UTC, merged