feat(query-service-ts): Added raw queries support for VictoriaMetrics
epiphany-platform/CommonDataLayer pull request #90
Opened 2020-12-14 16:21 UTC by MrDarthShoe

https://github.com/epiphany-platform/CommonDataLayer/projects/4#card-49504058

2020-12-15 09:08 UTC, frondeus commented on query-service-ts/src/victoria.rs
> +        let body: serde_json::Value = reqwest::get(&url)
What about post requests? Victoriametrics supports POST methods for example in `/query_range` because URL encoding has some limits. Also I think Graphite Tags API is using POST methods.

2020-12-15 09:27 UTC, MrDarthShoe commented on query-service-ts/src/victoria.rs
> +        let body: serde_json::Value = reqwest::get(&url)
Aren't POST's only for inserting data in PromQL? If so, adding metrics should be through command-service (or even directly to VictoriaMetrics, without CDL), not query-service-ts as I understand. In normal query-service we "allow" users to make INSERT's, just because we don't want to filter raw queries

2020-12-15 10:24 UTC, frondeus commented on query-service-ts/src/victoria.rs
> +        let body: serde_json::Value = reqwest::get(&url)
Not really. Victoriametrics provides API for Prometheus - https://github.com/VictoriaMetrics/VictoriaMetrics#prometheus-querying-api-usage.
Now If you follow link to Prometheus API - https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries
you can see both `GET` and `POST` methods are supported for **querying**, and not only for inserting.

> You can URL-encode these parameters directly in the request body by using the POST method and Content-Type: application/x-www-form-urlencoded header. This is useful when specifying a large query that may breach server-side URL character limits.

2020-12-18 13:28 UTC, luke-biel requested changes
Some documentation on usage of this is a must. Even an example of json body that raw queries are supposed to send will be ok. You can place it in README of this crate.

Also:
> @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
> @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
Don't delete comments, even if they are useless/obsolete. We have no idea what was there now.

2020-12-18 13:36 UTC, MrDarthShoe commented
> Some documentation on usage of this is a must. Even an example of json body that raw queries are supposed to send will be ok. You can place it in README of this crate.
> 
> Also:
> 
> > @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
> > @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
> 
> Don't delete comments, even if they are useless/obsolete. We have no idea what was there now.

I planned adding example in query-router openapi after router part will be done, but surely I can add it in readme here too

2020-12-18 13:53 UTC, luke-biel commented
> > Some documentation on usage of this is a must. Even an example of json body that raw queries are supposed to send will be ok. You can place it in README of this crate.
> > Also:
> > > @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
> > > @MrDarthShoe MrDarthShoe deleted a comment from frondeus 21 hours ago
> > 
> > 
> > Don't delete comments, even if they are useless/obsolete. We have no idea what was there now.
> 
> I planned adding example in query-router openapi after router part will be done, but surely I can add it in readme here too (which is better as user can talk directly to QS without QR)

Ok, then it's fine.

2020-12-18 13:53 UTC, luke-biel approved these changes

2020-12-21 08:56 UTC, frondeus approved these changes

2020-12-21 10:34 UTC, merged