Wpo command service grpc
epiphany-platform/CommonDataLayer pull request #91
Opened 2020-12-14 16:25 UTC by frondeus

Waiting for base PR

2020-12-16 16:04 UTC, luke-biel requested changes

2020-12-16 16:08 UTC, frondeus commented on command-service/src/main.rs
> +    input_config: InputConfig,
Unfortunately, clap supports only one subcommand (and that's what you are proposing) and in `command_service` we already used it for `output_plugin` so we can choose between `postrgres`, `victoriametrics` etc.

This is indeed the sad part because I don't like `Option` either. It's just... lesser evil.

In theory, I could make `ingestion_method` a part of every variant in `output_plugin` or vice-versa (so instead of two subcommands on the same level, one subcommand would be nested into another), but it's still ugly and cumbersome from a code-point perspective.

2020-12-16 16:08 UTC, frondeus commented on command-service/src/args.rs
> +    pub enum Input {
I agree

2020-12-16 16:09 UTC, frondeus commented on command-service/src/main.rs
> +    input_config: InputConfig,
That's why I was thinking about introducing a config file for the command service. It would solve our limitations (and probably introduce new ones ;-) )

2020-12-16 16:39 UTC, luke-biel commented on command-service/src/main.rs
> +    input_config: InputConfig,
Config file is cool till you start using kubernetes i guess. Then, ways to propagate it all look hacky to me.

2020-12-17 16:52 UTC, Kononnable commented on utils/src/messaging_system/consumer.rs
> +            .set("enable.auto.commit", "false")
Did you test whole pipeline and checked that it works correctly and no message is redelivered?
I don't see any other changes regarding this setting.

2020-12-17 17:39 UTC, frondeus commented on utils/src/messaging_system/consumer.rs
> +            .set("enable.auto.commit", "false")
There is a change in `kafka.rs` - I added `message.ack()`. 
Unfortunately, I moved it to another file so Github couldn't catch it and diff it :(

What is more, I checked the code of `data_router` and `schema_registry/src/slave.rs` and surprisingly we were using `message.ack()` there properly (but not in command_service). But it was a pointless call for Kafka because the client committed messages before we called this method. It made more sense for RabbitMQ because we don't ack automatically there.

And yes, I did test it locally by running Kafka, data_router, schema_registry, and commad_service_postgres.
I'll provide additional changes to docker-compose tho to simplify the process cause I tried to run it without docker and its ugly :)

2020-12-17 17:41 UTC, frondeus commented on utils/src/messaging_system/consumer.rs
> +            .set("enable.auto.commit", "false")
Also to the helm chart

2020-12-17 19:17 UTC, Kononnable approved these changes

2020-12-17 23:47 UTC, luke-biel approved these changes
Don't bother with my comment, if you change it we'd have to redo approval, and this thing doesn't matter much. It's here just as a TIL.

2020-12-17 23:47 UTC, luke-biel commented on command-service/src/args.rs
> +    #[structopt(long, env = "INGESTION_METHOD", possible_values = &IngestionMethod::variants(), case_insensitive = true)]
`env` is enough, no need for `= "..."` here, structopt will create it automagically.

2020-12-18 08:01 UTC, merged