Use gRPC for communication between the Data Router and the Command Service
epiphany-platform/CommonDataLayer pull request #92
Opened 2020-12-14 16:49 UTC by USSAMOH2

For clean-up, this PR moved all gRPC definitions into a crate called `rpc`.

2020-12-14 17:15 UTC, frondeus commented on cdl-cli/src/actions/schema.rs
> +    insert_address: String,
I don't know if `insert_address` is right name. It can be either:
* Kafka topic
* GRPC address (URI)
* **OR** (technically but not realistically) - rabbitMQ exchange

2020-12-14 17:15 UTC, frondeus commented on command-service/src/input/config.rs
> +    pub port: u16,
I don't think we should replace it but make it optional, but my PR covers it.

2020-12-14 17:15 UTC, frondeus commented on command-service/src/input/service.rs
> +        self.task_limiter
You don't wanna spawn new task for GRPC handling. RPC needs to respond with an error if we fail to handle message.
Please note, if we simply respond with `Empty` and then crash, message will be lost. Fortunately, again my PR is going to fix it :)

2020-12-14 17:15 UTC, frondeus commented on schema-registry/src/error.rs
> -    NoTopic(String),
Now this whole feature for checking kafka topic is useless.. And if we are going to fully switch to GRPC, shouldn't we ping `insert_address` to validate if it exists?

2020-12-15 09:44 UTC, Kononnable requested changes

2020-12-15 09:44 UTC, Kononnable commented on cdl-cli/src/actions/schema.rs
> +    insert_address: String,
I would say `communication_channel` or something similar(generic) is more appropriate.
Same goes for rpc methods in schema registry.

2020-12-15 09:44 UTC, Kononnable commented on cdl-cli/src/actions/schema.rs
> +        .map(|v: String| Version::parse(&v))
Why explicit type?

2020-12-15 09:44 UTC, Kononnable commented on cdl-cli/src/args.rs
> +    GetInsertAddress {
As above - address doesn't cover all of the cases.

2020-12-15 09:44 UTC, Kononnable commented on command-service/src/input/config.rs
> +    pub port: u16,
It's better to keep refactor(extracting rpc crate) and feature changes in separate PRs so I would ask to remove all of feature changing changes from here, create another PR for that if necessary.

2020-12-15 16:40 UTC, USSAMOH2 commented
Closed in favor of https://github.com/epiphany-platform/CommonDataLayer/pull/91.

2020-12-15 16:44 UTC, closed without merging